// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const advanceRequestStep = `-- name: AdvanceRequestStep :one
UPDATE approval.requests SET current_step=current_step+1
WHERE id=$1 AND deleted_at IS NULL RETURNING id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at
`

func (q *Queries) AdvanceRequestStep(ctx context.Context, id uuid.UUID) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, advanceRequestStep, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OfficeID,
		&i.Amount,
		&i.CurrentStep,
		&i.TargetEntity,
		&i.TargetID,
		&i.Payload,
		&i.Reason,
		&i.Status,
		&i.RequestedByID,
		&i.DecidedByID,
		&i.DecisionNote,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const cancelRequest = `-- name: CancelRequest :one
UPDATE approval.requests SET status='cancelled'
WHERE id=$1 AND requested_by_id=$2 AND status='pending' AND deleted_at IS NULL RETURNING id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at
`

type CancelRequestParams struct {
	ID            uuid.UUID `json:"id"`
	RequestedByID uuid.UUID `json:"requested_by_id"`
}

func (q *Queries) CancelRequest(ctx context.Context, arg CancelRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, cancelRequest, arg.ID, arg.RequestedByID)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OfficeID,
		&i.Amount,
		&i.CurrentStep,
		&i.TargetEntity,
		&i.TargetID,
		&i.Payload,
		&i.Reason,
		&i.Status,
		&i.RequestedByID,
		&i.DecidedByID,
		&i.DecisionNote,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countRequests = `-- name: CountRequests :one
SELECT count(*) FROM approval.requests
WHERE deleted_at IS NULL
  AND ($1::boolean OR office_id = ANY($2::uuid[]))
  AND ($3::shared.request_status IS NULL OR status = $3)
  AND ($4::shared.request_type IS NULL OR type = $4)
`

type CountRequestsParams struct {
	AllScope  bool                 `json:"all_scope"`
	OfficeIds []uuid.UUID          `json:"office_ids"`
	Status    *SharedRequestStatus `json:"status"`
	Type      *SharedRequestType   `json:"type"`
}

func (q *Queries) CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequests,
		arg.AllScope,
		arg.OfficeIds,
		arg.Status,
		arg.Type,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO approval.requests
  (type, office_id, amount, current_step, target_entity, target_id, payload, reason, requested_by_id)
VALUES ($1,$2,$3,1,$4,$5,COALESCE($6,'{}')::jsonb,$7,$8) RETURNING id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at
`

type CreateRequestParams struct {
	Type          SharedRequestType `json:"type"`
	OfficeID      *uuid.UUID        `json:"office_id"`
	Amount        *string           `json:"amount"`
	TargetEntity  *string           `json:"target_entity"`
	TargetID      *uuid.UUID        `json:"target_id"`
	Column6       []byte            `json:"column_6"`
	Reason        *string           `json:"reason"`
	RequestedByID uuid.UUID         `json:"requested_by_id"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Type,
		arg.OfficeID,
		arg.Amount,
		arg.TargetEntity,
		arg.TargetID,
		arg.Column6,
		arg.Reason,
		arg.RequestedByID,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OfficeID,
		&i.Amount,
		&i.CurrentStep,
		&i.TargetEntity,
		&i.TargetID,
		&i.Payload,
		&i.Reason,
		&i.Status,
		&i.RequestedByID,
		&i.DecidedByID,
		&i.DecisionNote,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRequestApproval = `-- name: CreateRequestApproval :one
INSERT INTO approval.request_approvals (request_id, step_order, required_level)
VALUES ($1,$2,$3) RETURNING id, request_id, step_order, required_level, approver_id, decision, note, decided_at, created_at, updated_at, deleted_at
`

type CreateRequestApprovalParams struct {
	RequestID     uuid.UUID           `json:"request_id"`
	StepOrder     int32               `json:"step_order"`
	RequiredLevel SharedApproverLevel `json:"required_level"`
}

func (q *Queries) CreateRequestApproval(ctx context.Context, arg CreateRequestApprovalParams) (ApprovalRequestApproval, error) {
	row := q.db.QueryRow(ctx, createRequestApproval, arg.RequestID, arg.StepOrder, arg.RequiredLevel)
	var i ApprovalRequestApproval
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.StepOrder,
		&i.RequiredLevel,
		&i.ApproverID,
		&i.Decision,
		&i.Note,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createThreshold = `-- name: CreateThreshold :one
INSERT INTO approval.approval_thresholds
  (request_type, amount_from, amount_to, required_level, step_order, is_active)
VALUES ($1,$2,$3,$4,$5,COALESCE($6,true)) RETURNING id, request_type, amount_from, amount_to, required_level, step_order, is_active, created_at, updated_at, deleted_at
`

type CreateThresholdParams struct {
	RequestType   SharedRequestType   `json:"request_type"`
	AmountFrom    string              `json:"amount_from"`
	AmountTo      *string             `json:"amount_to"`
	RequiredLevel SharedApproverLevel `json:"required_level"`
	StepOrder     int32               `json:"step_order"`
	Column6       interface{}         `json:"column_6"`
}

func (q *Queries) CreateThreshold(ctx context.Context, arg CreateThresholdParams) (ApprovalApprovalThreshold, error) {
	row := q.db.QueryRow(ctx, createThreshold,
		arg.RequestType,
		arg.AmountFrom,
		arg.AmountTo,
		arg.RequiredLevel,
		arg.StepOrder,
		arg.Column6,
	)
	var i ApprovalApprovalThreshold
	err := row.Scan(
		&i.ID,
		&i.RequestType,
		&i.AmountFrom,
		&i.AmountTo,
		&i.RequiredLevel,
		&i.StepOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decideRequestApproval = `-- name: DecideRequestApproval :one
UPDATE approval.request_approvals SET approver_id=$3, decision=$4, note=$5, decided_at=now()
WHERE request_id=$1 AND step_order=$2 AND deleted_at IS NULL RETURNING id, request_id, step_order, required_level, approver_id, decision, note, decided_at, created_at, updated_at, deleted_at
`

type DecideRequestApprovalParams struct {
	RequestID  uuid.UUID           `json:"request_id"`
	StepOrder  int32               `json:"step_order"`
	ApproverID *uuid.UUID          `json:"approver_id"`
	Decision   SharedRequestStatus `json:"decision"`
	Note       *string             `json:"note"`
}

func (q *Queries) DecideRequestApproval(ctx context.Context, arg DecideRequestApprovalParams) (ApprovalRequestApproval, error) {
	row := q.db.QueryRow(ctx, decideRequestApproval,
		arg.RequestID,
		arg.StepOrder,
		arg.ApproverID,
		arg.Decision,
		arg.Note,
	)
	var i ApprovalRequestApproval
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.StepOrder,
		&i.RequiredLevel,
		&i.ApproverID,
		&i.Decision,
		&i.Note,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at FROM approval.requests WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OfficeID,
		&i.Amount,
		&i.CurrentStep,
		&i.TargetEntity,
		&i.TargetID,
		&i.Payload,
		&i.Reason,
		&i.Status,
		&i.RequestedByID,
		&i.DecidedByID,
		&i.DecisionNote,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInboxCandidates = `-- name: ListInboxCandidates :many
SELECT id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at FROM approval.requests
WHERE deleted_at IS NULL AND status='pending'
ORDER BY created_at ASC
`

func (q *Queries) ListInboxCandidates(ctx context.Context) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listInboxCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OfficeID,
			&i.Amount,
			&i.CurrentStep,
			&i.TargetEntity,
			&i.TargetID,
			&i.Payload,
			&i.Reason,
			&i.Status,
			&i.RequestedByID,
			&i.DecidedByID,
			&i.DecisionNote,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestApprovals = `-- name: ListRequestApprovals :many
SELECT id, request_id, step_order, required_level, approver_id, decision, note, decided_at, created_at, updated_at, deleted_at FROM approval.request_approvals
WHERE request_id=$1 AND deleted_at IS NULL ORDER BY step_order
`

func (q *Queries) ListRequestApprovals(ctx context.Context, requestID uuid.UUID) ([]ApprovalRequestApproval, error) {
	rows, err := q.db.Query(ctx, listRequestApprovals, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequestApproval{}
	for rows.Next() {
		var i ApprovalRequestApproval
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.StepOrder,
			&i.RequiredLevel,
			&i.ApproverID,
			&i.Decision,
			&i.Note,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at FROM approval.requests
WHERE deleted_at IS NULL
  AND ($1::boolean OR office_id = ANY($2::uuid[]))
  AND ($3::shared.request_status IS NULL OR status = $3)
  AND ($4::shared.request_type IS NULL OR type = $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListRequestsParams struct {
	AllScope  bool                 `json:"all_scope"`
	OfficeIds []uuid.UUID          `json:"office_ids"`
	Status    *SharedRequestStatus `json:"status"`
	Type      *SharedRequestType   `json:"type"`
	Off       int32                `json:"off"`
	Lim       int32                `json:"lim"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.AllScope,
		arg.OfficeIds,
		arg.Status,
		arg.Type,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OfficeID,
			&i.Amount,
			&i.CurrentStep,
			&i.TargetEntity,
			&i.TargetID,
			&i.Payload,
			&i.Reason,
			&i.Status,
			&i.RequestedByID,
			&i.DecidedByID,
			&i.DecisionNote,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThresholds = `-- name: ListThresholds :many
SELECT id, request_type, amount_from, amount_to, required_level, step_order, is_active, created_at, updated_at, deleted_at FROM approval.approval_thresholds WHERE deleted_at IS NULL
ORDER BY request_type, amount_from, step_order
`

func (q *Queries) ListThresholds(ctx context.Context) ([]ApprovalApprovalThreshold, error) {
	rows, err := q.db.Query(ctx, listThresholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalApprovalThreshold{}
	for rows.Next() {
		var i ApprovalApprovalThreshold
		if err := rows.Scan(
			&i.ID,
			&i.RequestType,
			&i.AmountFrom,
			&i.AmountTo,
			&i.RequiredLevel,
			&i.StepOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchThresholdSteps = `-- name: MatchThresholdSteps :many

SELECT id, request_type, amount_from, amount_to, required_level, step_order, is_active, created_at, updated_at, deleted_at FROM approval.approval_thresholds
WHERE request_type = $1 AND is_active AND deleted_at IS NULL
  AND amount_from <= $2
  AND (amount_to IS NULL OR $2 < amount_to)
ORDER BY step_order
`

type MatchThresholdStepsParams struct {
	RequestType SharedRequestType `json:"request_type"`
	Amount      string            `json:"amount"`
}

// Approval / maker-checker queries (approval schema).
// See docs/DATABASE.md §4.5 and PRD §3.6 for schema context.
func (q *Queries) MatchThresholdSteps(ctx context.Context, arg MatchThresholdStepsParams) ([]ApprovalApprovalThreshold, error) {
	rows, err := q.db.Query(ctx, matchThresholdSteps, arg.RequestType, arg.Amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalApprovalThreshold{}
	for rows.Next() {
		var i ApprovalApprovalThreshold
		if err := rows.Scan(
			&i.ID,
			&i.RequestType,
			&i.AmountFrom,
			&i.AmountTo,
			&i.RequiredLevel,
			&i.StepOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestDecision = `-- name: SetRequestDecision :one
UPDATE approval.requests SET status=$2, decided_by_id=$3, decision_note=$4, decided_at=now()
WHERE id=$1 AND deleted_at IS NULL RETURNING id, type, office_id, amount, current_step, target_entity, target_id, payload, reason, status, requested_by_id, decided_by_id, decision_note, decided_at, created_at, updated_at, deleted_at
`

type SetRequestDecisionParams struct {
	ID           uuid.UUID           `json:"id"`
	Status       SharedRequestStatus `json:"status"`
	DecidedByID  *uuid.UUID          `json:"decided_by_id"`
	DecisionNote *string             `json:"decision_note"`
}

func (q *Queries) SetRequestDecision(ctx context.Context, arg SetRequestDecisionParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, setRequestDecision,
		arg.ID,
		arg.Status,
		arg.DecidedByID,
		arg.DecisionNote,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OfficeID,
		&i.Amount,
		&i.CurrentStep,
		&i.TargetEntity,
		&i.TargetID,
		&i.Payload,
		&i.Reason,
		&i.Status,
		&i.RequestedByID,
		&i.DecidedByID,
		&i.DecisionNote,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteThreshold = `-- name: SoftDeleteThreshold :execrows
UPDATE approval.approval_thresholds SET deleted_at=now() WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteThreshold(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteThreshold, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateThreshold = `-- name: UpdateThreshold :one
UPDATE approval.approval_thresholds SET
  amount_from=$2, amount_to=$3, required_level=$4, step_order=$5, is_active=$6
WHERE id=$1 AND deleted_at IS NULL RETURNING id, request_type, amount_from, amount_to, required_level, step_order, is_active, created_at, updated_at, deleted_at
`

type UpdateThresholdParams struct {
	ID            uuid.UUID           `json:"id"`
	AmountFrom    string              `json:"amount_from"`
	AmountTo      *string             `json:"amount_to"`
	RequiredLevel SharedApproverLevel `json:"required_level"`
	StepOrder     int32               `json:"step_order"`
	IsActive      bool                `json:"is_active"`
}

func (q *Queries) UpdateThreshold(ctx context.Context, arg UpdateThresholdParams) (ApprovalApprovalThreshold, error) {
	row := q.db.QueryRow(ctx, updateThreshold,
		arg.ID,
		arg.AmountFrom,
		arg.AmountTo,
		arg.RequiredLevel,
		arg.StepOrder,
		arg.IsActive,
	)
	var i ApprovalApprovalThreshold
	err := row.Scan(
		&i.ID,
		&i.RequestType,
		&i.AmountFrom,
		&i.AmountTo,
		&i.RequiredLevel,
		&i.StepOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
