// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeActivePIC = `-- name: CloseActivePIC :exec
UPDATE asset.asset_pic_history SET released_at = now()
WHERE asset_id = $1 AND released_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) CloseActivePIC(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeActivePIC, assetID)
	return err
}

const insertAssetLocationHistory = `-- name: InsertAssetLocationHistory :exec

INSERT INTO asset.asset_location_history (
  asset_id, office_id, floor_id, room_id, source, moved_by_id, transfer_id, note
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
`

type InsertAssetLocationHistoryParams struct {
	AssetID    uuid.UUID                  `json:"asset_id"`
	OfficeID   uuid.UUID                  `json:"office_id"`
	FloorID    *uuid.UUID                 `json:"floor_id"`
	RoomID     *uuid.UUID                 `json:"room_id"`
	Source     SharedLocationChangeSource `json:"source"`
	MovedByID  *uuid.UUID                 `json:"moved_by_id"`
	TransferID *uuid.UUID                 `json:"transfer_id"`
	Note       *string                    `json:"note"`
}

// Asset location + PIC history (spec 2026-07-23 legacy-parity, Fase 3).
func (q *Queries) InsertAssetLocationHistory(ctx context.Context, arg InsertAssetLocationHistoryParams) error {
	_, err := q.db.Exec(ctx, insertAssetLocationHistory,
		arg.AssetID,
		arg.OfficeID,
		arg.FloorID,
		arg.RoomID,
		arg.Source,
		arg.MovedByID,
		arg.TransferID,
		arg.Note,
	)
	return err
}

const insertAssetPICHistory = `-- name: InsertAssetPICHistory :exec
INSERT INTO asset.asset_pic_history (asset_id, pic_employee_id, assigned_by_id, note)
VALUES ($1, $2, $3, $4)
`

type InsertAssetPICHistoryParams struct {
	AssetID       uuid.UUID  `json:"asset_id"`
	PicEmployeeID uuid.UUID  `json:"pic_employee_id"`
	AssignedByID  *uuid.UUID `json:"assigned_by_id"`
	Note          *string    `json:"note"`
}

func (q *Queries) InsertAssetPICHistory(ctx context.Context, arg InsertAssetPICHistoryParams) error {
	_, err := q.db.Exec(ctx, insertAssetPICHistory,
		arg.AssetID,
		arg.PicEmployeeID,
		arg.AssignedByID,
		arg.Note,
	)
	return err
}

const listAssetLocationHistory = `-- name: ListAssetLocationHistory :many
SELECT h.id, h.asset_id, h.office_id, h.floor_id, h.room_id, h.source, h.moved_at,
       h.moved_by_id, h.transfer_id, h.note,
       o.name AS office_name, f.name AS floor_name, r.name AS room_name, u.name AS moved_by_name
FROM asset.asset_location_history h
JOIN masterdata.offices o ON o.id = h.office_id
LEFT JOIN masterdata.floors f ON f.id = h.floor_id
LEFT JOIN masterdata.rooms r ON r.id = h.room_id
LEFT JOIN identity.users u ON u.id = h.moved_by_id
WHERE h.asset_id = $1 AND h.deleted_at IS NULL
ORDER BY h.moved_at DESC, h.created_at DESC
`

type ListAssetLocationHistoryRow struct {
	ID          uuid.UUID                  `json:"id"`
	AssetID     uuid.UUID                  `json:"asset_id"`
	OfficeID    uuid.UUID                  `json:"office_id"`
	FloorID     *uuid.UUID                 `json:"floor_id"`
	RoomID      *uuid.UUID                 `json:"room_id"`
	Source      SharedLocationChangeSource `json:"source"`
	MovedAt     pgtype.Timestamptz         `json:"moved_at"`
	MovedByID   *uuid.UUID                 `json:"moved_by_id"`
	TransferID  *uuid.UUID                 `json:"transfer_id"`
	Note        *string                    `json:"note"`
	OfficeName  string                     `json:"office_name"`
	FloorName   *string                    `json:"floor_name"`
	RoomName    *string                    `json:"room_name"`
	MovedByName *string                    `json:"moved_by_name"`
}

func (q *Queries) ListAssetLocationHistory(ctx context.Context, assetID uuid.UUID) ([]ListAssetLocationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAssetLocationHistory, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetLocationHistoryRow{}
	for rows.Next() {
		var i ListAssetLocationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.OfficeID,
			&i.FloorID,
			&i.RoomID,
			&i.Source,
			&i.MovedAt,
			&i.MovedByID,
			&i.TransferID,
			&i.Note,
			&i.OfficeName,
			&i.FloorName,
			&i.RoomName,
			&i.MovedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetPICHistory = `-- name: ListAssetPICHistory :many
SELECT h.id, h.asset_id, h.pic_employee_id, h.assigned_at, h.released_at,
       h.assigned_by_id, h.note,
       e.name AS pic_name, e.code AS pic_code, u.name AS assigned_by_name
FROM asset.asset_pic_history h
JOIN masterdata.employees e ON e.id = h.pic_employee_id
LEFT JOIN identity.users u ON u.id = h.assigned_by_id
WHERE h.asset_id = $1 AND h.deleted_at IS NULL
ORDER BY h.assigned_at DESC, h.created_at DESC
`

type ListAssetPICHistoryRow struct {
	ID             uuid.UUID          `json:"id"`
	AssetID        uuid.UUID          `json:"asset_id"`
	PicEmployeeID  uuid.UUID          `json:"pic_employee_id"`
	AssignedAt     pgtype.Timestamptz `json:"assigned_at"`
	ReleasedAt     pgtype.Timestamptz `json:"released_at"`
	AssignedByID   *uuid.UUID         `json:"assigned_by_id"`
	Note           *string            `json:"note"`
	PicName        string             `json:"pic_name"`
	PicCode        string             `json:"pic_code"`
	AssignedByName *string            `json:"assigned_by_name"`
}

func (q *Queries) ListAssetPICHistory(ctx context.Context, assetID uuid.UUID) ([]ListAssetPICHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAssetPICHistory, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetPICHistoryRow{}
	for rows.Next() {
		var i ListAssetPICHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.PicEmployeeID,
			&i.AssignedAt,
			&i.ReleasedAt,
			&i.AssignedByID,
			&i.Note,
			&i.PicName,
			&i.PicCode,
			&i.AssignedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
