// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkinAssignment = `-- name: CheckinAssignment :one
UPDATE assignment.assignments
SET status = 'returned', checkin_date = $1, condition_in = $2
WHERE id = $3 AND status = 'active' AND deleted_at IS NULL
RETURNING id, asset_id, employee_id, assigned_by_id, checkout_date, due_date, checkin_date, condition_out, condition_in, status, notes, created_at, updated_at, deleted_at
`

type CheckinAssignmentParams struct {
	CheckinDate pgtype.Timestamptz `json:"checkin_date"`
	ConditionIn *string            `json:"condition_in"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) CheckinAssignment(ctx context.Context, arg CheckinAssignmentParams) (AssignmentAssignment, error) {
	row := q.db.QueryRow(ctx, checkinAssignment, arg.CheckinDate, arg.ConditionIn, arg.ID)
	var i AssignmentAssignment
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EmployeeID,
		&i.AssignedByID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.CheckinDate,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const checkoutAssignment = `-- name: CheckoutAssignment :one
INSERT INTO assignment.assignments (
  asset_id, employee_id, assigned_by_id, checkout_date, due_date, condition_out, notes, status
) VALUES (
  $1, $2, $3,
  $4, $5, $6, $7, 'active'
)
RETURNING id, asset_id, employee_id, assigned_by_id, checkout_date, due_date, checkin_date, condition_out, condition_in, status, notes, created_at, updated_at, deleted_at
`

type CheckoutAssignmentParams struct {
	AssetID      uuid.UUID          `json:"asset_id"`
	EmployeeID   uuid.UUID          `json:"employee_id"`
	AssignedByID uuid.UUID          `json:"assigned_by_id"`
	CheckoutDate pgtype.Timestamptz `json:"checkout_date"`
	DueDate      pgtype.Date        `json:"due_date"`
	ConditionOut *string            `json:"condition_out"`
	Notes        *string            `json:"notes"`
}

func (q *Queries) CheckoutAssignment(ctx context.Context, arg CheckoutAssignmentParams) (AssignmentAssignment, error) {
	row := q.db.QueryRow(ctx, checkoutAssignment,
		arg.AssetID,
		arg.EmployeeID,
		arg.AssignedByID,
		arg.CheckoutDate,
		arg.DueDate,
		arg.ConditionOut,
		arg.Notes,
	)
	var i AssignmentAssignment
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EmployeeID,
		&i.AssignedByID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.CheckinDate,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countAssignments = `-- name: CountAssignments :one
SELECT count(*)
FROM assignment.assignments asg
JOIN asset.assets a              ON a.id = asg.asset_id    AND a.deleted_at IS NULL
LEFT JOIN masterdata.employees e ON e.id = asg.employee_id AND e.deleted_at IS NULL
WHERE asg.deleted_at IS NULL
  AND ($1::boolean OR a.office_id = ANY($2::uuid[]))
  AND ($3::shared.assignment_status IS NULL OR asg.status = $3)
  AND ($4::uuid IS NULL OR asg.employee_id = $4)
  AND ($5::text IS NULL OR a.name ILIKE '%' || $5 || '%'
       OR a.asset_tag ILIKE '%' || $5 || '%'
       OR e.name ILIKE '%' || $5 || '%')
`

type CountAssignmentsParams struct {
	AllScope   bool                    `json:"all_scope"`
	OfficeIds  []uuid.UUID             `json:"office_ids"`
	Status     *SharedAssignmentStatus `json:"status"`
	EmployeeID *uuid.UUID              `json:"employee_id"`
	Search     *string                 `json:"search"`
}

func (q *Queries) CountAssignments(ctx context.Context, arg CountAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignments,
		arg.AllScope,
		arg.OfficeIds,
		arg.Status,
		arg.EmployeeID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveAssignmentByAsset = `-- name: GetActiveAssignmentByAsset :one
SELECT id, asset_id, employee_id, assigned_by_id, checkout_date, due_date, checkin_date, condition_out, condition_in, status, notes, created_at, updated_at, deleted_at FROM assignment.assignments
WHERE asset_id = $1 AND status = 'active' AND deleted_at IS NULL
`

// Used by the maintenance module (cross-schema rule): when releasing an asset
// from under_maintenance, we must know whether an employee still holds it via
// an active assignment, so it is restored to 'assigned' rather than 'available'.
func (q *Queries) GetActiveAssignmentByAsset(ctx context.Context, assetID uuid.UUID) (AssignmentAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveAssignmentByAsset, assetID)
	var i AssignmentAssignment
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EmployeeID,
		&i.AssignedByID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.CheckinDate,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssignmentEnriched = `-- name: GetAssignmentEnriched :one
SELECT asg.id, asg.asset_id, asg.employee_id, asg.assigned_by_id, asg.checkout_date, asg.due_date, asg.checkin_date, asg.condition_out, asg.condition_in, asg.status, asg.notes, asg.created_at, asg.updated_at, asg.deleted_at,
       a.name      AS asset_name,
       a.asset_tag AS asset_tag,
       a.office_id AS office_id,
       e.name      AS employee_name,
       u.name      AS assigned_by_name,
       o.name      AS office_name
FROM assignment.assignments asg
JOIN asset.assets a              ON a.id = asg.asset_id       AND a.deleted_at IS NULL
LEFT JOIN masterdata.employees e ON e.id = asg.employee_id    AND e.deleted_at IS NULL
LEFT JOIN identity.users u       ON u.id = asg.assigned_by_id AND u.deleted_at IS NULL
LEFT JOIN masterdata.offices o   ON o.id = a.office_id        AND o.deleted_at IS NULL
WHERE asg.id = $1 AND asg.deleted_at IS NULL
  AND ($2::boolean OR a.office_id = ANY($3::uuid[]))
`

type GetAssignmentEnrichedParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

type GetAssignmentEnrichedRow struct {
	AssignmentAssignment AssignmentAssignment `json:"assignment_assignment"`
	AssetName            string               `json:"asset_name"`
	AssetTag             string               `json:"asset_tag"`
	OfficeID             uuid.UUID            `json:"office_id"`
	EmployeeName         *string              `json:"employee_name"`
	AssignedByName       *string              `json:"assigned_by_name"`
	OfficeName           *string              `json:"office_name"`
}

func (q *Queries) GetAssignmentEnriched(ctx context.Context, arg GetAssignmentEnrichedParams) (GetAssignmentEnrichedRow, error) {
	row := q.db.QueryRow(ctx, getAssignmentEnriched, arg.ID, arg.AllScope, arg.OfficeIds)
	var i GetAssignmentEnrichedRow
	err := row.Scan(
		&i.AssignmentAssignment.ID,
		&i.AssignmentAssignment.AssetID,
		&i.AssignmentAssignment.EmployeeID,
		&i.AssignmentAssignment.AssignedByID,
		&i.AssignmentAssignment.CheckoutDate,
		&i.AssignmentAssignment.DueDate,
		&i.AssignmentAssignment.CheckinDate,
		&i.AssignmentAssignment.ConditionOut,
		&i.AssignmentAssignment.ConditionIn,
		&i.AssignmentAssignment.Status,
		&i.AssignmentAssignment.Notes,
		&i.AssignmentAssignment.CreatedAt,
		&i.AssignmentAssignment.UpdatedAt,
		&i.AssignmentAssignment.DeletedAt,
		&i.AssetName,
		&i.AssetTag,
		&i.OfficeID,
		&i.EmployeeName,
		&i.AssignedByName,
		&i.OfficeName,
	)
	return i, err
}

const getAssignmentScoped = `-- name: GetAssignmentScoped :one
SELECT asg.id, asg.asset_id, asg.employee_id, asg.assigned_by_id, asg.checkout_date, asg.due_date, asg.checkin_date, asg.condition_out, asg.condition_in, asg.status, asg.notes, asg.created_at, asg.updated_at, asg.deleted_at FROM assignment.assignments asg
JOIN asset.assets a ON a.id = asg.asset_id AND a.deleted_at IS NULL
WHERE asg.id = $1 AND asg.deleted_at IS NULL
  AND ($2::boolean OR a.office_id = ANY($3::uuid[]))
`

type GetAssignmentScopedParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

// Plain (unenriched) row, scoped by the asset's office. Used by Checkin to load +
// validate state before the update.
func (q *Queries) GetAssignmentScoped(ctx context.Context, arg GetAssignmentScopedParams) (AssignmentAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentScoped, arg.ID, arg.AllScope, arg.OfficeIds)
	var i AssignmentAssignment
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EmployeeID,
		&i.AssignedByID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.CheckinDate,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssignmentsByAssetEnriched = `-- name: ListAssignmentsByAssetEnriched :many
SELECT asg.id, asg.asset_id, asg.employee_id, asg.assigned_by_id, asg.checkout_date, asg.due_date, asg.checkin_date, asg.condition_out, asg.condition_in, asg.status, asg.notes, asg.created_at, asg.updated_at, asg.deleted_at,
       a.name      AS asset_name,
       a.asset_tag AS asset_tag,
       a.office_id AS office_id,
       e.name      AS employee_name,
       u.name      AS assigned_by_name,
       o.name      AS office_name
FROM assignment.assignments asg
JOIN asset.assets a              ON a.id = asg.asset_id       AND a.deleted_at IS NULL
LEFT JOIN masterdata.employees e ON e.id = asg.employee_id    AND e.deleted_at IS NULL
LEFT JOIN identity.users u       ON u.id = asg.assigned_by_id AND u.deleted_at IS NULL
LEFT JOIN masterdata.offices o   ON o.id = a.office_id        AND o.deleted_at IS NULL
WHERE asg.asset_id = $1 AND asg.deleted_at IS NULL
  AND ($2::boolean OR a.office_id = ANY($3::uuid[]))
ORDER BY asg.checkout_date DESC
`

type ListAssignmentsByAssetEnrichedParams struct {
	AssetID   uuid.UUID   `json:"asset_id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

type ListAssignmentsByAssetEnrichedRow struct {
	AssignmentAssignment AssignmentAssignment `json:"assignment_assignment"`
	AssetName            string               `json:"asset_name"`
	AssetTag             string               `json:"asset_tag"`
	OfficeID             uuid.UUID            `json:"office_id"`
	EmployeeName         *string              `json:"employee_name"`
	AssignedByName       *string              `json:"assigned_by_name"`
	OfficeName           *string              `json:"office_name"`
}

func (q *Queries) ListAssignmentsByAssetEnriched(ctx context.Context, arg ListAssignmentsByAssetEnrichedParams) ([]ListAssignmentsByAssetEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByAssetEnriched, arg.AssetID, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsByAssetEnrichedRow{}
	for rows.Next() {
		var i ListAssignmentsByAssetEnrichedRow
		if err := rows.Scan(
			&i.AssignmentAssignment.ID,
			&i.AssignmentAssignment.AssetID,
			&i.AssignmentAssignment.EmployeeID,
			&i.AssignmentAssignment.AssignedByID,
			&i.AssignmentAssignment.CheckoutDate,
			&i.AssignmentAssignment.DueDate,
			&i.AssignmentAssignment.CheckinDate,
			&i.AssignmentAssignment.ConditionOut,
			&i.AssignmentAssignment.ConditionIn,
			&i.AssignmentAssignment.Status,
			&i.AssignmentAssignment.Notes,
			&i.AssignmentAssignment.CreatedAt,
			&i.AssignmentAssignment.UpdatedAt,
			&i.AssignmentAssignment.DeletedAt,
			&i.AssetName,
			&i.AssetTag,
			&i.OfficeID,
			&i.EmployeeName,
			&i.AssignedByName,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsEnriched = `-- name: ListAssignmentsEnriched :many
SELECT asg.id, asg.asset_id, asg.employee_id, asg.assigned_by_id, asg.checkout_date, asg.due_date, asg.checkin_date, asg.condition_out, asg.condition_in, asg.status, asg.notes, asg.created_at, asg.updated_at, asg.deleted_at,
       a.name      AS asset_name,
       a.asset_tag AS asset_tag,
       a.office_id AS office_id,
       e.name      AS employee_name,
       u.name      AS assigned_by_name,
       o.name      AS office_name
FROM assignment.assignments asg
JOIN asset.assets a              ON a.id = asg.asset_id       AND a.deleted_at IS NULL
LEFT JOIN masterdata.employees e ON e.id = asg.employee_id    AND e.deleted_at IS NULL
LEFT JOIN identity.users u       ON u.id = asg.assigned_by_id AND u.deleted_at IS NULL
LEFT JOIN masterdata.offices o   ON o.id = a.office_id        AND o.deleted_at IS NULL
WHERE asg.deleted_at IS NULL
  AND ($1::boolean OR a.office_id = ANY($2::uuid[]))
  AND ($3::shared.assignment_status IS NULL OR asg.status = $3)
  AND ($4::uuid IS NULL OR asg.employee_id = $4)
  AND ($5::text IS NULL OR a.name ILIKE '%' || $5 || '%'
       OR a.asset_tag ILIKE '%' || $5 || '%'
       OR e.name ILIKE '%' || $5 || '%')
ORDER BY asg.checkout_date DESC
LIMIT $7 OFFSET $6
`

type ListAssignmentsEnrichedParams struct {
	AllScope   bool                    `json:"all_scope"`
	OfficeIds  []uuid.UUID             `json:"office_ids"`
	Status     *SharedAssignmentStatus `json:"status"`
	EmployeeID *uuid.UUID              `json:"employee_id"`
	Search     *string                 `json:"search"`
	Off        int32                   `json:"off"`
	Lim        int32                   `json:"lim"`
}

type ListAssignmentsEnrichedRow struct {
	AssignmentAssignment AssignmentAssignment `json:"assignment_assignment"`
	AssetName            string               `json:"asset_name"`
	AssetTag             string               `json:"asset_tag"`
	OfficeID             uuid.UUID            `json:"office_id"`
	EmployeeName         *string              `json:"employee_name"`
	AssignedByName       *string              `json:"assigned_by_name"`
	OfficeName           *string              `json:"office_name"`
}

func (q *Queries) ListAssignmentsEnriched(ctx context.Context, arg ListAssignmentsEnrichedParams) ([]ListAssignmentsEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsEnriched,
		arg.AllScope,
		arg.OfficeIds,
		arg.Status,
		arg.EmployeeID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsEnrichedRow{}
	for rows.Next() {
		var i ListAssignmentsEnrichedRow
		if err := rows.Scan(
			&i.AssignmentAssignment.ID,
			&i.AssignmentAssignment.AssetID,
			&i.AssignmentAssignment.EmployeeID,
			&i.AssignmentAssignment.AssignedByID,
			&i.AssignmentAssignment.CheckoutDate,
			&i.AssignmentAssignment.DueDate,
			&i.AssignmentAssignment.CheckinDate,
			&i.AssignmentAssignment.ConditionOut,
			&i.AssignmentAssignment.ConditionIn,
			&i.AssignmentAssignment.Status,
			&i.AssignmentAssignment.Notes,
			&i.AssignmentAssignment.CreatedAt,
			&i.AssignmentAssignment.UpdatedAt,
			&i.AssignmentAssignment.DeletedAt,
			&i.AssetName,
			&i.AssetTag,
			&i.OfficeID,
			&i.EmployeeName,
			&i.AssignedByName,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
