// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOfficeSubtree = `-- name: GetOfficeSubtree :many

WITH RECURSIVE subtree AS (
  SELECT o.id FROM masterdata.offices o WHERE o.id = $1 AND o.deleted_at IS NULL
  UNION ALL
  SELECT o.id
  FROM masterdata.offices o
  JOIN subtree s ON o.parent_id = s.id
  WHERE o.deleted_at IS NULL
)
SELECT id FROM subtree
`

// Authorization queries: office subtree (scoping) and field permissions.
// Returns an office plus all of its descendants (Pusat -> Wilayah -> Cabang -> Outlet).
func (q *Queries) GetOfficeSubtree(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOfficeSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldPermissionsByRole = `-- name: ListFieldPermissionsByRole :many
SELECT entity, field, can_view, can_edit
FROM identity.field_permissions
WHERE role_id = $1 AND deleted_at IS NULL
`

type ListFieldPermissionsByRoleRow struct {
	Entity  string `json:"entity"`
	Field   string `json:"field"`
	CanView bool   `json:"can_view"`
	CanEdit bool   `json:"can_edit"`
}

func (q *Queries) ListFieldPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]ListFieldPermissionsByRoleRow, error) {
	rows, err := q.db.Query(ctx, listFieldPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFieldPermissionsByRoleRow{}
	for rows.Next() {
		var i ListFieldPermissionsByRoleRow
		if err := rows.Scan(
			&i.Entity,
			&i.Field,
			&i.CanView,
			&i.CanEdit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
