// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOfficeSubtree = `-- name: GetOfficeSubtree :many

WITH RECURSIVE subtree AS (
  SELECT o.id FROM masterdata.offices o WHERE o.id = $1 AND o.deleted_at IS NULL
  UNION ALL
  SELECT o.id
  FROM masterdata.offices o
  JOIN subtree s ON o.parent_id = s.id
  WHERE o.deleted_at IS NULL
)
SELECT id FROM subtree
`

// Authorization queries: office subtree (scoping) and field permissions.
// Returns an office plus all of its descendants (Pusat -> Wilayah -> Cabang -> Outlet).
func (q *Queries) GetOfficeSubtree(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOfficeSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldPermissionsByRole = `-- name: ListFieldPermissionsByRole :many
SELECT entity, field, can_view, can_edit
FROM identity.field_permissions
WHERE role_id = $1 AND deleted_at IS NULL
`

type ListFieldPermissionsByRoleRow struct {
	Entity  string `json:"entity"`
	Field   string `json:"field"`
	CanView bool   `json:"can_view"`
	CanEdit bool   `json:"can_edit"`
}

func (q *Queries) ListFieldPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]ListFieldPermissionsByRoleRow, error) {
	rows, err := q.db.Query(ctx, listFieldPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFieldPermissionsByRoleRow{}
	for rows.Next() {
		var i ListFieldPermissionsByRoleRow
		if err := rows.Scan(
			&i.Entity,
			&i.Field,
			&i.CanView,
			&i.CanEdit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithPermission = `-- name: ListUsersWithPermission :many
SELECT u.id, u.role_id, u.office_id
FROM identity.users u
JOIN identity.role_permissions rp
  ON rp.role_id = u.role_id AND rp.deleted_at IS NULL
WHERE rp.permission_key = $1
  AND u.status = 'active'
  AND u.deleted_at IS NULL
`

type ListUsersWithPermissionRow struct {
	ID       uuid.UUID  `json:"id"`
	RoleID   uuid.UUID  `json:"role_id"`
	OfficeID *uuid.UUID `json:"office_id"`
}

// The inverse of the request-time permission check: given a permission key, who
// holds it? Needed to fan notifications out to concrete users, because every
// other authorization path here answers only "may THIS caller act?".
// Callers must still apply scope and SoD by running the existing eligibility
// predicate over each candidate -- deliberately not reimplemented in SQL, or the
// rules would drift from approval.eligibleToDecide.
func (q *Queries) ListUsersWithPermission(ctx context.Context, permissionKey string) ([]ListUsersWithPermissionRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithPermission, permissionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithPermissionRow{}
	for rows.Next() {
		var i ListUsersWithPermissionRow
		if err := rows.Scan(&i.ID, &i.RoleID, &i.OfficeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
