// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM masterdata.categories
WHERE deleted_at IS NULL
  AND (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR coalesce(code, '') ILIKE '%' || $1 || '%'
  )
`

func (q *Queries) CountCategories(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO masterdata.categories (
  name, code, parent_id, default_depreciation_method,
  default_useful_life_months, default_salvage_rate, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, code, parent_id, default_depreciation_method, default_useful_life_months, default_salvage_rate, is_active, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	Name                      string                    `json:"name"`
	Code                      *string                   `json:"code"`
	ParentID                  *uuid.UUID                `json:"parent_id"`
	DefaultDepreciationMethod *SharedDepreciationMethod `json:"default_depreciation_method"`
	DefaultUsefulLifeMonths   *int32                    `json:"default_useful_life_months"`
	DefaultSalvageRate        *string                   `json:"default_salvage_rate"`
	IsActive                  bool                      `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (MasterdataCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.DefaultDepreciationMethod,
		arg.DefaultUsefulLifeMonths,
		arg.DefaultSalvageRate,
		arg.IsActive,
	)
	var i MasterdataCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.DefaultDepreciationMethod,
		&i.DefaultUsefulLifeMonths,
		&i.DefaultSalvageRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, code, parent_id, default_depreciation_method, default_useful_life_months, default_salvage_rate, is_active, created_at, updated_at, deleted_at FROM masterdata.categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (MasterdataCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i MasterdataCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.DefaultDepreciationMethod,
		&i.DefaultUsefulLifeMonths,
		&i.DefaultSalvageRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

SELECT id, name, code, parent_id, default_depreciation_method, default_useful_life_months, default_salvage_rate, is_active, created_at, updated_at, deleted_at FROM masterdata.categories
WHERE deleted_at IS NULL
  AND (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR coalesce(code, '') ILIKE '%' || $1 || '%'
  )
ORDER BY name
LIMIT $3 OFFSET $2
`

type ListCategoriesParams struct {
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// Asset category master data (masterdata.categories). Respects soft delete.
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]MasterdataCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterdataCategory{}
	for rows.Next() {
		var i MasterdataCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.DefaultDepreciationMethod,
			&i.DefaultUsefulLifeMonths,
			&i.DefaultSalvageRate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :execrows
UPDATE masterdata.categories
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE masterdata.categories
SET name = $2,
    code = $3,
    parent_id = $4,
    default_depreciation_method = $5,
    default_useful_life_months = $6,
    default_salvage_rate = $7,
    is_active = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, code, parent_id, default_depreciation_method, default_useful_life_months, default_salvage_rate, is_active, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	ID                        uuid.UUID                 `json:"id"`
	Name                      string                    `json:"name"`
	Code                      *string                   `json:"code"`
	ParentID                  *uuid.UUID                `json:"parent_id"`
	DefaultDepreciationMethod *SharedDepreciationMethod `json:"default_depreciation_method"`
	DefaultUsefulLifeMonths   *int32                    `json:"default_useful_life_months"`
	DefaultSalvageRate        *string                   `json:"default_salvage_rate"`
	IsActive                  bool                      `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MasterdataCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.DefaultDepreciationMethod,
		arg.DefaultUsefulLifeMonths,
		arg.DefaultSalvageRate,
		arg.IsActive,
	)
	var i MasterdataCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.DefaultDepreciationMethod,
		&i.DefaultUsefulLifeMonths,
		&i.DefaultSalvageRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
