// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countDepartments = `-- name: CountDepartments :one
SELECT count(*) FROM masterdata.departments
WHERE deleted_at IS NULL
  AND ($1::bool
       OR office_id = ANY($2::uuid[])
       OR office_id IS NULL)
  AND (
    $3::text = ''
    OR name ILIKE '%' || $3 || '%'
    OR code ILIKE '%' || $3 || '%'
  )
`

type CountDepartmentsParams struct {
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
	Search    string      `json:"search"`
}

func (q *Queries) CountDepartments(ctx context.Context, arg CountDepartmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments, arg.AllScope, arg.OfficeIds, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO masterdata.departments (name, code, office_id, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, code, is_active, created_at, updated_at, deleted_at, office_id
`

type CreateDepartmentParams struct {
	Name     string     `json:"name"`
	Code     *string    `json:"code"`
	OfficeID *uuid.UUID `json:"office_id"`
	IsActive bool       `json:"is_active"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (MasterdataDepartment, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.Name,
		arg.Code,
		arg.OfficeID,
		arg.IsActive,
	)
	var i MasterdataDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, code, is_active, created_at, updated_at, deleted_at, office_id FROM masterdata.departments
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::bool
       OR office_id = ANY($3::uuid[])
       OR office_id IS NULL)
`

type GetDepartmentParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

// Read visibility includes NULL-office (global) departments.
func (q *Queries) GetDepartment(ctx context.Context, arg GetDepartmentParams) (MasterdataDepartment, error) {
	row := q.db.QueryRow(ctx, getDepartment, arg.ID, arg.AllScope, arg.OfficeIds)
	var i MasterdataDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many

SELECT id, name, code, is_active, created_at, updated_at, deleted_at, office_id FROM masterdata.departments
WHERE deleted_at IS NULL
  AND ($1::bool
       OR office_id = ANY($2::uuid[])
       OR office_id IS NULL)
  AND (
    $3::text = ''
    OR name ILIKE '%' || $3 || '%'
    OR code ILIKE '%' || $3 || '%'
  )
ORDER BY name
LIMIT $5 OFFSET $4
`

type ListDepartmentsParams struct {
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
	Search    string      `json:"search"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

// Departments are office-scoped master data (legacy-parity Fase 6 made them
// per-office). Reads/writes are filtered by the caller's office data scope; legacy
// departments with a NULL office_id are shared reference data visible to everyone
// but mutable only by a global-scope caller (enforced in the service layer).
func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]MasterdataDepartment, error) {
	rows, err := q.db.Query(ctx, listDepartments,
		arg.AllScope,
		arg.OfficeIds,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterdataDepartment{}
	for rows.Next() {
		var i MasterdataDepartment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDepartment = `-- name: SoftDeleteDepartment :execrows
UPDATE masterdata.departments SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::bool OR office_id = ANY($3::uuid[]))
`

type SoftDeleteDepartmentParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) SoftDeleteDepartment(ctx context.Context, arg SoftDeleteDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDepartment, arg.ID, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE masterdata.departments
SET name = $1,
    code = $2,
    office_id = $3,
    is_active = $4
WHERE id = $5 AND deleted_at IS NULL
  AND ($6::bool OR office_id = ANY($7::uuid[]))
RETURNING id, name, code, is_active, created_at, updated_at, deleted_at, office_id
`

type UpdateDepartmentParams struct {
	Name      string      `json:"name"`
	Code      *string     `json:"code"`
	OfficeID  *uuid.UUID  `json:"office_id"`
	IsActive  bool        `json:"is_active"`
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

// Write scope EXCLUDES NULL-office rows: only a global-scope caller may mutate a
// shared/global department (a scoped caller can read but not edit it).
func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (MasterdataDepartment, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.Name,
		arg.Code,
		arg.OfficeID,
		arg.IsActive,
		arg.ID,
		arg.AllScope,
		arg.OfficeIds,
	)
	var i MasterdataDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
	)
	return i, err
}
