// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countEmployees = `-- name: CountEmployees :one
SELECT count(*) FROM masterdata.employees
WHERE deleted_at IS NULL
  AND ($1::bool OR office_id = ANY($2::uuid[]))
  AND (
    $3::text = ''
    OR name ILIKE '%' || $3 || '%'
    OR code ILIKE '%' || $3 || '%'
  )
`

type CountEmployeesParams struct {
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
	Search    string      `json:"search"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.AllScope, arg.OfficeIds, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO masterdata.employees (
  code, name, email, phone, avatar_key, department_id, position_id, office_id, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, name, email, avatar_key, department_id, position_id, office_id, status, created_at, updated_at, deleted_at, phone
`

type CreateEmployeeParams struct {
	Code         string           `json:"code"`
	Name         string           `json:"name"`
	Email        *string          `json:"email"`
	Phone        *string          `json:"phone"`
	AvatarKey    *string          `json:"avatar_key"`
	DepartmentID *uuid.UUID       `json:"department_id"`
	PositionID   *uuid.UUID       `json:"position_id"`
	OfficeID     uuid.UUID        `json:"office_id"`
	Status       SharedUserStatus `json:"status"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (MasterdataEmployee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.Code,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.AvatarKey,
		arg.DepartmentID,
		arg.PositionID,
		arg.OfficeID,
		arg.Status,
	)
	var i MasterdataEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.AvatarKey,
		&i.DepartmentID,
		&i.PositionID,
		&i.OfficeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Phone,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, code, name, email, avatar_key, department_id, position_id, office_id, status, created_at, updated_at, deleted_at, phone FROM masterdata.employees
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::bool OR office_id = ANY($3::uuid[]))
`

type GetEmployeeParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (MasterdataEmployee, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.ID, arg.AllScope, arg.OfficeIds)
	var i MasterdataEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.AvatarKey,
		&i.DepartmentID,
		&i.PositionID,
		&i.OfficeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Phone,
	)
	return i, err
}

const getEmployeeByCode = `-- name: GetEmployeeByCode :one
SELECT id, code, name, email, avatar_key, department_id, position_id, office_id, status, created_at, updated_at, deleted_at, phone FROM masterdata.employees WHERE code = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetEmployeeByCode(ctx context.Context, code string) (MasterdataEmployee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByCode, code)
	var i MasterdataEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.AvatarKey,
		&i.DepartmentID,
		&i.PositionID,
		&i.OfficeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Phone,
	)
	return i, err
}

const listEmployeeCodes = `-- name: ListEmployeeCodes :many
SELECT code FROM masterdata.employees WHERE deleted_at IS NULL
`

// All existing (non-deleted) employee codes, used by the employee importer to
// detect collisions with user-supplied kode values during validation. Employee
// codes are globally unique (uq_employees_code), so this set is deliberately
// unscoped.
func (q *Queries) ListEmployeeCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEmployeeCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many

SELECT id, code, name, email, avatar_key, department_id, position_id, office_id, status, created_at, updated_at, deleted_at, phone FROM masterdata.employees
WHERE deleted_at IS NULL
  AND ($1::bool OR office_id = ANY($2::uuid[]))
  AND (
    $3::text = ''
    OR name ILIKE '%' || $3 || '%'
    OR code ILIKE '%' || $3 || '%'
  )
ORDER BY name
LIMIT $5 OFFSET $4
`

type ListEmployeesParams struct {
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
	Search    string      `json:"search"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

// Employees (asset custodians) with data-scoping by office.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]MasterdataEmployee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.AllScope,
		arg.OfficeIds,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterdataEmployee{}
	for rows.Next() {
		var i MasterdataEmployee
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Email,
			&i.AvatarKey,
			&i.DepartmentID,
			&i.PositionID,
			&i.OfficeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEmployee = `-- name: SoftDeleteEmployee :execrows
UPDATE masterdata.employees SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::bool OR office_id = ANY($3::uuid[]))
`

type SoftDeleteEmployeeParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEmployee, arg.ID, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE masterdata.employees
SET code = $1,
    name = $2,
    email = $3,
    phone = $4,
    avatar_key = $5,
    department_id = $6,
    position_id = $7,
    office_id = $8,
    status = $9
WHERE id = $10 AND deleted_at IS NULL
  AND ($11::bool OR office_id = ANY($12::uuid[]))
RETURNING id, code, name, email, avatar_key, department_id, position_id, office_id, status, created_at, updated_at, deleted_at, phone
`

type UpdateEmployeeParams struct {
	Code         string           `json:"code"`
	Name         string           `json:"name"`
	Email        *string          `json:"email"`
	Phone        *string          `json:"phone"`
	AvatarKey    *string          `json:"avatar_key"`
	DepartmentID *uuid.UUID       `json:"department_id"`
	PositionID   *uuid.UUID       `json:"position_id"`
	OfficeID     uuid.UUID        `json:"office_id"`
	Status       SharedUserStatus `json:"status"`
	ID           uuid.UUID        `json:"id"`
	AllScope     bool             `json:"all_scope"`
	OfficeIds    []uuid.UUID      `json:"office_ids"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (MasterdataEmployee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.Code,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.AvatarKey,
		arg.DepartmentID,
		arg.PositionID,
		arg.OfficeID,
		arg.Status,
		arg.ID,
		arg.AllScope,
		arg.OfficeIds,
	)
	var i MasterdataEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.AvatarKey,
		&i.DepartmentID,
		&i.PositionID,
		&i.OfficeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Phone,
	)
	return i, err
}

const updateEmployeePhone = `-- name: UpdateEmployeePhone :exec
UPDATE masterdata.employees SET phone = $2 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateEmployeePhoneParams struct {
	ID    uuid.UUID `json:"id"`
	Phone *string   `json:"phone"`
}

func (q *Queries) UpdateEmployeePhone(ctx context.Context, arg UpdateEmployeePhoneParams) error {
	_, err := q.db.Exec(ctx, updateEmployeePhone, arg.ID, arg.Phone)
	return err
}
