// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: floors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countFloorsByOffice = `-- name: CountFloorsByOffice :one
SELECT count(*) FROM masterdata.floors
WHERE deleted_at IS NULL AND office_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
`

type CountFloorsByOfficeParams struct {
	OfficeID uuid.UUID `json:"office_id"`
	Search   string    `json:"search"`
}

func (q *Queries) CountFloorsByOffice(ctx context.Context, arg CountFloorsByOfficeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFloorsByOffice, arg.OfficeID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFloor = `-- name: CreateFloor :one
INSERT INTO masterdata.floors (office_id, name, level)
VALUES ($1, $2, $3)
RETURNING id, office_id, name, level, created_at, updated_at, deleted_at
`

type CreateFloorParams struct {
	OfficeID uuid.UUID `json:"office_id"`
	Name     string    `json:"name"`
	Level    *int32    `json:"level"`
}

func (q *Queries) CreateFloor(ctx context.Context, arg CreateFloorParams) (MasterdataFloor, error) {
	row := q.db.QueryRow(ctx, createFloor, arg.OfficeID, arg.Name, arg.Level)
	var i MasterdataFloor
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFloor = `-- name: GetFloor :one
SELECT id, office_id, name, level, created_at, updated_at, deleted_at FROM masterdata.floors
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::bool OR office_id = ANY($3::uuid[]))
`

type GetFloorParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) GetFloor(ctx context.Context, arg GetFloorParams) (MasterdataFloor, error) {
	row := q.db.QueryRow(ctx, getFloor, arg.ID, arg.AllScope, arg.OfficeIds)
	var i MasterdataFloor
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFloorsByOffice = `-- name: ListFloorsByOffice :many

SELECT id, office_id, name, level, created_at, updated_at, deleted_at FROM masterdata.floors
WHERE deleted_at IS NULL AND office_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
ORDER BY name
LIMIT $4 OFFSET $3
`

type ListFloorsByOfficeParams struct {
	OfficeID uuid.UUID `json:"office_id"`
	Search   string    `json:"search"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

// Floors (within an office). Listed per office; single-row ops carry the
// office scope (all_scope OR office_id = ANY(office_ids)).
func (q *Queries) ListFloorsByOffice(ctx context.Context, arg ListFloorsByOfficeParams) ([]MasterdataFloor, error) {
	rows, err := q.db.Query(ctx, listFloorsByOffice,
		arg.OfficeID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterdataFloor{}
	for rows.Next() {
		var i MasterdataFloor
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.Name,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFloor = `-- name: SoftDeleteFloor :execrows
UPDATE masterdata.floors SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::bool OR office_id = ANY($3::uuid[]))
`

type SoftDeleteFloorParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) SoftDeleteFloor(ctx context.Context, arg SoftDeleteFloorParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFloor, arg.ID, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFloor = `-- name: UpdateFloor :one
UPDATE masterdata.floors
SET office_id = $1, name = $2, level = $3
WHERE id = $4 AND deleted_at IS NULL
  AND ($5::bool OR office_id = ANY($6::uuid[]))
RETURNING id, office_id, name, level, created_at, updated_at, deleted_at
`

type UpdateFloorParams struct {
	OfficeID  uuid.UUID   `json:"office_id"`
	Name      string      `json:"name"`
	Level     *int32      `json:"level"`
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) UpdateFloor(ctx context.Context, arg UpdateFloorParams) (MasterdataFloor, error) {
	row := q.db.QueryRow(ctx, updateFloor,
		arg.OfficeID,
		arg.Name,
		arg.Level,
		arg.ID,
		arg.AllScope,
		arg.OfficeIds,
	)
	var i MasterdataFloor
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
