// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guide.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countGuideAttachments = `-- name: CountGuideAttachments :one
SELECT count(*) FROM guide.guide_attachments
WHERE module_id = $1 AND deleted_at IS NULL
`

// Menegakkan batas jumlah lampiran per modul. Dihitung di dalam transaksi yang
// sama dengan penyisipan supaya dua permintaan bersamaan tidak sama-sama lolos.
func (q *Queries) CountGuideAttachments(ctx context.Context, moduleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGuideAttachments, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuideAttachment = `-- name: CreateGuideAttachment :one
INSERT INTO guide.guide_attachments
  (module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10, $11
)
RETURNING id, module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by, created_at, updated_at, deleted_at
`

type CreateGuideAttachmentParams struct {
	ModuleID         uuid.UUID                 `json:"module_id"`
	Kind             SharedGuideAttachmentKind `json:"kind"`
	TitleID          string                    `json:"title_id"`
	TitleEn          *string                   `json:"title_en"`
	SortOrder        int32                     `json:"sort_order"`
	YoutubeID        *string                   `json:"youtube_id"`
	ObjectKey        *string                   `json:"object_key"`
	OriginalFilename *string                   `json:"original_filename"`
	MimeType         *string                   `json:"mime_type"`
	SizeBytes        *int64                    `json:"size_bytes"`
	Actor            *uuid.UUID                `json:"actor"`
}

func (q *Queries) CreateGuideAttachment(ctx context.Context, arg CreateGuideAttachmentParams) (GuideGuideAttachment, error) {
	row := q.db.QueryRow(ctx, createGuideAttachment,
		arg.ModuleID,
		arg.Kind,
		arg.TitleID,
		arg.TitleEn,
		arg.SortOrder,
		arg.YoutubeID,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.Actor,
	)
	var i GuideGuideAttachment
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Kind,
		&i.TitleID,
		&i.TitleEn,
		&i.SortOrder,
		&i.YoutubeID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGuideModule = `-- name: CreateGuideModule :one
INSERT INTO guide.guide_modules
  (slug, icon, sort_order, status, published_at, title_id, title_en, body_id, body_en, steps, created_by, updated_by)
VALUES (
  $1, $2, $3, $4,
  CASE WHEN $4::shared.guide_status = 'published' THEN now() END,
  $5, $6, $7, $8, $9, $10, $10
)
RETURNING id, slug, icon, sort_order, status, published_at, title_id, title_en, body_id, body_en, steps, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateGuideModuleParams struct {
	Slug      string            `json:"slug"`
	Icon      string            `json:"icon"`
	SortOrder int32             `json:"sort_order"`
	Status    SharedGuideStatus `json:"status"`
	TitleID   string            `json:"title_id"`
	TitleEn   *string           `json:"title_en"`
	BodyID    *string           `json:"body_id"`
	BodyEn    *string           `json:"body_en"`
	Steps     []byte            `json:"steps"`
	Actor     *uuid.UUID        `json:"actor"`
}

func (q *Queries) CreateGuideModule(ctx context.Context, arg CreateGuideModuleParams) (GuideGuideModule, error) {
	row := q.db.QueryRow(ctx, createGuideModule,
		arg.Slug,
		arg.Icon,
		arg.SortOrder,
		arg.Status,
		arg.TitleID,
		arg.TitleEn,
		arg.BodyID,
		arg.BodyEn,
		arg.Steps,
		arg.Actor,
	)
	var i GuideGuideModule
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.TitleID,
		&i.TitleEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Steps,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGuideAttachment = `-- name: GetGuideAttachment :one
SELECT id, module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by, created_at, updated_at, deleted_at FROM guide.guide_attachments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGuideAttachment(ctx context.Context, id uuid.UUID) (GuideGuideAttachment, error) {
	row := q.db.QueryRow(ctx, getGuideAttachment, id)
	var i GuideGuideAttachment
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Kind,
		&i.TitleID,
		&i.TitleEn,
		&i.SortOrder,
		&i.YoutubeID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGuideAttachmentForRead = `-- name: GetGuideAttachmentForRead :one
SELECT a.id, a.module_id, a.kind, a.title_id, a.title_en, a.sort_order, a.youtube_id, a.object_key, a.original_filename, a.mime_type, a.size_bytes, a.created_by, a.created_at, a.updated_at, a.deleted_at FROM guide.guide_attachments a
JOIN guide.guide_modules m ON m.id = a.module_id
WHERE a.id = $1
  AND a.deleted_at IS NULL
  AND m.deleted_at IS NULL
  AND ($2::boolean OR m.status = 'published')
`

type GetGuideAttachmentForReadParams struct {
	ID           uuid.UUID `json:"id"`
	IncludeDraft bool      `json:"include_draft"`
}

// Dipakai endpoint penyajian berkas. Status modul induk ikut disaring DI DALAM
// kueri, bukan diperiksa pada hasilnya: lampiran milik modul draf tidak
// dikembalikan sama sekali kecuali @include_draft menyala, dan handler hanya
// menyalakannya untuk pemanggil yang memegang guide.manage. Tanpa baris,
// pemanggil menerima 404 yang sama persis dengan id yang tidak ada — keberadaan
// draf pun tidak terbocorkan.
func (q *Queries) GetGuideAttachmentForRead(ctx context.Context, arg GetGuideAttachmentForReadParams) (GuideGuideAttachment, error) {
	row := q.db.QueryRow(ctx, getGuideAttachmentForRead, arg.ID, arg.IncludeDraft)
	var i GuideGuideAttachment
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Kind,
		&i.TitleID,
		&i.TitleEn,
		&i.SortOrder,
		&i.YoutubeID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGuideModule = `-- name: GetGuideModule :one
SELECT id, slug, icon, sort_order, status, published_at, title_id, title_en, body_id, body_en, steps, created_by, updated_by, created_at, updated_at, deleted_at FROM guide.guide_modules
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGuideModule(ctx context.Context, id uuid.UUID) (GuideGuideModule, error) {
	row := q.db.QueryRow(ctx, getGuideModule, id)
	var i GuideGuideModule
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.TitleID,
		&i.TitleEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Steps,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGuideAttachmentsByModules = `-- name: ListGuideAttachmentsByModules :many
SELECT id, module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by, created_at, updated_at, deleted_at FROM guide.guide_attachments
WHERE module_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY module_id, sort_order, created_at
`

// Dipakai daftar modul: satu kueri untuk seluruh modul yang tampil, bukan satu
// kueri per modul.
func (q *Queries) ListGuideAttachmentsByModules(ctx context.Context, moduleIds []uuid.UUID) ([]GuideGuideAttachment, error) {
	rows, err := q.db.Query(ctx, listGuideAttachmentsByModules, moduleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuideGuideAttachment{}
	for rows.Next() {
		var i GuideGuideAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Kind,
			&i.TitleID,
			&i.TitleEn,
			&i.SortOrder,
			&i.YoutubeID,
			&i.ObjectKey,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuideModules = `-- name: ListGuideModules :many

SELECT id, slug, icon, sort_order, status, published_at, title_id, title_en, body_id, body_en, steps, created_by, updated_by, created_at, updated_at, deleted_at FROM guide.guide_modules
WHERE deleted_at IS NULL
  AND ($1::boolean OR status = 'published')
ORDER BY sort_order, created_at
`

// Konten Panduan Penggunaan. Panduan bersifat global: tidak ada penyaringan
// office scope di mana pun berkas ini, dan itu memang disengaja (lihat
// docs/superpowers/plans/2026-08-08-guide-media-cms.md).
// Satu kueri untuk pembaca dan pengelola. @include_draft = false menyisakan
// modul terbit saja; handler hanya menyalakannya untuk pemanggil yang memegang
// guide.manage, sehingga draf tidak pernah bocor lewat parameter.
func (q *Queries) ListGuideModules(ctx context.Context, includeDraft bool) ([]GuideGuideModule, error) {
	rows, err := q.db.Query(ctx, listGuideModules, includeDraft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuideGuideModule{}
	for rows.Next() {
		var i GuideGuideModule
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Icon,
			&i.SortOrder,
			&i.Status,
			&i.PublishedAt,
			&i.TitleID,
			&i.TitleEn,
			&i.BodyID,
			&i.BodyEn,
			&i.Steps,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGuideAttachment = `-- name: SoftDeleteGuideAttachment :one
UPDATE guide.guide_attachments SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteGuideAttachment(ctx context.Context, id uuid.UUID) (GuideGuideAttachment, error) {
	row := q.db.QueryRow(ctx, softDeleteGuideAttachment, id)
	var i GuideGuideAttachment
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Kind,
		&i.TitleID,
		&i.TitleEn,
		&i.SortOrder,
		&i.YoutubeID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteGuideModule = `-- name: SoftDeleteGuideModule :one
UPDATE guide.guide_modules SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, slug, icon, sort_order, status, published_at, title_id, title_en, body_id, body_en, steps, created_by, updated_by, created_at, updated_at, deleted_at
`

type SoftDeleteGuideModuleParams struct {
	Actor *uuid.UUID `json:"actor"`
	ID    uuid.UUID  `json:"id"`
}

// Lampiran ikut ditandai terhapus dalam transaksi yang sama oleh service, bukan
// oleh cascade: baris lampiran perlu tetap ada supaya objek MinIO-nya masih bisa
// ditelusuri kalau penghapusan objek gagal.
func (q *Queries) SoftDeleteGuideModule(ctx context.Context, arg SoftDeleteGuideModuleParams) (GuideGuideModule, error) {
	row := q.db.QueryRow(ctx, softDeleteGuideModule, arg.Actor, arg.ID)
	var i GuideGuideModule
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.TitleID,
		&i.TitleEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Steps,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteGuideModuleAttachments = `-- name: SoftDeleteGuideModuleAttachments :many
UPDATE guide.guide_attachments SET deleted_at = now()
WHERE module_id = $1 AND deleted_at IS NULL
RETURNING id, module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteGuideModuleAttachments(ctx context.Context, moduleID uuid.UUID) ([]GuideGuideAttachment, error) {
	rows, err := q.db.Query(ctx, softDeleteGuideModuleAttachments, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuideGuideAttachment{}
	for rows.Next() {
		var i GuideGuideAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Kind,
			&i.TitleID,
			&i.TitleEn,
			&i.SortOrder,
			&i.YoutubeID,
			&i.ObjectKey,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuideAttachment = `-- name: UpdateGuideAttachment :one
UPDATE guide.guide_attachments SET
  title_id   = $1,
  title_en   = $2,
  sort_order = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, module_id, kind, title_id, title_en, sort_order, youtube_id, object_key, original_filename, mime_type, size_bytes, created_by, created_at, updated_at, deleted_at
`

type UpdateGuideAttachmentParams struct {
	TitleID   string    `json:"title_id"`
	TitleEn   *string   `json:"title_en"`
	SortOrder int32     `json:"sort_order"`
	ID        uuid.UUID `json:"id"`
}

// Hanya judul dan urutan. Berkas maupun tautan tidak bisa diganti di tempat:
// untuk itu lampirannya dihapus lalu dibuat ulang, sehingga tidak pernah ada
// baris yang menunjuk objek MinIO yang sudah bukan miliknya.
func (q *Queries) UpdateGuideAttachment(ctx context.Context, arg UpdateGuideAttachmentParams) (GuideGuideAttachment, error) {
	row := q.db.QueryRow(ctx, updateGuideAttachment,
		arg.TitleID,
		arg.TitleEn,
		arg.SortOrder,
		arg.ID,
	)
	var i GuideGuideAttachment
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Kind,
		&i.TitleID,
		&i.TitleEn,
		&i.SortOrder,
		&i.YoutubeID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGuideModule = `-- name: UpdateGuideModule :one
UPDATE guide.guide_modules SET
  slug         = $1,
  icon         = $2,
  sort_order   = $3,
  status       = $4,
  published_at = CASE
                   WHEN $4::shared.guide_status = 'published'
                     THEN COALESCE(published_at, now())
                   ELSE NULL
                 END,
  title_id     = $5,
  title_en     = $6,
  body_id      = $7,
  body_en      = $8,
  steps        = $9,
  updated_by   = $10
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, slug, icon, sort_order, status, published_at, title_id, title_en, body_id, body_en, steps, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateGuideModuleParams struct {
	Slug      string            `json:"slug"`
	Icon      string            `json:"icon"`
	SortOrder int32             `json:"sort_order"`
	Status    SharedGuideStatus `json:"status"`
	TitleID   string            `json:"title_id"`
	TitleEn   *string           `json:"title_en"`
	BodyID    *string           `json:"body_id"`
	BodyEn    *string           `json:"body_en"`
	Steps     []byte            `json:"steps"`
	Actor     *uuid.UUID        `json:"actor"`
	ID        uuid.UUID         `json:"id"`
}

// published_at menandai penerbitan PERTAMA dan tidak diperbarui saat modul yang
// sudah terbit disunting lagi; menariknya kembali ke draf mengosongkannya, jadi
// penerbitan berikutnya mencatat waktu barunya sendiri.
func (q *Queries) UpdateGuideModule(ctx context.Context, arg UpdateGuideModuleParams) (GuideGuideModule, error) {
	row := q.db.QueryRow(ctx, updateGuideModule,
		arg.Slug,
		arg.Icon,
		arg.SortOrder,
		arg.Status,
		arg.TitleID,
		arg.TitleEn,
		arg.BodyID,
		arg.BodyEn,
		arg.Steps,
		arg.Actor,
		arg.ID,
	)
	var i GuideGuideModule
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.TitleID,
		&i.TitleEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Steps,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
