// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (name, email, password_hash, role_id, office_id, employee_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, employee_id, office_id, name, email, password_hash, google_id, avatar_url, role_id, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name         string     `json:"name"`
	Email        string     `json:"email"`
	PasswordHash *string    `json:"password_hash"`
	RoleID       uuid.UUID  `json:"role_id"`
	OfficeID     *uuid.UUID `json:"office_id"`
	EmployeeID   *uuid.UUID `json:"employee_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.RoleID,
		arg.OfficeID,
		arg.EmployeeID,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.OfficeID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one

SELECT id, code, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles
WHERE code = $1 AND deleted_at IS NULL
`

// Identity module queries. Schema-qualified (see DATABASE.md §1.2).
func (q *Queries) GetRoleByCode(ctx context.Context, code string) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, employee_id, office_id, name, email, password_hash, google_id, avatar_url, role_id, status, created_at, updated_at, deleted_at FROM identity.users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.OfficeID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_id, office_id, name, email, password_hash, google_id, avatar_url, role_id, status, created_at, updated_at, deleted_at FROM identity.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.OfficeID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDataScopePolicies = `-- name: ListDataScopePolicies :many
SELECT id, role_id, module, scope_level, created_at, updated_at, deleted_at FROM identity.data_scope_policies
WHERE role_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListDataScopePolicies(ctx context.Context, roleID uuid.UUID) ([]IdentityDataScopePolicy, error) {
	rows, err := q.db.Query(ctx, listDataScopePolicies, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityDataScopePolicy{}
	for rows.Next() {
		var i IdentityDataScopePolicy
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Module,
			&i.ScopeLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT permission_key FROM identity.role_permissions
WHERE role_id = $1 AND deleted_at IS NULL
ORDER BY permission_key
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
