// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importer.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const cancelJob = `-- name: CancelJob :one
UPDATE import.import_jobs
SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status IN ('pending', 'validated')
RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

func (q *Queries) CancelJob(ctx context.Context, id uuid.UUID) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, cancelJob, id)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const claimConfirmedJob = `-- name: ClaimConfirmedJob :one
SELECT id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key FROM import.import_jobs
WHERE status = 'confirmed' AND deleted_at IS NULL
ORDER BY confirmed_at
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) ClaimConfirmedJob(ctx context.Context) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, claimConfirmedJob)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const claimPendingJob = `-- name: ClaimPendingJob :one
SELECT id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key FROM import.import_jobs
WHERE status = 'pending' AND deleted_at IS NULL
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) ClaimPendingJob(ctx context.Context) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, claimPendingJob)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const confirmJob = `-- name: ConfirmJob :one
UPDATE import.import_jobs
SET status = 'confirmed', confirmed_at = now()
WHERE id = $1 AND status = 'validated'
RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

func (q *Queries) ConfirmJob(ctx context.Context, id uuid.UUID) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, confirmJob, id)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const countImportJobs = `-- name: CountImportJobs :one
SELECT count(*) FROM import.import_jobs
WHERE deleted_at IS NULL
  AND created_by_id = $1
  AND ($2::text = '' OR target = $2::text)
`

type CountImportJobsParams struct {
	CreatedBy uuid.UUID `json:"created_by"`
	Target    string    `json:"target"`
}

func (q *Queries) CountImportJobs(ctx context.Context, arg CountImportJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobs, arg.CreatedBy, arg.Target)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImportRows = `-- name: CountImportRows :one
SELECT count(*) FROM import.import_rows
WHERE job_id = $1 AND deleted_at IS NULL
  AND ($2::bool = false OR valid = false)
`

type CountImportRowsParams struct {
	JobID      uuid.UUID `json:"job_id"`
	OnlyErrors bool      `json:"only_errors"`
}

func (q *Queries) CountImportRows(ctx context.Context, arg CountImportRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImportRows, arg.JobID, arg.OnlyErrors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import.import_jobs (target, format, filename, object_key, office_id, total_rows, created_by_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

type CreateImportJobParams struct {
	Target      string     `json:"target"`
	Format      string     `json:"format"`
	Filename    string     `json:"filename"`
	ObjectKey   *string    `json:"object_key"`
	OfficeID    *uuid.UUID `json:"office_id"`
	TotalRows   int32      `json:"total_rows"`
	CreatedByID uuid.UUID  `json:"created_by_id"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.Target,
		arg.Format,
		arg.Filename,
		arg.ObjectKey,
		arg.OfficeID,
		arg.TotalRows,
		arg.CreatedByID,
	)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key FROM import.import_jobs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetImportJob(ctx context.Context, id uuid.UUID) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJob, id)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const getImportJobForUpdate = `-- name: GetImportJobForUpdate :one
SELECT id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key FROM import.import_jobs WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetImportJobForUpdate(ctx context.Context, id uuid.UUID) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobForUpdate, id)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const insertImportRow = `-- name: InsertImportRow :one
INSERT INTO import.import_rows (job_id, row_no, data, valid, errors)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, row_no, data, valid, errors, result_ref, created_at, updated_at, deleted_at
`

type InsertImportRowParams struct {
	JobID  uuid.UUID `json:"job_id"`
	RowNo  int32     `json:"row_no"`
	Data   []byte    `json:"data"`
	Valid  bool      `json:"valid"`
	Errors []byte    `json:"errors"`
}

func (q *Queries) InsertImportRow(ctx context.Context, arg InsertImportRowParams) (ImportImportRow, error) {
	row := q.db.QueryRow(ctx, insertImportRow,
		arg.JobID,
		arg.RowNo,
		arg.Data,
		arg.Valid,
		arg.Errors,
	)
	var i ImportImportRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RowNo,
		&i.Data,
		&i.Valid,
		&i.Errors,
		&i.ResultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listImportJobs = `-- name: ListImportJobs :many
SELECT id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key FROM import.import_jobs
WHERE deleted_at IS NULL
  AND created_by_id = $1
  AND ($2::text = '' OR target = $2::text)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListImportJobsParams struct {
	CreatedBy uuid.UUID `json:"created_by"`
	Target    string    `json:"target"`
	Off       int32     `json:"off"`
	Lim       int32     `json:"lim"`
}

func (q *Queries) ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]ImportImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobs,
		arg.CreatedBy,
		arg.Target,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportImportJob{}
	for rows.Next() {
		var i ImportImportJob
		if err := rows.Scan(
			&i.ID,
			&i.Target,
			&i.Format,
			&i.Filename,
			&i.ObjectKey,
			&i.Status,
			&i.TotalRows,
			&i.SuccessRows,
			&i.FailedRows,
			&i.ErrorReportKey,
			&i.CreatedByID,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeID,
			&i.RequestID,
			&i.ConfirmedAt,
			&i.ErrorKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRows = `-- name: ListImportRows :many
SELECT id, job_id, row_no, data, valid, errors, result_ref, created_at, updated_at, deleted_at FROM import.import_rows
WHERE job_id = $1 AND deleted_at IS NULL
  AND ($2::bool = false OR valid = false)
ORDER BY row_no
LIMIT $4 OFFSET $3
`

type ListImportRowsParams struct {
	JobID      uuid.UUID `json:"job_id"`
	OnlyErrors bool      `json:"only_errors"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

func (q *Queries) ListImportRows(ctx context.Context, arg ListImportRowsParams) ([]ImportImportRow, error) {
	rows, err := q.db.Query(ctx, listImportRows,
		arg.JobID,
		arg.OnlyErrors,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportImportRow{}
	for rows.Next() {
		var i ImportImportRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RowNo,
			&i.Data,
			&i.Valid,
			&i.Errors,
			&i.ResultRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidImportRows = `-- name: ListValidImportRows :many
SELECT id, job_id, row_no, data, valid, errors, result_ref, created_at, updated_at, deleted_at FROM import.import_rows
WHERE job_id = $1 AND valid = true AND deleted_at IS NULL
ORDER BY row_no
`

func (q *Queries) ListValidImportRows(ctx context.Context, jobID uuid.UUID) ([]ImportImportRow, error) {
	rows, err := q.db.Query(ctx, listValidImportRows, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportImportRow{}
	for rows.Next() {
		var i ImportImportRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RowNo,
			&i.Data,
			&i.Valid,
			&i.Errors,
			&i.ResultRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRowFailed = `-- name: MarkRowFailed :exec
UPDATE import.import_rows SET valid = false, errors = $2 WHERE id = $1
`

type MarkRowFailedParams struct {
	ID     uuid.UUID `json:"id"`
	Errors []byte    `json:"errors"`
}

func (q *Queries) MarkRowFailed(ctx context.Context, arg MarkRowFailedParams) error {
	_, err := q.db.Exec(ctx, markRowFailed, arg.ID, arg.Errors)
	return err
}

const markRowResult = `-- name: MarkRowResult :exec
UPDATE import.import_rows SET result_ref = $2 WHERE id = $1
`

type MarkRowResultParams struct {
	ID        uuid.UUID `json:"id"`
	ResultRef *string   `json:"result_ref"`
}

func (q *Queries) MarkRowResult(ctx context.Context, arg MarkRowResultParams) error {
	_, err := q.db.Exec(ctx, markRowResult, arg.ID, arg.ResultRef)
	return err
}

const recoverStuckJobs = `-- name: RecoverStuckJobs :execrows
UPDATE import.import_jobs
SET status = CASE status WHEN 'processing' THEN 'pending'::shared.import_status
                         WHEN 'executing'  THEN 'confirmed'::shared.import_status
                         ELSE status END
WHERE status IN ('processing', 'executing') AND deleted_at IS NULL
`

func (q *Queries) RecoverStuckJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStuckJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJobRequest = `-- name: SetJobRequest :one
UPDATE import.import_jobs
SET status = 'awaiting_approval', request_id = $2
WHERE id = $1 RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

type SetJobRequestParams struct {
	ID        uuid.UUID  `json:"id"`
	RequestID *uuid.UUID `json:"request_id"`
}

func (q *Queries) SetJobRequest(ctx context.Context, arg SetJobRequestParams) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, setJobRequest, arg.ID, arg.RequestID)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const setJobResult = `-- name: SetJobResult :one
UPDATE import.import_jobs
SET status = $2, success_rows = $3, failed_rows = $4, error_key = $5, finished_at = now()
WHERE id = $1 RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

type SetJobResultParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      SharedImportStatus `json:"status"`
	SuccessRows int32              `json:"success_rows"`
	FailedRows  int32              `json:"failed_rows"`
	ErrorKey    *string            `json:"error_key"`
}

func (q *Queries) SetJobResult(ctx context.Context, arg SetJobResultParams) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, setJobResult,
		arg.ID,
		arg.Status,
		arg.SuccessRows,
		arg.FailedRows,
		arg.ErrorKey,
	)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const setJobValidated = `-- name: SetJobValidated :one
UPDATE import.import_jobs
SET status = 'validated', total_rows = $2, success_rows = $3, failed_rows = $4, office_id = $5
WHERE id = $1 RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

type SetJobValidatedParams struct {
	ID          uuid.UUID  `json:"id"`
	TotalRows   int32      `json:"total_rows"`
	SuccessRows int32      `json:"success_rows"`
	FailedRows  int32      `json:"failed_rows"`
	OfficeID    *uuid.UUID `json:"office_id"`
}

func (q *Queries) SetJobValidated(ctx context.Context, arg SetJobValidatedParams) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, setJobValidated,
		arg.ID,
		arg.TotalRows,
		arg.SuccessRows,
		arg.FailedRows,
		arg.OfficeID,
	)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE import.import_jobs SET status = $2 WHERE id = $1 RETURNING id, target, format, filename, object_key, status, total_rows, success_rows, failed_rows, error_report_key, created_by_id, finished_at, created_at, updated_at, deleted_at, office_id, request_id, confirmed_at, error_key
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status SharedImportStatus `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (ImportImportJob, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i ImportImportJob
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Format,
		&i.Filename,
		&i.ObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorReportKey,
		&i.CreatedByID,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeID,
		&i.RequestID,
		&i.ConfirmedAt,
		&i.ErrorKey,
	)
	return i, err
}
