// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SharedApproverLevel string

const (
	SharedApproverLevelOffice        SharedApproverLevel = "office"
	SharedApproverLevelOfficeSubtree SharedApproverLevel = "office_subtree"
	SharedApproverLevelWilayah       SharedApproverLevel = "wilayah"
	SharedApproverLevelPusat         SharedApproverLevel = "pusat"
)

func (e *SharedApproverLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedApproverLevel(s)
	case string:
		*e = SharedApproverLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedApproverLevel: %T", src)
	}
	return nil
}

type NullSharedApproverLevel struct {
	SharedApproverLevel SharedApproverLevel `json:"shared_approver_level"`
	Valid               bool                `json:"valid"` // Valid is true if SharedApproverLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedApproverLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SharedApproverLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedApproverLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedApproverLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedApproverLevel), nil
}

type SharedAssetClass string

const (
	SharedAssetClassTangible   SharedAssetClass = "tangible"
	SharedAssetClassIntangible SharedAssetClass = "intangible"
)

func (e *SharedAssetClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedAssetClass(s)
	case string:
		*e = SharedAssetClass(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedAssetClass: %T", src)
	}
	return nil
}

type NullSharedAssetClass struct {
	SharedAssetClass SharedAssetClass `json:"shared_asset_class"`
	Valid            bool             `json:"valid"` // Valid is true if SharedAssetClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedAssetClass) Scan(value interface{}) error {
	if value == nil {
		ns.SharedAssetClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedAssetClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedAssetClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedAssetClass), nil
}

type SharedAssetDocumentType string

const (
	SharedAssetDocumentTypeBastAcquisition SharedAssetDocumentType = "bast_acquisition"
	SharedAssetDocumentTypeBastTransfer    SharedAssetDocumentType = "bast_transfer"
	SharedAssetDocumentTypeBastDisposal    SharedAssetDocumentType = "bast_disposal"
	SharedAssetDocumentTypeInvoice         SharedAssetDocumentType = "invoice"
	SharedAssetDocumentTypeContract        SharedAssetDocumentType = "contract"
	SharedAssetDocumentTypeOther           SharedAssetDocumentType = "other"
)

func (e *SharedAssetDocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedAssetDocumentType(s)
	case string:
		*e = SharedAssetDocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedAssetDocumentType: %T", src)
	}
	return nil
}

type NullSharedAssetDocumentType struct {
	SharedAssetDocumentType SharedAssetDocumentType `json:"shared_asset_document_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if SharedAssetDocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedAssetDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.SharedAssetDocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedAssetDocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedAssetDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedAssetDocumentType), nil
}

type SharedAssetStatus string

const (
	SharedAssetStatusAvailable        SharedAssetStatus = "available"
	SharedAssetStatusAssigned         SharedAssetStatus = "assigned"
	SharedAssetStatusUnderMaintenance SharedAssetStatus = "under_maintenance"
	SharedAssetStatusInTransfer       SharedAssetStatus = "in_transfer"
	SharedAssetStatusRetired          SharedAssetStatus = "retired"
	SharedAssetStatusDisposed         SharedAssetStatus = "disposed"
	SharedAssetStatusLost             SharedAssetStatus = "lost"
)

func (e *SharedAssetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedAssetStatus(s)
	case string:
		*e = SharedAssetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedAssetStatus: %T", src)
	}
	return nil
}

type NullSharedAssetStatus struct {
	SharedAssetStatus SharedAssetStatus `json:"shared_asset_status"`
	Valid             bool              `json:"valid"` // Valid is true if SharedAssetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedAssetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedAssetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedAssetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedAssetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedAssetStatus), nil
}

type SharedAssignmentStatus string

const (
	SharedAssignmentStatusActive   SharedAssignmentStatus = "active"
	SharedAssignmentStatusReturned SharedAssignmentStatus = "returned"
)

func (e *SharedAssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedAssignmentStatus(s)
	case string:
		*e = SharedAssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedAssignmentStatus: %T", src)
	}
	return nil
}

type NullSharedAssignmentStatus struct {
	SharedAssignmentStatus SharedAssignmentStatus `json:"shared_assignment_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if SharedAssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedAssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedAssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedAssignmentStatus), nil
}

type SharedAttachmentKind string

const (
	SharedAttachmentKindPhoto    SharedAttachmentKind = "photo"
	SharedAttachmentKindDocument SharedAttachmentKind = "document"
)

func (e *SharedAttachmentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedAttachmentKind(s)
	case string:
		*e = SharedAttachmentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedAttachmentKind: %T", src)
	}
	return nil
}

type NullSharedAttachmentKind struct {
	SharedAttachmentKind SharedAttachmentKind `json:"shared_attachment_kind"`
	Valid                bool                 `json:"valid"` // Valid is true if SharedAttachmentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedAttachmentKind) Scan(value interface{}) error {
	if value == nil {
		ns.SharedAttachmentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedAttachmentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedAttachmentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedAttachmentKind), nil
}

type SharedAuditAction string

const (
	SharedAuditActionCreate SharedAuditAction = "create"
	SharedAuditActionUpdate SharedAuditAction = "update"
	SharedAuditActionDelete SharedAuditAction = "delete"
)

func (e *SharedAuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedAuditAction(s)
	case string:
		*e = SharedAuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedAuditAction: %T", src)
	}
	return nil
}

type NullSharedAuditAction struct {
	SharedAuditAction SharedAuditAction `json:"shared_audit_action"`
	Valid             bool              `json:"valid"` // Valid is true if SharedAuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.SharedAuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedAuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedAuditAction), nil
}

type SharedDepreciationBasis string

const (
	SharedDepreciationBasisCommercial SharedDepreciationBasis = "commercial"
	SharedDepreciationBasisFiscal     SharedDepreciationBasis = "fiscal"
)

func (e *SharedDepreciationBasis) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedDepreciationBasis(s)
	case string:
		*e = SharedDepreciationBasis(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedDepreciationBasis: %T", src)
	}
	return nil
}

type NullSharedDepreciationBasis struct {
	SharedDepreciationBasis SharedDepreciationBasis `json:"shared_depreciation_basis"`
	Valid                   bool                    `json:"valid"` // Valid is true if SharedDepreciationBasis is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedDepreciationBasis) Scan(value interface{}) error {
	if value == nil {
		ns.SharedDepreciationBasis, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedDepreciationBasis.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedDepreciationBasis) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedDepreciationBasis), nil
}

type SharedDepreciationMethod string

const (
	SharedDepreciationMethodStraightLine     SharedDepreciationMethod = "straight_line"
	SharedDepreciationMethodDecliningBalance SharedDepreciationMethod = "declining_balance"
)

func (e *SharedDepreciationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedDepreciationMethod(s)
	case string:
		*e = SharedDepreciationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedDepreciationMethod: %T", src)
	}
	return nil
}

type NullSharedDepreciationMethod struct {
	SharedDepreciationMethod SharedDepreciationMethod `json:"shared_depreciation_method"`
	Valid                    bool                     `json:"valid"` // Valid is true if SharedDepreciationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedDepreciationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.SharedDepreciationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedDepreciationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedDepreciationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedDepreciationMethod), nil
}

type SharedDepreciationPeriodStatus string

const (
	SharedDepreciationPeriodStatusOpen     SharedDepreciationPeriodStatus = "open"
	SharedDepreciationPeriodStatusComputed SharedDepreciationPeriodStatus = "computed"
	SharedDepreciationPeriodStatusClosed   SharedDepreciationPeriodStatus = "closed"
)

func (e *SharedDepreciationPeriodStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedDepreciationPeriodStatus(s)
	case string:
		*e = SharedDepreciationPeriodStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedDepreciationPeriodStatus: %T", src)
	}
	return nil
}

type NullSharedDepreciationPeriodStatus struct {
	SharedDepreciationPeriodStatus SharedDepreciationPeriodStatus `json:"shared_depreciation_period_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if SharedDepreciationPeriodStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedDepreciationPeriodStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedDepreciationPeriodStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedDepreciationPeriodStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedDepreciationPeriodStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedDepreciationPeriodStatus), nil
}

type SharedDisposalMethod string

const (
	SharedDisposalMethodSale     SharedDisposalMethod = "sale"
	SharedDisposalMethodAuction  SharedDisposalMethod = "auction"
	SharedDisposalMethodDonation SharedDisposalMethod = "donation"
	SharedDisposalMethodWriteOff SharedDisposalMethod = "write_off"
)

func (e *SharedDisposalMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedDisposalMethod(s)
	case string:
		*e = SharedDisposalMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedDisposalMethod: %T", src)
	}
	return nil
}

type NullSharedDisposalMethod struct {
	SharedDisposalMethod SharedDisposalMethod `json:"shared_disposal_method"`
	Valid                bool                 `json:"valid"` // Valid is true if SharedDisposalMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedDisposalMethod) Scan(value interface{}) error {
	if value == nil {
		ns.SharedDisposalMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedDisposalMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedDisposalMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedDisposalMethod), nil
}

type SharedFiscalAssetGroup string

const (
	SharedFiscalAssetGroupKelompok1           SharedFiscalAssetGroup = "kelompok_1"
	SharedFiscalAssetGroupKelompok2           SharedFiscalAssetGroup = "kelompok_2"
	SharedFiscalAssetGroupKelompok3           SharedFiscalAssetGroup = "kelompok_3"
	SharedFiscalAssetGroupKelompok4           SharedFiscalAssetGroup = "kelompok_4"
	SharedFiscalAssetGroupBangunanPermanen    SharedFiscalAssetGroup = "bangunan_permanen"
	SharedFiscalAssetGroupBangunanNonPermanen SharedFiscalAssetGroup = "bangunan_non_permanen"
	SharedFiscalAssetGroupNonSusut            SharedFiscalAssetGroup = "non_susut"
)

func (e *SharedFiscalAssetGroup) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedFiscalAssetGroup(s)
	case string:
		*e = SharedFiscalAssetGroup(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedFiscalAssetGroup: %T", src)
	}
	return nil
}

type NullSharedFiscalAssetGroup struct {
	SharedFiscalAssetGroup SharedFiscalAssetGroup `json:"shared_fiscal_asset_group"`
	Valid                  bool                   `json:"valid"` // Valid is true if SharedFiscalAssetGroup is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedFiscalAssetGroup) Scan(value interface{}) error {
	if value == nil {
		ns.SharedFiscalAssetGroup, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedFiscalAssetGroup.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedFiscalAssetGroup) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedFiscalAssetGroup), nil
}

type SharedImportStatus string

const (
	SharedImportStatusPending          SharedImportStatus = "pending"
	SharedImportStatusProcessing       SharedImportStatus = "processing"
	SharedImportStatusCompleted        SharedImportStatus = "completed"
	SharedImportStatusFailed           SharedImportStatus = "failed"
	SharedImportStatusValidated        SharedImportStatus = "validated"
	SharedImportStatusConfirmed        SharedImportStatus = "confirmed"
	SharedImportStatusExecuting        SharedImportStatus = "executing"
	SharedImportStatusAwaitingApproval SharedImportStatus = "awaiting_approval"
	SharedImportStatusCancelled        SharedImportStatus = "cancelled"
)

func (e *SharedImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedImportStatus(s)
	case string:
		*e = SharedImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedImportStatus: %T", src)
	}
	return nil
}

type NullSharedImportStatus struct {
	SharedImportStatus SharedImportStatus `json:"shared_import_status"`
	Valid              bool               `json:"valid"` // Valid is true if SharedImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedImportStatus), nil
}

type SharedMaintenanceStatus string

const (
	SharedMaintenanceStatusScheduled  SharedMaintenanceStatus = "scheduled"
	SharedMaintenanceStatusInProgress SharedMaintenanceStatus = "in_progress"
	SharedMaintenanceStatusCompleted  SharedMaintenanceStatus = "completed"
	SharedMaintenanceStatusCancelled  SharedMaintenanceStatus = "cancelled"
)

func (e *SharedMaintenanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedMaintenanceStatus(s)
	case string:
		*e = SharedMaintenanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedMaintenanceStatus: %T", src)
	}
	return nil
}

type NullSharedMaintenanceStatus struct {
	SharedMaintenanceStatus SharedMaintenanceStatus `json:"shared_maintenance_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if SharedMaintenanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedMaintenanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedMaintenanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedMaintenanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedMaintenanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedMaintenanceStatus), nil
}

type SharedMaintenanceType string

const (
	SharedMaintenanceTypePreventive SharedMaintenanceType = "preventive"
	SharedMaintenanceTypeCorrective SharedMaintenanceType = "corrective"
)

func (e *SharedMaintenanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedMaintenanceType(s)
	case string:
		*e = SharedMaintenanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedMaintenanceType: %T", src)
	}
	return nil
}

type NullSharedMaintenanceType struct {
	SharedMaintenanceType SharedMaintenanceType `json:"shared_maintenance_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if SharedMaintenanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedMaintenanceType) Scan(value interface{}) error {
	if value == nil {
		ns.SharedMaintenanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedMaintenanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedMaintenanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedMaintenanceType), nil
}

type SharedOpnameItemResult string

const (
	SharedOpnameItemResultPending   SharedOpnameItemResult = "pending"
	SharedOpnameItemResultFound     SharedOpnameItemResult = "found"
	SharedOpnameItemResultNotFound  SharedOpnameItemResult = "not_found"
	SharedOpnameItemResultDamaged   SharedOpnameItemResult = "damaged"
	SharedOpnameItemResultMisplaced SharedOpnameItemResult = "misplaced"
)

func (e *SharedOpnameItemResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedOpnameItemResult(s)
	case string:
		*e = SharedOpnameItemResult(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedOpnameItemResult: %T", src)
	}
	return nil
}

type NullSharedOpnameItemResult struct {
	SharedOpnameItemResult SharedOpnameItemResult `json:"shared_opname_item_result"`
	Valid                  bool                   `json:"valid"` // Valid is true if SharedOpnameItemResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedOpnameItemResult) Scan(value interface{}) error {
	if value == nil {
		ns.SharedOpnameItemResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedOpnameItemResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedOpnameItemResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedOpnameItemResult), nil
}

type SharedOpnameSessionStatus string

const (
	SharedOpnameSessionStatusOpen        SharedOpnameSessionStatus = "open"
	SharedOpnameSessionStatusCounting    SharedOpnameSessionStatus = "counting"
	SharedOpnameSessionStatusReconciling SharedOpnameSessionStatus = "reconciling"
	SharedOpnameSessionStatusClosed      SharedOpnameSessionStatus = "closed"
)

func (e *SharedOpnameSessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedOpnameSessionStatus(s)
	case string:
		*e = SharedOpnameSessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedOpnameSessionStatus: %T", src)
	}
	return nil
}

type NullSharedOpnameSessionStatus struct {
	SharedOpnameSessionStatus SharedOpnameSessionStatus `json:"shared_opname_session_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if SharedOpnameSessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedOpnameSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedOpnameSessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedOpnameSessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedOpnameSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedOpnameSessionStatus), nil
}

type SharedRequestStatus string

const (
	SharedRequestStatusPending   SharedRequestStatus = "pending"
	SharedRequestStatusApproved  SharedRequestStatus = "approved"
	SharedRequestStatusRejected  SharedRequestStatus = "rejected"
	SharedRequestStatusCancelled SharedRequestStatus = "cancelled"
)

func (e *SharedRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedRequestStatus(s)
	case string:
		*e = SharedRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedRequestStatus: %T", src)
	}
	return nil
}

type NullSharedRequestStatus struct {
	SharedRequestStatus SharedRequestStatus `json:"shared_request_status"`
	Valid               bool                `json:"valid"` // Valid is true if SharedRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedRequestStatus), nil
}

type SharedRequestType string

const (
	SharedRequestTypeAssetCreate        SharedRequestType = "asset_create"
	SharedRequestTypeAssetDisposal      SharedRequestType = "asset_disposal"
	SharedRequestTypeAssetTransfer      SharedRequestType = "asset_transfer"
	SharedRequestTypeAssignment         SharedRequestType = "assignment"
	SharedRequestTypeMaintenance        SharedRequestType = "maintenance"
	SharedRequestTypeValuationExclusion SharedRequestType = "valuation_exclusion"
	SharedRequestTypeAssetImport        SharedRequestType = "asset_import"
)

func (e *SharedRequestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedRequestType(s)
	case string:
		*e = SharedRequestType(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedRequestType: %T", src)
	}
	return nil
}

type NullSharedRequestType struct {
	SharedRequestType SharedRequestType `json:"shared_request_type"`
	Valid             bool              `json:"valid"` // Valid is true if SharedRequestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedRequestType) Scan(value interface{}) error {
	if value == nil {
		ns.SharedRequestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedRequestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedRequestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedRequestType), nil
}

type SharedScopeLevel string

const (
	SharedScopeLevelGlobal        SharedScopeLevel = "global"
	SharedScopeLevelOfficeSubtree SharedScopeLevel = "office_subtree"
	SharedScopeLevelOffice        SharedScopeLevel = "office"
	SharedScopeLevelOwn           SharedScopeLevel = "own"
)

func (e *SharedScopeLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedScopeLevel(s)
	case string:
		*e = SharedScopeLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedScopeLevel: %T", src)
	}
	return nil
}

type NullSharedScopeLevel struct {
	SharedScopeLevel SharedScopeLevel `json:"shared_scope_level"`
	Valid            bool             `json:"valid"` // Valid is true if SharedScopeLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedScopeLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SharedScopeLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedScopeLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedScopeLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedScopeLevel), nil
}

type SharedTransferCondition string

const (
	SharedTransferConditionBaik        SharedTransferCondition = "baik"
	SharedTransferConditionRusakRingan SharedTransferCondition = "rusak_ringan"
	SharedTransferConditionRusakBerat  SharedTransferCondition = "rusak_berat"
)

func (e *SharedTransferCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedTransferCondition(s)
	case string:
		*e = SharedTransferCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedTransferCondition: %T", src)
	}
	return nil
}

type NullSharedTransferCondition struct {
	SharedTransferCondition SharedTransferCondition `json:"shared_transfer_condition"`
	Valid                   bool                    `json:"valid"` // Valid is true if SharedTransferCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedTransferCondition) Scan(value interface{}) error {
	if value == nil {
		ns.SharedTransferCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedTransferCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedTransferCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedTransferCondition), nil
}

type SharedTransferStatus string

const (
	SharedTransferStatusPending   SharedTransferStatus = "pending"
	SharedTransferStatusApproved  SharedTransferStatus = "approved"
	SharedTransferStatusInTransit SharedTransferStatus = "in_transit"
	SharedTransferStatusReceived  SharedTransferStatus = "received"
	SharedTransferStatusRejected  SharedTransferStatus = "rejected"
	SharedTransferStatusCancelled SharedTransferStatus = "cancelled"
	SharedTransferStatusReturned  SharedTransferStatus = "returned"
)

func (e *SharedTransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedTransferStatus(s)
	case string:
		*e = SharedTransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedTransferStatus: %T", src)
	}
	return nil
}

type NullSharedTransferStatus struct {
	SharedTransferStatus SharedTransferStatus `json:"shared_transfer_status"`
	Valid                bool                 `json:"valid"` // Valid is true if SharedTransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedTransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedTransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedTransferStatus), nil
}

type SharedUserStatus string

const (
	SharedUserStatusActive    SharedUserStatus = "active"
	SharedUserStatusInactive  SharedUserStatus = "inactive"
	SharedUserStatusSuspended SharedUserStatus = "suspended"
)

func (e *SharedUserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SharedUserStatus(s)
	case string:
		*e = SharedUserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SharedUserStatus: %T", src)
	}
	return nil
}

type NullSharedUserStatus struct {
	SharedUserStatus SharedUserStatus `json:"shared_user_status"`
	Valid            bool             `json:"valid"` // Valid is true if SharedUserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSharedUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SharedUserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SharedUserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSharedUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SharedUserStatus), nil
}

type ApprovalApprovalThreshold struct {
	ID            uuid.UUID           `json:"id"`
	RequestType   SharedRequestType   `json:"request_type"`
	AmountFrom    string              `json:"amount_from"`
	AmountTo      *string             `json:"amount_to"`
	RequiredLevel SharedApproverLevel `json:"required_level"`
	StepOrder     int32               `json:"step_order"`
	IsActive      bool                `json:"is_active"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz  `json:"deleted_at"`
}

type ApprovalRequest struct {
	ID            uuid.UUID           `json:"id"`
	Type          SharedRequestType   `json:"type"`
	OfficeID      *uuid.UUID          `json:"office_id"`
	Amount        *string             `json:"amount"`
	CurrentStep   int32               `json:"current_step"`
	TargetEntity  *string             `json:"target_entity"`
	TargetID      *uuid.UUID          `json:"target_id"`
	Payload       []byte              `json:"payload"`
	Reason        *string             `json:"reason"`
	Status        SharedRequestStatus `json:"status"`
	RequestedByID uuid.UUID           `json:"requested_by_id"`
	DecidedByID   *uuid.UUID          `json:"decided_by_id"`
	DecisionNote  *string             `json:"decision_note"`
	DecidedAt     pgtype.Timestamptz  `json:"decided_at"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz  `json:"deleted_at"`
}

type ApprovalRequestApproval struct {
	ID            uuid.UUID           `json:"id"`
	RequestID     uuid.UUID           `json:"request_id"`
	StepOrder     int32               `json:"step_order"`
	RequiredLevel SharedApproverLevel `json:"required_level"`
	ApproverID    *uuid.UUID          `json:"approver_id"`
	Decision      SharedRequestStatus `json:"decision"`
	Note          *string             `json:"note"`
	DecidedAt     pgtype.Timestamptz  `json:"decided_at"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz  `json:"deleted_at"`
}

type AssetAsset struct {
	ID                       uuid.UUID                 `json:"id"`
	AssetTag                 string                    `json:"asset_tag"`
	Name                     string                    `json:"name"`
	CategoryID               uuid.UUID                 `json:"category_id"`
	BrandID                  *uuid.UUID                `json:"brand_id"`
	ModelID                  *uuid.UUID                `json:"model_id"`
	RoomID                   *uuid.UUID                `json:"room_id"`
	OfficeID                 uuid.UUID                 `json:"office_id"`
	UnitID                   *uuid.UUID                `json:"unit_id"`
	Status                   SharedAssetStatus         `json:"status"`
	SerialNumber             *string                   `json:"serial_number"`
	PurchaseDate             pgtype.Date               `json:"purchase_date"`
	PurchaseCost             *string                   `json:"purchase_cost"`
	VendorID                 *uuid.UUID                `json:"vendor_id"`
	PoNumber                 *string                   `json:"po_number"`
	FundingSource            *string                   `json:"funding_source"`
	WarrantyExpiry           pgtype.Date               `json:"warranty_expiry"`
	Specifications           []byte                    `json:"specifications"`
	AssetClass               SharedAssetClass          `json:"asset_class"`
	Capitalized              bool                      `json:"capitalized"`
	DepreciationMethod       *SharedDepreciationMethod `json:"depreciation_method"`
	UsefulLifeMonths         *int32                    `json:"useful_life_months"`
	SalvageValue             *string                   `json:"salvage_value"`
	FiscalGroup              *SharedFiscalAssetGroup   `json:"fiscal_group"`
	FiscalLifeMonths         *int32                    `json:"fiscal_life_months"`
	AccumulatedDepreciation  string                    `json:"accumulated_depreciation"`
	BookValue                *string                   `json:"book_value"`
	ImpairmentLoss           *string                   `json:"impairment_loss"`
	AcquisitionBastNo        *string                   `json:"acquisition_bast_no"`
	CurrentHolderEmployeeID  *uuid.UUID                `json:"current_holder_employee_id"`
	ExcludedFromValuation    bool                      `json:"excluded_from_valuation"`
	ValuationExclusionReason *string                   `json:"valuation_exclusion_reason"`
	CreatedByID              *uuid.UUID                `json:"created_by_id"`
	Notes                    *string                   `json:"notes"`
	CreatedAt                pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz        `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz        `json:"deleted_at"`
	ImpairedBookValue        *string                   `json:"impaired_book_value"`
}

type AssetAssetAttachment struct {
	ID               uuid.UUID            `json:"id"`
	AssetID          uuid.UUID            `json:"asset_id"`
	Kind             SharedAttachmentKind `json:"kind"`
	ObjectKey        string               `json:"object_key"`
	ThumbnailKey     *string              `json:"thumbnail_key"`
	OriginalFilename string               `json:"original_filename"`
	SizeBytes        int64                `json:"size_bytes"`
	MimeType         string               `json:"mime_type"`
	CreatedByID      *uuid.UUID           `json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz   `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz   `json:"deleted_at"`
}

type AssetAssetDocument struct {
	ID                uuid.UUID               `json:"id"`
	AssetID           uuid.UUID               `json:"asset_id"`
	DocType           SharedAssetDocumentType `json:"doc_type"`
	DocNo             *string                 `json:"doc_no"`
	DocDate           pgtype.Date             `json:"doc_date"`
	Counterparty      *string                 `json:"counterparty"`
	ObjectKey         *string                 `json:"object_key"`
	RelatedRequestID  *uuid.UUID              `json:"related_request_id"`
	RelatedTransferID *uuid.UUID              `json:"related_transfer_id"`
	RelatedDisposalID *uuid.UUID              `json:"related_disposal_id"`
	CreatedByID       *uuid.UUID              `json:"created_by_id"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz      `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz      `json:"deleted_at"`
}

type AssetAssetTagCounter struct {
	ID         uuid.UUID          `json:"id"`
	OfficeID   uuid.UUID          `json:"office_id"`
	CategoryID uuid.UUID          `json:"category_id"`
	Year       int32              `json:"year"`
	LastSeq    int32              `json:"last_seq"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AssignmentAssignment struct {
	ID           uuid.UUID              `json:"id"`
	AssetID      uuid.UUID              `json:"asset_id"`
	EmployeeID   uuid.UUID              `json:"employee_id"`
	AssignedByID uuid.UUID              `json:"assigned_by_id"`
	CheckoutDate pgtype.Timestamptz     `json:"checkout_date"`
	DueDate      pgtype.Date            `json:"due_date"`
	CheckinDate  pgtype.Timestamptz     `json:"checkin_date"`
	ConditionOut *string                `json:"condition_out"`
	ConditionIn  *string                `json:"condition_in"`
	Status       SharedAssignmentStatus `json:"status"`
	Notes        *string                `json:"notes"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz     `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz     `json:"deleted_at"`
}

type AuditAuditLog struct {
	ID         uuid.UUID          `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Action     SharedAuditAction  `json:"action"`
	Changes    []byte             `json:"changes"`
	Ip         *string            `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	OfficeID   *uuid.UUID         `json:"office_id"`
}

type DepreciationDepreciationEntry struct {
	ID                 uuid.UUID                `json:"id"`
	AssetID            uuid.UUID                `json:"asset_id"`
	Basis              SharedDepreciationBasis  `json:"basis"`
	Period             pgtype.Date              `json:"period"`
	OpeningValue       string                   `json:"opening_value"`
	DepreciationAmount string                   `json:"depreciation_amount"`
	ClosingValue       string                   `json:"closing_value"`
	Method             SharedDepreciationMethod `json:"method"`
	CreatedAt          pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz       `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz       `json:"deleted_at"`
}

type DepreciationDepreciationPeriod struct {
	ID           uuid.UUID                      `json:"id"`
	Period       pgtype.Date                    `json:"period"`
	Status       SharedDepreciationPeriodStatus `json:"status"`
	ComputedAt   pgtype.Timestamptz             `json:"computed_at"`
	ComputedBy   *uuid.UUID                     `json:"computed_by"`
	ClosedAt     pgtype.Timestamptz             `json:"closed_at"`
	ClosedBy     *uuid.UUID                     `json:"closed_by"`
	AssetCount   int32                          `json:"asset_count"`
	TotalAmount  string                         `json:"total_amount"`
	SkippedCount int32                          `json:"skipped_count"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
}

type DisposalDisposal struct {
	ID                  uuid.UUID            `json:"id"`
	AssetID             uuid.UUID            `json:"asset_id"`
	Method              SharedDisposalMethod `json:"method"`
	DisposalDate        pgtype.Date          `json:"disposal_date"`
	Proceeds            *string              `json:"proceeds"`
	BookValueAtDisposal *string              `json:"book_value_at_disposal"`
	GainLoss            *string              `json:"gain_loss"`
	BastNo              *string              `json:"bast_no"`
	ApprovedByID        *uuid.UUID           `json:"approved_by_id"`
	RequestID           *uuid.UUID           `json:"request_id"`
	CreatedByID         *uuid.UUID           `json:"created_by_id"`
	CreatedAt           pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz   `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz   `json:"deleted_at"`
}

type IdentityAppSetting struct {
	ID          uuid.UUID          `json:"id"`
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	ValueType   *string            `json:"value_type"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityDataScopePolicy struct {
	ID         uuid.UUID          `json:"id"`
	RoleID     uuid.UUID          `json:"role_id"`
	Module     string             `json:"module"`
	ScopeLevel SharedScopeLevel   `json:"scope_level"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityFieldPermission struct {
	ID        uuid.UUID          `json:"id"`
	Entity    string             `json:"entity"`
	Field     string             `json:"field"`
	RoleID    uuid.UUID          `json:"role_id"`
	CanView   bool               `json:"can_view"`
	CanEdit   bool               `json:"can_edit"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityRole struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityRolePermission struct {
	ID            uuid.UUID          `json:"id"`
	RoleID        uuid.UUID          `json:"role_id"`
	PermissionKey string             `json:"permission_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityUser struct {
	ID           uuid.UUID          `json:"id"`
	EmployeeID   *uuid.UUID         `json:"employee_id"`
	OfficeID     *uuid.UUID         `json:"office_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	GoogleID     *string            `json:"google_id"`
	AvatarUrl    *string            `json:"avatar_url"`
	RoleID       uuid.UUID          `json:"role_id"`
	Status       SharedUserStatus   `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type ImportImportJob struct {
	ID             uuid.UUID          `json:"id"`
	Target         string             `json:"target"`
	Format         string             `json:"format"`
	Filename       string             `json:"filename"`
	ObjectKey      *string            `json:"object_key"`
	Status         SharedImportStatus `json:"status"`
	TotalRows      int32              `json:"total_rows"`
	SuccessRows    int32              `json:"success_rows"`
	FailedRows     int32              `json:"failed_rows"`
	ErrorReportKey *string            `json:"error_report_key"`
	CreatedByID    uuid.UUID          `json:"created_by_id"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	OfficeID       *uuid.UUID         `json:"office_id"`
	RequestID      *uuid.UUID         `json:"request_id"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	ErrorKey       *string            `json:"error_key"`
}

type ImportImportRow struct {
	ID        uuid.UUID          `json:"id"`
	JobID     uuid.UUID          `json:"job_id"`
	RowNo     int32              `json:"row_no"`
	Data      []byte             `json:"data"`
	Valid     bool               `json:"valid"`
	Errors    []byte             `json:"errors"`
	ResultRef *string            `json:"result_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MaintenanceMaintenanceRecord struct {
	ID                    uuid.UUID               `json:"id"`
	AssetID               uuid.UUID               `json:"asset_id"`
	MaintenanceCategoryID *uuid.UUID              `json:"maintenance_category_id"`
	ProblemCategoryID     *uuid.UUID              `json:"problem_category_id"`
	Type                  SharedMaintenanceType   `json:"type"`
	Status                SharedMaintenanceStatus `json:"status"`
	ScheduledDate         pgtype.Date             `json:"scheduled_date"`
	CompletedDate         pgtype.Date             `json:"completed_date"`
	Cost                  *string                 `json:"cost"`
	VendorID              *uuid.UUID              `json:"vendor_id"`
	PerformedBy           *string                 `json:"performed_by"`
	Description           string                  `json:"description"`
	ReportedByID          *uuid.UUID              `json:"reported_by_id"`
	CreatedAt             pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz      `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz      `json:"deleted_at"`
	ScheduleID            *uuid.UUID              `json:"schedule_id"`
}

type MaintenanceMaintenanceSchedule struct {
	ID                    uuid.UUID          `json:"id"`
	AssetID               uuid.UUID          `json:"asset_id"`
	MaintenanceCategoryID *uuid.UUID         `json:"maintenance_category_id"`
	IntervalMonths        int32              `json:"interval_months"`
	LastDoneDate          pgtype.Date        `json:"last_done_date"`
	NextDueDate           pgtype.Date        `json:"next_due_date"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataBrand struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataCategory struct {
	ID                        uuid.UUID                 `json:"id"`
	Name                      string                    `json:"name"`
	Code                      *string                   `json:"code"`
	ParentID                  *uuid.UUID                `json:"parent_id"`
	DefaultDepreciationMethod *SharedDepreciationMethod `json:"default_depreciation_method"`
	DefaultUsefulLifeMonths   *int32                    `json:"default_useful_life_months"`
	DefaultSalvageRate        *string                   `json:"default_salvage_rate"`
	AssetClass                SharedAssetClass          `json:"asset_class"`
	DefaultFiscalGroup        *SharedFiscalAssetGroup   `json:"default_fiscal_group"`
	DefaultFiscalLifeMonths   *int32                    `json:"default_fiscal_life_months"`
	GlAccountCode             *string                   `json:"gl_account_code"`
	CapitalizationThreshold   *string                   `json:"capitalization_threshold"`
	IsActive                  bool                      `json:"is_active"`
	CreatedAt                 pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz        `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz        `json:"deleted_at"`
}

type MasterdataCity struct {
	ID         uuid.UUID          `json:"id"`
	ProvinceID uuid.UUID          `json:"province_id"`
	Name       string             `json:"name"`
	Code       *string            `json:"code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataDepartment struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Code      *string            `json:"code"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataEmployee struct {
	ID           uuid.UUID          `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Email        *string            `json:"email"`
	AvatarKey    *string            `json:"avatar_key"`
	DepartmentID *uuid.UUID         `json:"department_id"`
	PositionID   *uuid.UUID         `json:"position_id"`
	OfficeID     uuid.UUID          `json:"office_id"`
	Status       SharedUserStatus   `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	Phone        *string            `json:"phone"`
}

type MasterdataFloor struct {
	ID        uuid.UUID          `json:"id"`
	OfficeID  uuid.UUID          `json:"office_id"`
	Name      string             `json:"name"`
	Level     *int32             `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataMaintenanceCategory struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataModel struct {
	ID        uuid.UUID          `json:"id"`
	BrandID   uuid.UUID          `json:"brand_id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataOffice struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       *uuid.UUID         `json:"parent_id"`
	OfficeTypeID   uuid.UUID          `json:"office_type_id"`
	ProvinceID     *uuid.UUID         `json:"province_id"`
	CityID         *uuid.UUID         `json:"city_id"`
	Name           string             `json:"name"`
	Code           string             `json:"code"`
	CostCenterCode *string            `json:"cost_center_code"`
	Address        *string            `json:"address"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Latitude       *float64           `json:"latitude"`
	Longitude      *float64           `json:"longitude"`
}

type MasterdataOfficeType struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	IsActive  bool                 `json:"is_active"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt pgtype.Timestamptz   `json:"updated_at"`
	DeletedAt pgtype.Timestamptz   `json:"deleted_at"`
	Tier      *SharedApproverLevel `json:"tier"`
}

type MasterdataPosition struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataProblemCategory struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataProvince struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Code      *string            `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataRoom struct {
	ID        uuid.UUID          `json:"id"`
	FloorID   uuid.UUID          `json:"floor_id"`
	Name      string             `json:"name"`
	Code      *string            `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataUnit struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Symbol    *string            `json:"symbol"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterdataVendor struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	ContactName *string            `json:"contact_name"`
	Phone       *string            `json:"phone"`
	Email       *string            `json:"email"`
	Address     *string            `json:"address"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type StockopnameStockOpnameItem struct {
	ID                uuid.UUID              `json:"id"`
	SessionID         uuid.UUID              `json:"session_id"`
	AssetID           uuid.UUID              `json:"asset_id"`
	Expected          bool                   `json:"expected"`
	Result            SharedOpnameItemResult `json:"result"`
	CountedByID       *uuid.UUID             `json:"counted_by_id"`
	CountedAt         pgtype.Timestamptz     `json:"counted_at"`
	Note              *string                `json:"note"`
	CreatedAt         pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz     `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz     `json:"deleted_at"`
	FollowupRequestID *uuid.UUID             `json:"followup_request_id"`
	FollowupRecordID  *uuid.UUID             `json:"followup_record_id"`
}

type StockopnameStockOpnameSession struct {
	ID          uuid.UUID                 `json:"id"`
	OfficeID    uuid.UUID                 `json:"office_id"`
	Name        *string                   `json:"name"`
	Period      pgtype.Date               `json:"period"`
	Status      SharedOpnameSessionStatus `json:"status"`
	StartedByID uuid.UUID                 `json:"started_by_id"`
	StartedAt   pgtype.Timestamptz        `json:"started_at"`
	ClosedByID  *uuid.UUID                `json:"closed_by_id"`
	ClosedAt    pgtype.Timestamptz        `json:"closed_at"`
	CreatedAt   pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz        `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz        `json:"deleted_at"`
}

type TransferAssetTransfer struct {
	ID            uuid.UUID                `json:"id"`
	AssetID       uuid.UUID                `json:"asset_id"`
	FromOfficeID  uuid.UUID                `json:"from_office_id"`
	ToOfficeID    uuid.UUID                `json:"to_office_id"`
	ToRoomID      *uuid.UUID               `json:"to_room_id"`
	Status        SharedTransferStatus     `json:"status"`
	Reason        *string                  `json:"reason"`
	RequestedByID uuid.UUID                `json:"requested_by_id"`
	ApprovedByID  *uuid.UUID               `json:"approved_by_id"`
	ShippedDate   pgtype.Date              `json:"shipped_date"`
	ReceivedDate  pgtype.Date              `json:"received_date"`
	ReceivedByID  *uuid.UUID               `json:"received_by_id"`
	BastNo        *string                  `json:"bast_no"`
	RequestID     *uuid.UUID               `json:"request_id"`
	Notes         *string                  `json:"notes"`
	CreatedAt     pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz       `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz       `json:"deleted_at"`
	ConditionSent *SharedTransferCondition `json:"condition_sent"`
	TransferDate  pgtype.Date              `json:"transfer_date"`
	ReturnNote    *string                  `json:"return_note"`
}
