// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimUnpublishedOutbox = `-- name: ClaimUnpublishedOutbox :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, published_at, created_at, updated_at, deleted_at FROM notification.outbox
WHERE published_at IS NULL AND deleted_at IS NULL
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

// Same FOR UPDATE SKIP LOCKED claim the import worker uses, so two relays never
// publish the same row.
func (q *Queries) ClaimUnpublishedOutbox(ctx context.Context, limit int32) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotifications = `-- name: CountNotifications :one
SELECT count(*) FROM notification.notifications
WHERE user_id = $1 AND deleted_at IS NULL
  AND (NOT $2::boolean OR read_at IS NULL)
  AND (NOT $3::boolean OR read_at IS NOT NULL)
`

type CountNotificationsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	UnreadOnly bool      `json:"unread_only"`
	ReadOnly   bool      `json:"read_only"`
}

// Same predicate as ListNotifications so total always matches the filtered page.
func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, arg.UserID, arg.UnreadOnly, arg.ReadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notification.notifications
WHERE user_id = $1 AND read_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notification.notifications
  (user_id, type, params, entity_type, entity_id, dedup_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type CreateNotificationParams struct {
	UserID     uuid.UUID              `json:"user_id"`
	Type       SharedNotificationType `json:"type"`
	Params     []byte                 `json:"params"`
	EntityType *string                `json:"entity_type"`
	EntityID   *uuid.UUID             `json:"entity_id"`
	DedupKey   *string                `json:"dedup_key"`
}

// Notifications: the permanent per-user feed.
// ON CONFLICT DO NOTHING against uq_notif_dedup is what makes the at-least-once
// consumer safe -- redelivery cannot duplicate a row.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Params,
		arg.EntityType,
		arg.EntityID,
		arg.DedupKey,
	)
	return err
}

const enqueueOutbox = `-- name: EnqueueOutbox :one

INSERT INTO notification.outbox (event_type, aggregate_type, aggregate_id, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, event_type, aggregate_type, aggregate_id, payload, published_at, created_at, updated_at, deleted_at
`

type EnqueueOutboxParams struct {
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	Payload       []byte    `json:"payload"`
}

// Outbox: written inside the caller's business transaction, so a rollback leaves
// no orphan event and a commit can never lose one.
func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueOutbox,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, params, entity_type, entity_id, dedup_key, read_at, created_at, updated_at, deleted_at FROM notification.notifications
WHERE user_id = $1 AND deleted_at IS NULL
  AND (NOT $2::boolean OR read_at IS NULL)
  AND (NOT $3::boolean OR read_at IS NOT NULL)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListNotificationsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	UnreadOnly bool      `json:"unread_only"`
	ReadOnly   bool      `json:"read_only"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

// unread_only and read_only are mutually exclusive flags carrying the tri-state
// "read" filter: both false means no filter (the whole feed).
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]NotificationNotification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.ReadOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationNotification{}
	for rows.Next() {
		var i NotificationNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Params,
			&i.EntityType,
			&i.EntityID,
			&i.DedupKey,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notification.notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notification.notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, type, params, entity_type, entity_id, dedup_key, read_at, created_at, updated_at, deleted_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// user_id is part of the predicate, not just the lookup: marking someone else's
// notification read must affect zero rows (the handler turns that into a 404).
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (NotificationNotification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i NotificationNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Params,
		&i.EntityType,
		&i.EntityID,
		&i.DedupKey,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE notification.outbox SET published_at = now() WHERE id = $1
`

// Only ever called after XADD succeeds: an unpublished row is retried next tick
// rather than lost.
func (q *Queries) MarkOutboxPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const purgeNotifications = `-- name: PurgeNotifications :exec
UPDATE notification.notifications
SET deleted_at = now()
WHERE deleted_at IS NULL AND created_at < $1
`

// Retention purge. Soft delete keeps the convention; because every index is
// partial on deleted_at IS NULL, purged rows leave the indexes entirely, so the
// feed and unread count stay fast however large the table grows.
func (q *Queries) PurgeNotifications(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, purgeNotifications, cutoff)
	return err
}

const purgeOutbox = `-- name: PurgeOutbox :exec
UPDATE notification.outbox
SET deleted_at = now()
WHERE deleted_at IS NULL AND published_at IS NOT NULL AND created_at < $1
`

func (q *Queries) PurgeOutbox(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, purgeOutbox, cutoff)
	return err
}

const softDeleteNotificationsByDedupKey = `-- name: SoftDeleteNotificationsByDedupKey :exec

UPDATE notification.notifications
SET deleted_at = now()
WHERE dedup_key = $1 AND deleted_at IS NULL
`

// Auto-resolve: a notification whose turn has passed is soft-deleted, not just
// marked read -- it cannot be acted on, so it should not sit in the feed.
// Clears exactly one step. Every recipient of a step shares the same dedup_key
// (only user_id differs), so an exact match already sweeps all of them.
// Prefer this over the prefix form whenever a single step is meant: the prefix
// 'request:<id>:step:1' also matches step:10, step:11, ...
func (q *Queries) SoftDeleteNotificationsByDedupKey(ctx context.Context, dedupKey *string) error {
	_, err := q.db.Exec(ctx, softDeleteNotificationsByDedupKey, dedupKey)
	return err
}

const softDeleteNotificationsByDedupPrefix = `-- name: SoftDeleteNotificationsByDedupPrefix :exec
UPDATE notification.notifications
SET deleted_at = now()
WHERE dedup_key LIKE $1 || '%' AND deleted_at IS NULL
`

// Prefix form, for sweeping every step of a request at once. Callers must pass
// a prefix that cannot straddle a boundary -- 'request:<id>:step:' with the
// trailing colon, never 'request:<id>:step:<n>'. The keys carry no LIKE
// metacharacter (no '%' or '_'), so no escaping is needed.
func (q *Queries) SoftDeleteNotificationsByDedupPrefix(ctx context.Context, prefix *string) error {
	_, err := q.db.Exec(ctx, softDeleteNotificationsByDedupPrefix, prefix)
	return err
}
