// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvanceRequestStep(ctx context.Context, id uuid.UUID) (ApprovalRequest, error)
	// Depreciation engine queries. See docs/DATABASE.md §4.4 and spec 2026-07-05.
	// Transaction-scoped exclusive lock; released automatically at COMMIT/ROLLBACK.
	AdvisoryLockDepreciation(ctx context.Context) error
	// PSAK 48 impairment write-down: sets the money fields directly. No
	// depreciation entry is posted here — impairment is a separate loss, not a
	// depreciation expense. book_value is the DERIVED carrying amount (compute
	// rewrites it every run); impaired_book_value is the STABLE resume floor that
	// the compute's commercial resumption override picks up prospectively (see
	// RecordImpairment / regenerateBasis). Both are set to the recoverable amount
	// here; a later, deeper impairment lowers the floor further (correct).
	ApplyAssetImpairment(ctx context.Context, arg ApplyAssetImpairmentParams) (AssetAsset, error)
	BumpAssetTagCounter(ctx context.Context, arg BumpAssetTagCounterParams) (int32, error)
	CancelRequest(ctx context.Context, arg CancelRequestParams) (ApprovalRequest, error)
	CheckinAssignment(ctx context.Context, arg CheckinAssignmentParams) (AssignmentAssignment, error)
	CheckoutAssignment(ctx context.Context, arg CheckoutAssignmentParams) (AssignmentAssignment, error)
	// Active = scheduled or in_progress. exclude_id lets the caller ignore the row
	// it is about to transition (release check).
	CountActiveMaintRecordsByAsset(ctx context.Context, arg CountActiveMaintRecordsByAssetParams) (int64, error)
	CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error)
	CountAssignments(ctx context.Context, arg CountAssignmentsParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountCategories(ctx context.Context, search string) (int64, error)
	CountDisposals(ctx context.Context, arg CountDisposalsParams) (int64, error)
	CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error)
	CountFloorsByOffice(ctx context.Context, arg CountFloorsByOfficeParams) (int64, error)
	CountMaintRecords(ctx context.Context, arg CountMaintRecordsParams) (int64, error)
	CountMaintSchedules(ctx context.Context, arg CountMaintSchedulesParams) (int64, error)
	CountOffices(ctx context.Context, arg CountOfficesParams) (int64, error)
	CountOpenEarlierPeriods(ctx context.Context, period pgtype.Date) (int64, error)
	CountOpnameSessions(ctx context.Context, arg CountOpnameSessionsParams) (int64, error)
	CountPendingDisposalRequestsForAsset(ctx context.Context, assetID *uuid.UUID) (int64, error)
	// Duplicate-guard: pending maintenance request for the same asset by the same maker.
	CountPendingMaintRequests(ctx context.Context, arg CountPendingMaintRequestsParams) (int64, error)
	// Guard: an asset may have at most one pending asset_transfer approval request.
	CountPendingTransferRequestsForAsset(ctx context.Context, assetID *uuid.UUID) (int64, error)
	CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error)
	CountRoomsByFloor(ctx context.Context, arg CountRoomsByFloorParams) (int64, error)
	CountTransfers(ctx context.Context, arg CountTransfersParams) (int64, error)
	CountUsers(ctx context.Context, search string) (int64, error)
	CountUsersByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (AssetAsset, error)
	CreateAssetDocument(ctx context.Context, arg CreateAssetDocumentParams) (AssetAssetDocument, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (AssetAssetAttachment, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (MasterdataCategory, error)
	// gain_loss is computed here (null-propagating): null when either input is null.
	CreateDisposal(ctx context.Context, arg CreateDisposalParams) (DisposalDisposal, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (MasterdataEmployee, error)
	CreateFloor(ctx context.Context, arg CreateFloorParams) (MasterdataFloor, error)
	CreateMaintRecord(ctx context.Context, arg CreateMaintRecordParams) (MaintenanceMaintenanceRecord, error)
	CreateMaintSchedule(ctx context.Context, arg CreateMaintScheduleParams) (MaintenanceMaintenanceSchedule, error)
	CreateOffice(ctx context.Context, arg CreateOfficeParams) (MasterdataOffice, error)
	CreateOpnameSession(ctx context.Context, arg CreateOpnameSessionParams) (StockopnameStockOpnameSession, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (ApprovalRequest, error)
	CreateRequestApproval(ctx context.Context, arg CreateRequestApprovalParams) (ApprovalRequestApproval, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (IdentityRole, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (MasterdataRoom, error)
	CreateThreshold(ctx context.Context, arg CreateThresholdParams) (ApprovalApprovalThreshold, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (TransferAssetTransfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error)
	DecideRequestApproval(ctx context.Context, arg DecideRequestApprovalParams) (ApprovalRequestApproval, error)
	// Regeneration window: everything past the closed watermark up to the target period.
	DeleteEntriesAfterWatermark(ctx context.Context, arg DeleteEntriesAfterWatermarkParams) error
	// First-ever run (no watermark): clear everything ≤ target.
	DeleteEntriesThrough(ctx context.Context, target pgtype.Date) error
	// Used by the maintenance module (cross-schema rule): when releasing an asset
	// from under_maintenance, we must know whether an employee still holds it via
	// an active assignment, so it is restored to 'assigned' rather than 'available'.
	GetActiveAssignmentByAsset(ctx context.Context, assetID uuid.UUID) (AssignmentAssignment, error)
	GetAppSetting(ctx context.Context, key string) (string, error)
	GetAsset(ctx context.Context, id uuid.UUID) (AssetAsset, error)
	GetAssetByTag(ctx context.Context, assetTag string) (AssetAsset, error)
	GetAssetDocument(ctx context.Context, id uuid.UUID) (AssetAssetDocument, error)
	// Row-locked read for RecordImpairment's read-modify-write (precedent:
	// approval.sql GetRequestForUpdate): a second concurrent impairment blocks
	// here until the first commits, then re-reads the post-commit book_value/
	// impairment_loss so deltas accumulate instead of clobbering (lost update).
	GetAssetForUpdate(ctx context.Context, id uuid.UUID) (AssetAsset, error)
	GetAssetLabelByID(ctx context.Context, id uuid.UUID) (GetAssetLabelByIDRow, error)
	GetAssetLabelByTag(ctx context.Context, assetTag string) (GetAssetLabelByTagRow, error)
	GetAssignmentEnriched(ctx context.Context, arg GetAssignmentEnrichedParams) (GetAssignmentEnrichedRow, error)
	// Plain (unenriched) row, scoped by the asset's office. Used by Checkin to load +
	// validate state before the update.
	GetAssignmentScoped(ctx context.Context, arg GetAssignmentScopedParams) (AssignmentAssignment, error)
	GetAttachment(ctx context.Context, id uuid.UUID) (AssetAssetAttachment, error)
	GetCategory(ctx context.Context, id uuid.UUID) (MasterdataCategory, error)
	GetCategoryCode(ctx context.Context, id uuid.UUID) (*string, error)
	GetDepreciationPeriod(ctx context.Context, period pgtype.Date) (DepreciationDepreciationPeriod, error)
	// Guard (office-unscoped): at most one live disposal per asset.
	GetDisposalByAsset(ctx context.Context, assetID uuid.UUID) (DisposalDisposal, error)
	// Scoped: caller must have the asset's office in scope (disposals have no office_id).
	// The asset JOIN stays the scope anchor (INNER — a disposal always has a live
	// asset) and doubles as the source of asset_name/asset_tag. LEFT JOINs keep the
	// row visible (with nil names) even when a joined office/user was soft-deleted.
	GetDisposalEnriched(ctx context.Context, arg GetDisposalEnrichedParams) (GetDisposalEnrichedRow, error)
	GetEmployee(ctx context.Context, arg GetEmployeeParams) (MasterdataEmployee, error)
	GetFloor(ctx context.Context, arg GetFloorParams) (MasterdataFloor, error)
	GetMaintRecordEnriched(ctx context.Context, arg GetMaintRecordEnrichedParams) (GetMaintRecordEnrichedRow, error)
	GetMaintRecordScoped(ctx context.Context, arg GetMaintRecordScopedParams) (MaintenanceMaintenanceRecord, error)
	GetMaintScheduleScoped(ctx context.Context, arg GetMaintScheduleScopedParams) (MaintenanceMaintenanceSchedule, error)
	GetOffice(ctx context.Context, arg GetOfficeParams) (MasterdataOffice, error)
	GetOfficeAncestors(ctx context.Context, id uuid.UUID) ([]GetOfficeAncestorsRow, error)
	GetOfficeCode(ctx context.Context, id uuid.UUID) (string, error)
	// Authorization queries: office subtree (scoping) and field permissions.
	// Returns an office plus all of its descendants (Pusat -> Wilayah -> Cabang -> Outlet).
	GetOfficeSubtree(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// Guard: an asset may have at most one non-terminal transfer row.
	GetOpenTransferForAsset(ctx context.Context, assetID uuid.UUID) (TransferAssetTransfer, error)
	GetOpnameItem(ctx context.Context, arg GetOpnameItemParams) (StockopnameStockOpnameItem, error)
	GetOpnameItemByTag(ctx context.Context, arg GetOpnameItemByTagParams) (StockopnameStockOpnameItem, error)
	GetOpnameSession(ctx context.Context, arg GetOpnameSessionParams) (GetOpnameSessionRow, error)
	GetRequest(ctx context.Context, id uuid.UUID) (ApprovalRequest, error)
	// Enriched read variants: request row + resolved maker/role/office names.
	// LEFT JOINs keep rows visible even when the user/office was soft-deleted.
	GetRequestEnriched(ctx context.Context, id uuid.UUID) (GetRequestEnrichedRow, error)
	GetRequestForUpdate(ctx context.Context, id uuid.UUID) (ApprovalRequest, error)
	GetRole(ctx context.Context, id uuid.UUID) (IdentityRole, error)
	// Identity module queries. Schema-qualified (see DATABASE.md §1.2).
	GetRoleByCode(ctx context.Context, code string) (IdentityRole, error)
	GetRoom(ctx context.Context, arg GetRoomParams) (MasterdataRoom, error)
	// Scoped: caller must have the from- or to-office in scope. Plain (unenriched)
	// row — used internally by Ship/Receive/RejectReceive, which only need the
	// base columns to validate state + perform the update.
	GetTransfer(ctx context.Context, arg GetTransferParams) (TransferAssetTransfer, error)
	// Scoped: caller must have the from- or to-office in scope. Adds resolved
	// asset/office/room/actor display names for the detail view. LEFT JOINs keep
	// the row visible (with nil names) even when a joined entity was soft-deleted.
	GetTransferEnriched(ctx context.Context, arg GetTransferEnrichedParams) (GetTransferEnrichedRow, error)
	GetUserByEmail(ctx context.Context, email string) (IdentityUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	// Audit log: append-only writes + an office-scoped, filterable read model.
	// all_scope bypasses the office filter (global scope); otherwise only rows whose
	// office_id is in office_ids are returned. NULL-office (global) rows are visible
	// only to all-scope callers.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditAuditLog, error)
	InsertDataScopePolicy(ctx context.Context, arg InsertDataScopePolicyParams) (IdentityDataScopePolicy, error)
	InsertDepreciationEntry(ctx context.Context, arg InsertDepreciationEntryParams) error
	InsertFieldPermission(ctx context.Context, arg InsertFieldPermissionParams) (IdentityFieldPermission, error)
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) (IdentityRolePermission, error)
	// (scan reuses assets.sql GetAssetByTag; scope enforced in the service)
	// NOTE: :one + ON CONFLICT DO NOTHING → a conflict returns pgx.ErrNoRows (no row inserted); the caller treats that as "already present".
	InsertUnexpectedItem(ctx context.Context, arg InsertUnexpectedItemParams) (StockopnameStockOpnameItem, error)
	LastClosedPeriod(ctx context.Context) (pgtype.Date, error)
	LastEntryAtOrBefore(ctx context.Context, arg LastEntryAtOrBeforeParams) (DepreciationDepreciationEntry, error)
	LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) error
	ListAssetDocuments(ctx context.Context, assetID uuid.UUID) ([]AssetAssetDocument, error)
	ListAssetEntries(ctx context.Context, assetID uuid.UUID) ([]DepreciationDepreciationEntry, error)
	// Asset core queries (asset.assets + asset.asset_tag_counters).
	// Respects soft delete and caller data scope (all_scope / office_ids).
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]AssetAsset, error)
	// Every capitalized, non-deleted asset with its category (engine resolves/skips per-asset).
	ListAssetsForDepreciation(ctx context.Context) ([]ListAssetsForDepreciationRow, error)
	// Capitalized assets in scope with NO entry for the requested period+basis —
	// the schedule's "fully depreciated, no new entry this period" union rows.
	// The service further drops any row whose Resolve{Commercial,Fiscal} skips
	// (data drift since the asset last depreciated), keeping only "parameterized"
	// assets per the module spec.
	ListAssetsForScheduleUnion(ctx context.Context, arg ListAssetsForScheduleUnionParams) ([]ListAssetsForScheduleUnionRow, error)
	ListAssignmentsByAssetEnriched(ctx context.Context, arg ListAssignmentsByAssetEnrichedParams) ([]ListAssignmentsByAssetEnrichedRow, error)
	ListAssignmentsEnriched(ctx context.Context, arg ListAssignmentsEnrichedParams) ([]ListAssignmentsEnrichedRow, error)
	ListAttachments(ctx context.Context, assetID uuid.UUID) ([]AssetAssetAttachment, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// Asset category master data (masterdata.categories). Respects soft delete.
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]MasterdataCategory, error)
	// The full non-deleted category set (no pagination) for client-side tree building.
	ListCategoryTree(ctx context.Context) ([]MasterdataCategory, error)
	ListDataScopePolicies(ctx context.Context, roleID uuid.UUID) ([]IdentityDataScopePolicy, error)
	ListDepreciationPeriods(ctx context.Context) ([]DepreciationDepreciationPeriod, error)
	ListDisposalsByAssetEnriched(ctx context.Context, arg ListDisposalsByAssetEnrichedParams) ([]ListDisposalsByAssetEnrichedRow, error)
	ListDisposalsEnriched(ctx context.Context, arg ListDisposalsEnrichedParams) ([]ListDisposalsEnrichedRow, error)
	// Employees (asset custodians) with data-scoping by office.
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]MasterdataEmployee, error)
	// Schedule/journal source: entries of one period+basis joined to asset+category+office.
	// Embeds the full category row (not just name/gl_account_code) so callers can
	// also re-resolve Params (method/life_months) via ResolveCommercial/ResolveFiscal.
	ListEntriesForPeriod(ctx context.Context, arg ListEntriesForPeriodParams) ([]ListEntriesForPeriodRow, error)
	ListFieldPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]ListFieldPermissionsByRoleRow, error)
	// Floors (within an office). Listed per office; single-row ops carry the
	// office scope (all_scope OR office_id = ANY(office_ids)).
	ListFloorsByOffice(ctx context.Context, arg ListFloorsByOfficeParams) ([]MasterdataFloor, error)
	ListInboxCandidates(ctx context.Context) ([]ApprovalRequest, error)
	ListInboxCandidatesEnriched(ctx context.Context) ([]ListInboxCandidatesEnrichedRow, error)
	// Assets flagged under_maintenance (e.g. by assignment check-in) with no active
	// maintenance record — the "Perlu Tindak Lanjut" queue.
	ListMaintAttentionAssets(ctx context.Context, arg ListMaintAttentionAssetsParams) ([]ListMaintAttentionAssetsRow, error)
	ListMaintRecordsByAssetEnriched(ctx context.Context, arg ListMaintRecordsByAssetEnrichedParams) ([]ListMaintRecordsByAssetEnrichedRow, error)
	ListMaintRecordsEnriched(ctx context.Context, arg ListMaintRecordsEnrichedParams) ([]ListMaintRecordsEnrichedRow, error)
	ListMaintSchedulesEnriched(ctx context.Context, arg ListMaintSchedulesEnrichedParams) ([]ListMaintSchedulesEnrichedRow, error)
	// Offices (hierarchy) with data-scoping. all_scope bypasses the office filter
	// (global scope); otherwise only offices whose id is in office_ids are returned.
	ListOffices(ctx context.Context, arg ListOfficesParams) ([]MasterdataOffice, error)
	// Geo-enriched, scoped office list for the Peta Lokasi screen: resolves
	// office-type/province/city names + a per-office (non-deleted) asset count.
	ListOfficesMap(ctx context.Context, arg ListOfficesMapParams) ([]ListOfficesMapRow, error)
	ListOpnameItemsEnriched(ctx context.Context, arg ListOpnameItemsEnrichedParams) ([]ListOpnameItemsEnrichedRow, error)
	ListOpnameSessions(ctx context.Context, arg ListOpnameSessionsParams) ([]ListOpnameSessionsRow, error)
	ListRequestApprovals(ctx context.Context, requestID uuid.UUID) ([]ApprovalRequestApproval, error)
	ListRequestApprovalsEnriched(ctx context.Context, requestID uuid.UUID) ([]ListRequestApprovalsEnrichedRow, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ApprovalRequest, error)
	ListRequestsEnriched(ctx context.Context, arg ListRequestsEnrichedParams) ([]ListRequestsEnrichedRow, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRoles(ctx context.Context) ([]IdentityRole, error)
	// Rooms (within a floor). Scope is derived from the room's floor -> office.
	ListRoomsByFloor(ctx context.Context, arg ListRoomsByFloorParams) ([]MasterdataRoom, error)
	ListThresholds(ctx context.Context) ([]ApprovalApprovalThreshold, error)
	// Per-asset history, scoped by from- or to-office. Same enrichment as
	// GetTransferEnriched/ListTransfersEnriched.
	ListTransfersByAssetEnriched(ctx context.Context, arg ListTransfersByAssetEnrichedParams) ([]ListTransfersByAssetEnrichedRow, error)
	ListTransfersEnriched(ctx context.Context, arg ListTransfersEnrichedParams) ([]ListTransfersEnrichedRow, error)
	// User management queries (Superadmin). All respect soft delete.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUser, error)
	// Approval / maker-checker queries (approval schema).
	// See docs/DATABASE.md §4.5 and PRD §3.6 for schema context.
	MatchThresholdSteps(ctx context.Context, arg MatchThresholdStepsParams) ([]ApprovalApprovalThreshold, error)
	SessionKpis(ctx context.Context, sessionID uuid.UUID) (SessionKpisRow, error)
	SetAssetDocumentObjectKey(ctx context.Context, arg SetAssetDocumentObjectKeyParams) (AssetAssetDocument, error)
	// Relocate an asset to a new office/room (used by the transfer receive step).
	SetAssetOffice(ctx context.Context, arg SetAssetOfficeParams) (AssetAsset, error)
	SetAssetStatus(ctx context.Context, arg SetAssetStatusParams) (AssetAsset, error)
	SetAssetValuationExclusion(ctx context.Context, arg SetAssetValuationExclusionParams) (AssetAsset, error)
	SetDisposalBastNo(ctx context.Context, arg SetDisposalBastNoParams) (DisposalDisposal, error)
	SetItemFollowup(ctx context.Context, arg SetItemFollowupParams) (StockopnameStockOpnameItem, error)
	SetItemFollowupRecord(ctx context.Context, arg SetItemFollowupRecordParams) (StockopnameStockOpnameItem, error)
	SetOpnameItemResult(ctx context.Context, arg SetOpnameItemResultParams) (StockopnameStockOpnameItem, error)
	SetPeriodClosed(ctx context.Context, arg SetPeriodClosedParams) (DepreciationDepreciationPeriod, error)
	SetRequestDecision(ctx context.Context, arg SetRequestDecisionParams) (ApprovalRequest, error)
	SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) (StockopnameStockOpnameSession, error)
	SetTransferReceived(ctx context.Context, arg SetTransferReceivedParams) (TransferAssetTransfer, error)
	// Receiving side declines the shipment: terminal 'returned', asset never moved.
	SetTransferReturned(ctx context.Context, arg SetTransferReturnedParams) (TransferAssetTransfer, error)
	SetTransferShipped(ctx context.Context, arg SetTransferShippedParams) (TransferAssetTransfer, error)
	SnapshotSessionItems(ctx context.Context, arg SnapshotSessionItemsParams) error
	SoftDeleteAssetDocument(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteAttachment(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteCategory(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteDataScopePoliciesByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) (int64, error)
	SoftDeleteFieldPermissionsByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	SoftDeleteFloor(ctx context.Context, arg SoftDeleteFloorParams) (int64, error)
	SoftDeleteMaintSchedule(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteOffice(ctx context.Context, arg SoftDeleteOfficeParams) (int64, error)
	SoftDeleteRole(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteRolePermissionsByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (int64, error)
	SoftDeleteThreshold(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	// Per-asset accumulated depreciation for one basis, through (inclusive of) a
	// given period — the schedule's "accumulated" column source, for both the
	// entry-sourced and union rows.
	SumAmountsThroughPeriodByAsset(ctx context.Context, arg SumAmountsThroughPeriodByAssetParams) ([]SumAmountsThroughPeriodByAssetRow, error)
	SumAssetAmounts(ctx context.Context, arg SumAssetAmountsParams) (string, error)
	TouchMaintScheduleDone(ctx context.Context, arg TouchMaintScheduleDoneParams) (MaintenanceMaintenanceSchedule, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (AssetAsset, error)
	UpdateAssetDepreciationSummary(ctx context.Context, arg UpdateAssetDepreciationSummaryParams) error
	UpdateAssetDocument(ctx context.Context, arg UpdateAssetDocumentParams) (AssetAssetDocument, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MasterdataCategory, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (MasterdataEmployee, error)
	UpdateFloor(ctx context.Context, arg UpdateFloorParams) (MasterdataFloor, error)
	UpdateMaintRecord(ctx context.Context, arg UpdateMaintRecordParams) (MaintenanceMaintenanceRecord, error)
	UpdateMaintSchedule(ctx context.Context, arg UpdateMaintScheduleParams) (MaintenanceMaintenanceSchedule, error)
	UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (MasterdataOffice, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (IdentityRole, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (MasterdataRoom, error)
	UpdateThreshold(ctx context.Context, arg UpdateThresholdParams) (ApprovalApprovalThreshold, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (IdentityUser, error)
	// The DO UPDATE's WHERE guard makes a closed period unmatchable (0 rows →
	// pgx.ErrNoRows): even if a ComputePeriod raced past its status pre-check, it
	// can never flip a closed period back to 'computed'. The service maps that
	// ErrNoRows to ErrPeriodClosed and rolls back the regenerated entries.
	UpsertPeriodComputed(ctx context.Context, arg UpsertPeriodComputedParams) (DepreciationDepreciationPeriod, error)
}

var _ Querier = (*Queries)(nil)
