// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error)
	// Identity module queries. Schema-qualified (see DATABASE.md §1.2).
	GetRoleByCode(ctx context.Context, code string) (IdentityRole, error)
	GetUserByEmail(ctx context.Context, email string) (IdentityUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	ListDataScopePolicies(ctx context.Context, roleID uuid.UUID) ([]IdentityDataScopePolicy, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRoles(ctx context.Context) ([]IdentityRole, error)
}

var _ Querier = (*Queries)(nil)
