// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Serialize per-office tag-sequence allocation within the caller's transaction
	// (pg_advisory_xact_lock is released at commit/rollback). $1 = office id (text).
	AcquireOfficeTagLock(ctx context.Context, hashtext string) error
	AdvanceRequestStep(ctx context.Context, id uuid.UUID) (ApprovalRequest, error)
	// Depreciation engine queries. See docs/DATABASE.md §4.4 and spec 2026-07-05.
	// Transaction-scoped exclusive lock; released automatically at COMMIT/ROLLBACK.
	AdvisoryLockDepreciation(ctx context.Context) error
	// Sweeper: one instance at a time. Transaction-scoped exclusive lock, released
	// automatically at COMMIT/ROLLBACK (precedent: AdvisoryLockDepreciation).
	AdvisoryLockNotificationSweep(ctx context.Context) error
	// PSAK 48 impairment write-down: sets the money fields directly. No
	// depreciation entry is posted here — impairment is a separate loss, not a
	// depreciation expense. book_value is the DERIVED carrying amount (compute
	// rewrites it every run); impaired_book_value is the STABLE resume floor that
	// the compute's commercial resumption override picks up prospectively (see
	// RecordImpairment / regenerateBasis). Both are set to the recoverable amount
	// here; a later, deeper impairment lowers the floor further (correct).
	ApplyAssetImpairment(ctx context.Context, arg ApplyAssetImpairmentParams) (AssetAsset, error)
	CancelJob(ctx context.Context, id uuid.UUID) (ImportImportJob, error)
	CancelRequest(ctx context.Context, arg CancelRequestParams) (ApprovalRequest, error)
	CheckinAssignment(ctx context.Context, arg CheckinAssignmentParams) (AssignmentAssignment, error)
	CheckoutAssignment(ctx context.Context, arg CheckoutAssignmentParams) (AssignmentAssignment, error)
	ClaimConfirmedJob(ctx context.Context) (ImportImportJob, error)
	ClaimPendingJob(ctx context.Context) (ImportImportJob, error)
	// Same FOR UPDATE SKIP LOCKED claim the import worker uses, so two relays never
	// publish the same row.
	ClaimUnpublishedOutbox(ctx context.Context, limit int32) ([]NotificationOutbox, error)
	ConfirmJob(ctx context.Context, id uuid.UUID) (ImportImportJob, error)
	// Active = scheduled or in_progress. exclude_id lets the caller ignore the row
	// it is about to transition (release check).
	CountActiveMaintRecordsByAsset(ctx context.Context, arg CountActiveMaintRecordsByAssetParams) (int64, error)
	CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error)
	CountAssignments(ctx context.Context, arg CountAssignmentsParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountCategories(ctx context.Context, search string) (int64, error)
	CountDisposals(ctx context.Context, arg CountDisposalsParams) (int64, error)
	CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error)
	CountFloorsByOffice(ctx context.Context, arg CountFloorsByOfficeParams) (int64, error)
	CountImportJobs(ctx context.Context, arg CountImportJobsParams) (int64, error)
	CountImportRows(ctx context.Context, arg CountImportRowsParams) (int64, error)
	CountMaintRecords(ctx context.Context, arg CountMaintRecordsParams) (int64, error)
	CountMaintSchedules(ctx context.Context, arg CountMaintSchedulesParams) (int64, error)
	// Same predicate as ListNotifications so total always matches the filtered page.
	CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error)
	CountOffices(ctx context.Context, arg CountOfficesParams) (int64, error)
	CountOpenEarlierPeriods(ctx context.Context, period pgtype.Date) (int64, error)
	CountOpnameSessions(ctx context.Context, arg CountOpnameSessionsParams) (int64, error)
	CountPendingDisposalRequestsForAsset(ctx context.Context, assetID *uuid.UUID) (int64, error)
	// Duplicate-guard: pending maintenance request for the same asset by the same maker.
	CountPendingMaintRequests(ctx context.Context, arg CountPendingMaintRequestsParams) (int64, error)
	// Guard: an asset may have at most one pending asset_transfer approval request.
	CountPendingTransferRequestsForAsset(ctx context.Context, assetID *uuid.UUID) (int64, error)
	CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error)
	CountRoomsByFloor(ctx context.Context, arg CountRoomsByFloorParams) (int64, error)
	CountTransfers(ctx context.Context, arg CountTransfersParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountUsersByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (AssetAsset, error)
	CreateAssetDocument(ctx context.Context, arg CreateAssetDocumentParams) (AssetAssetDocument, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (AssetAssetAttachment, error)
	CreateBrand(ctx context.Context, name string) (MasterdataBrand, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (MasterdataCategory, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (MasterdataCity, error)
	// gain_loss is computed here (null-propagating): null when either input is null.
	CreateDisposal(ctx context.Context, arg CreateDisposalParams) (DisposalDisposal, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (MasterdataEmployee, error)
	CreateFloor(ctx context.Context, arg CreateFloorParams) (MasterdataFloor, error)
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportImportJob, error)
	CreateMaintRecord(ctx context.Context, arg CreateMaintRecordParams) (MaintenanceMaintenanceRecord, error)
	CreateMaintSchedule(ctx context.Context, arg CreateMaintScheduleParams) (MaintenanceMaintenanceSchedule, error)
	CreateModel(ctx context.Context, arg CreateModelParams) (MasterdataModel, error)
	// Notifications: the permanent per-user feed.
	// ON CONFLICT DO NOTHING against uq_notif_dedup is what makes the at-least-once
	// consumer safe -- redelivery cannot duplicate a row.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreateOffice(ctx context.Context, arg CreateOfficeParams) (MasterdataOffice, error)
	CreateOpnameSession(ctx context.Context, arg CreateOpnameSessionParams) (StockopnameStockOpnameSession, error)
	// Dedicated queries for the reference-target bulk importer (provinces, cities).
	// These exist alongside the generic reference engine (internal/masterdata/reference/engine.go)
	// because the engine operates on a *pgxpool.Pool directly and cannot join the
	// import worker's sqlc transaction (target.Execute receives a tx-bound
	// *sqlc.Queries). See internal/masterdata/reference/importer.go.
	CreateProvince(ctx context.Context, arg CreateProvinceParams) (MasterdataProvince, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (ApprovalRequest, error)
	CreateRequestApproval(ctx context.Context, arg CreateRequestApprovalParams) (ApprovalRequestApproval, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (IdentityRole, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (MasterdataRoom, error)
	CreateThreshold(ctx context.Context, arg CreateThresholdParams) (ApprovalApprovalThreshold, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (TransferAssetTransfer, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (MasterdataUnit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error)
	// Reporting & Dashboard module — read-only aggregates.
	// Every query: deleted_at IS NULL + the standard scope clause
	//   (sqlc.arg(all_scope)::boolean OR office_id = ANY(sqlc.arg(office_ids)::uuid[]))
	// plus an optional narg(office_filter) drill-down (validated against scope in the handler).
	// Money aggregates: COALESCE(SUM(x), 0)::text — never float.
	// Valuation rule: excluded_from_valuation is excluded from money sums, included in counts.
	DashboardAssetKpis(ctx context.Context, arg DashboardAssetKpisParams) (DashboardAssetKpisRow, error)
	DashboardAssetsByCategory(ctx context.Context, arg DashboardAssetsByCategoryParams) ([]DashboardAssetsByCategoryRow, error)
	DashboardAssetsByOffice(ctx context.Context, arg DashboardAssetsByOfficeParams) ([]DashboardAssetsByOfficeRow, error)
	DashboardAssetsByRoom(ctx context.Context, officeID uuid.UUID) ([]DashboardAssetsByRoomRow, error)
	DashboardDepreciationInPeriod(ctx context.Context, arg DashboardDepreciationInPeriodParams) (string, error)
	DashboardMaintenanceCost(ctx context.Context, arg DashboardMaintenanceCostParams) (DashboardMaintenanceCostRow, error)
	DashboardMaintenanceDueCount(ctx context.Context, arg DashboardMaintenanceDueCountParams) (int64, error)
	DashboardMaintenanceDueList(ctx context.Context, arg DashboardMaintenanceDueListParams) ([]DashboardMaintenanceDueListRow, error)
	DashboardOverdueCount(ctx context.Context, arg DashboardOverdueCountParams) (int64, error)
	DecideRequestApproval(ctx context.Context, arg DecideRequestApprovalParams) (ApprovalRequestApproval, error)
	// Regeneration window: everything past the closed watermark up to the target period.
	DeleteEntriesAfterWatermark(ctx context.Context, arg DeleteEntriesAfterWatermarkParams) error
	// First-ever run (no watermark): clear everything ≤ target.
	DeleteEntriesThrough(ctx context.Context, target pgtype.Date) error
	// Outbox-side idempotency for the sweeper's due scan. uq_notif_dedup guards the
	// notifications table, not the outbox: without this guard every sweep tick would
	// enqueue the same reminder again and the relay would faithfully publish each
	// one. The insert and its existence check are ONE statement, so correctness does
	// not rest on the advisory lock alone.
	//
	// Identity is (schedule, due date), read out of the payload -- the same identity
	// as the notification's dedup_key. `deleted_at IS NULL` mirrors uq_notif_dedup's
	// partial predicate so both sides forget at the same retention boundary: a
	// schedule still overdue after its reminder is purged earns a fresh one.
	EnqueueMaintenanceDueOutbox(ctx context.Context, arg EnqueueMaintenanceDueOutboxParams) (int64, error)
	// Outbox: written inside the caller's business transaction, so a rollback leaves
	// no orphan event and a commit can never lose one.
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (NotificationOutbox, error)
	// F3 crash-window fix: an approval request for this import batch may already
	// exist from a prior run that crashed between Submit committing and
	// SetJobRequest persisting the request_id. Look it up by (target_entity,
	// target_id) — backed by idx_requests_target — before submitting again.
	FindActiveImportRequest(ctx context.Context, targetID *uuid.UUID) (uuid.UUID, error)
	// Used by the maintenance module (cross-schema rule): when releasing an asset
	// from under_maintenance, we must know whether an employee still holds it via
	// an active assignment, so it is restored to 'assigned' rather than 'available'.
	GetActiveAssignmentByAsset(ctx context.Context, assetID uuid.UUID) (AssignmentAssignment, error)
	GetAppSetting(ctx context.Context, key string) (string, error)
	GetAsset(ctx context.Context, id uuid.UUID) (AssetAsset, error)
	GetAssetByTag(ctx context.Context, assetTag string) (AssetAsset, error)
	GetAssetDocument(ctx context.Context, id uuid.UUID) (AssetAssetDocument, error)
	// Row-locked read for RecordImpairment's read-modify-write (precedent:
	// approval.sql GetRequestForUpdate): a second concurrent impairment blocks
	// here until the first commits, then re-reads the post-commit book_value/
	// impairment_loss so deltas accumulate instead of clobbering (lost update).
	GetAssetForUpdate(ctx context.Context, id uuid.UUID) (AssetAsset, error)
	GetAssetLabelByID(ctx context.Context, id uuid.UUID) (GetAssetLabelByIDRow, error)
	GetAssetLabelByTag(ctx context.Context, assetTag string) (GetAssetLabelByTagRow, error)
	GetAssignmentEnriched(ctx context.Context, arg GetAssignmentEnrichedParams) (GetAssignmentEnrichedRow, error)
	// Plain (unenriched) row, scoped by the asset's office. Used by Checkin to load +
	// validate state before the update.
	GetAssignmentScoped(ctx context.Context, arg GetAssignmentScopedParams) (AssignmentAssignment, error)
	GetAttachment(ctx context.Context, id uuid.UUID) (AssetAssetAttachment, error)
	// Side-effect-free existence check for the brands importer's Execute
	// anti-poisoning pre-check (uq_brands_name; matched case-insensitively).
	GetBrandByName(ctx context.Context, lower string) (MasterdataBrand, error)
	GetCategory(ctx context.Context, id uuid.UUID) (MasterdataCategory, error)
	GetCategoryCode(ctx context.Context, id uuid.UUID) (*string, error)
	// Fresh, side-effect-free existence check used by the reference importer's
	// Execute anti-poisoning pre-check for cities (cities.code IS uniquely
	// constrained — uq_cities_code — so this pre-check is required, mirroring
	// GetProvinceByCode).
	GetCityByCode(ctx context.Context, code *string) (MasterdataCity, error)
	GetDepreciationPeriod(ctx context.Context, period pgtype.Date) (DepreciationDepreciationPeriod, error)
	// Guard (office-unscoped): at most one live disposal per asset.
	GetDisposalByAsset(ctx context.Context, assetID uuid.UUID) (DisposalDisposal, error)
	// Scoped: caller must have the asset's office in scope (disposals have no office_id).
	// The asset JOIN stays the scope anchor (INNER — a disposal always has a live
	// asset) and doubles as the source of asset_name/asset_tag. LEFT JOINs keep the
	// row visible (with nil names) even when a joined office/user was soft-deleted.
	GetDisposalEnriched(ctx context.Context, arg GetDisposalEnrichedParams) (GetDisposalEnrichedRow, error)
	GetEmployee(ctx context.Context, arg GetEmployeeParams) (MasterdataEmployee, error)
	GetEmployeeByCode(ctx context.Context, code string) (MasterdataEmployee, error)
	GetFloor(ctx context.Context, arg GetFloorParams) (MasterdataFloor, error)
	GetImportJob(ctx context.Context, id uuid.UUID) (ImportImportJob, error)
	GetImportJobForUpdate(ctx context.Context, id uuid.UUID) (ImportImportJob, error)
	GetMaintRecordEnriched(ctx context.Context, arg GetMaintRecordEnrichedParams) (GetMaintRecordEnrichedRow, error)
	GetMaintRecordScoped(ctx context.Context, arg GetMaintRecordScopedParams) (MaintenanceMaintenanceRecord, error)
	GetMaintScheduleScoped(ctx context.Context, arg GetMaintScheduleScopedParams) (MaintenanceMaintenanceSchedule, error)
	// Highest tag_seq for an office, INCLUDING soft-deleted rows (they reserve their
	// number); hard-deleted rows are gone so the top number frees up. NULL -> 0.
	GetMaxTagSeqForOffice(ctx context.Context, officeID uuid.UUID) (int32, error)
	GetModelByBrandAndName(ctx context.Context, arg GetModelByBrandAndNameParams) (MasterdataModel, error)
	GetOffice(ctx context.Context, arg GetOfficeParams) (MasterdataOffice, error)
	GetOfficeAncestors(ctx context.Context, id uuid.UUID) ([]GetOfficeAncestorsRow, error)
	// Fresh, side-effect-free existence check used by the office importer's
	// Execute anti-poisoning pre-check (mirrors GetEmployeeByCode).
	GetOfficeByCode(ctx context.Context, code string) (MasterdataOffice, error)
	GetOfficeCode(ctx context.Context, id uuid.UUID) (string, error)
	// Authorization queries: office subtree (scoping) and field permissions.
	// Returns an office plus all of its descendants (Pusat -> Wilayah -> Cabang -> Outlet).
	GetOfficeSubtree(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// Guard: an asset may have at most one non-terminal transfer row.
	GetOpenTransferForAsset(ctx context.Context, assetID uuid.UUID) (TransferAssetTransfer, error)
	GetOpnameItem(ctx context.Context, arg GetOpnameItemParams) (StockopnameStockOpnameItem, error)
	GetOpnameItemByTag(ctx context.Context, arg GetOpnameItemByTagParams) (StockopnameStockOpnameItem, error)
	GetOpnameSession(ctx context.Context, arg GetOpnameSessionParams) (GetOpnameSessionRow, error)
	// Fresh, side-effect-free existence check used by the reference importer's
	// Execute anti-poisoning pre-check for provinces (mirrors GetEmployeeByCode /
	// GetOfficeByCode).
	GetProvinceByCode(ctx context.Context, code *string) (MasterdataProvince, error)
	GetRequest(ctx context.Context, id uuid.UUID) (ApprovalRequest, error)
	// Enriched read variants: request row + resolved maker/role/office names.
	// LEFT JOINs keep rows visible even when the user/office was soft-deleted.
	GetRequestEnriched(ctx context.Context, id uuid.UUID) (GetRequestEnrichedRow, error)
	GetRequestForUpdate(ctx context.Context, id uuid.UUID) (ApprovalRequest, error)
	GetRole(ctx context.Context, id uuid.UUID) (IdentityRole, error)
	// Identity module queries. Schema-qualified (see DATABASE.md §1.2).
	GetRoleByCode(ctx context.Context, code string) (IdentityRole, error)
	GetRoom(ctx context.Context, arg GetRoomParams) (MasterdataRoom, error)
	// Scoped: caller must have the from- or to-office in scope. Plain (unenriched)
	// row — used internally by Ship/Receive/RejectReceive, which only need the
	// base columns to validate state + perform the update.
	GetTransfer(ctx context.Context, arg GetTransferParams) (TransferAssetTransfer, error)
	// Scoped: caller must have the from- or to-office in scope. Adds resolved
	// asset/office/room/actor display names for the detail view. LEFT JOINs keep
	// the row visible (with nil names) even when a joined entity was soft-deleted.
	GetTransferEnriched(ctx context.Context, arg GetTransferEnrichedParams) (GetTransferEnrichedRow, error)
	GetUnitByName(ctx context.Context, lower string) (MasterdataUnit, error)
	GetUserByEmail(ctx context.Context, email string) (IdentityUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	// Audit log: append-only writes + an office-scoped, filterable read model.
	// all_scope bypasses the office filter (global scope); otherwise only rows whose
	// office_id is in office_ids are returned. NULL-office (global) rows are visible
	// only to all-scope callers.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditAuditLog, error)
	InsertDataScopePolicy(ctx context.Context, arg InsertDataScopePolicyParams) (IdentityDataScopePolicy, error)
	InsertDepreciationEntry(ctx context.Context, arg InsertDepreciationEntryParams) error
	InsertFieldPermission(ctx context.Context, arg InsertFieldPermissionParams) (IdentityFieldPermission, error)
	InsertImportRow(ctx context.Context, arg InsertImportRowParams) (ImportImportRow, error)
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) (IdentityRolePermission, error)
	// (scan reuses assets.sql GetAssetByTag; scope enforced in the service)
	// NOTE: :one + ON CONFLICT DO NOTHING → a conflict returns pgx.ErrNoRows (no row inserted); the caller treats that as "already present".
	InsertUnexpectedItem(ctx context.Context, arg InsertUnexpectedItemParams) (StockopnameStockOpnameItem, error)
	LastClosedPeriod(ctx context.Context) (pgtype.Date, error)
	LastEntryAtOrBefore(ctx context.Context, arg LastEntryAtOrBeforeParams) (DepreciationDepreciationEntry, error)
	LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) error
	ListAssetDocuments(ctx context.Context, assetID uuid.UUID) ([]AssetAssetDocument, error)
	ListAssetEntries(ctx context.Context, assetID uuid.UUID) ([]DepreciationDepreciationEntry, error)
	// All existing (non-deleted) asset tags, used by the asset importer to detect
	// collisions with user-supplied asset_tag values during validation. Asset tags
	// are globally unique, so this set is deliberately unscoped.
	ListAssetTags(ctx context.Context) ([]string, error)
	// Asset core queries (asset.assets + asset.asset_tag_counters).
	// Respects soft delete and caller data scope (all_scope / office_ids).
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]AssetAsset, error)
	// Every capitalized, non-deleted asset with its category (engine resolves/skips per-asset).
	ListAssetsForDepreciation(ctx context.Context) ([]ListAssetsForDepreciationRow, error)
	ListAssignmentsByAssetEnriched(ctx context.Context, arg ListAssignmentsByAssetEnrichedParams) ([]ListAssignmentsByAssetEnrichedRow, error)
	ListAssignmentsEnriched(ctx context.Context, arg ListAssignmentsEnrichedParams) ([]ListAssignmentsEnrichedRow, error)
	ListAttachments(ctx context.Context, assetID uuid.UUID) ([]AssetAssetAttachment, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// id/name lookup: brand-name dedup (brands importer) AND "merek" resolution
	// (models importer). brands.name IS uniquely constrained (uq_brands_name).
	ListBrandsLookup(ctx context.Context) ([]ListBrandsLookupRow, error)
	// Asset category master data (masterdata.categories). Respects soft delete.
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]MasterdataCategory, error)
	// The full non-deleted category set (no pagination) for client-side tree building.
	ListCategoryTree(ctx context.Context) ([]MasterdataCategory, error)
	// Existing (non-deleted) city codes for the cities importer's validate-time
	// dupKode check (mirrors ListProvincesLookup's existingCodes use for
	// provinces) — cities.code IS uniquely constrained (uq_cities_code), so a
	// match here is authoritative, not just an in-file check.
	ListCityCodes(ctx context.Context) ([]*string, error)
	ListDataScopePolicies(ctx context.Context, roleID uuid.UUID) ([]IdentityDataScopePolicy, error)
	// id/name/code lookup for the employee importer's optional "departemen" column
	// (matched by name OR code, case-insensitive).
	ListDepartmentsLookup(ctx context.Context) ([]ListDepartmentsLookupRow, error)
	ListDepreciationPeriods(ctx context.Context) ([]DepreciationDepreciationPeriod, error)
	ListDisposalsByAssetEnriched(ctx context.Context, arg ListDisposalsByAssetEnrichedParams) ([]ListDisposalsByAssetEnrichedRow, error)
	ListDisposalsEnriched(ctx context.Context, arg ListDisposalsEnrichedParams) ([]ListDisposalsEnrichedRow, error)
	// All existing (non-deleted) employee codes, used by the employee importer to
	// detect collisions with user-supplied kode values during validation. Employee
	// codes are globally unique (uq_employees_code), so this set is deliberately
	// unscoped.
	ListEmployeeCodes(ctx context.Context) ([]string, error)
	// Employees (asset custodians) with data-scoping by office.
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]MasterdataEmployee, error)
	// Schedule/journal source: entries of one period+basis joined to asset+category+office.
	// Embeds the full category row (not just name/gl_account_code) so callers can
	// also re-resolve Params (method/life_months) via ResolveCommercial/ResolveFiscal.
	ListEntriesForPeriod(ctx context.Context, arg ListEntriesForPeriodParams) ([]ListEntriesForPeriodRow, error)
	ListFieldPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]ListFieldPermissionsByRoleRow, error)
	// Floors (within an office). Listed per office; single-row ops carry the
	// office scope (all_scope OR office_id = ANY(office_ids)).
	ListFloorsByOffice(ctx context.Context, arg ListFloorsByOfficeParams) ([]MasterdataFloor, error)
	ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]ImportImportJob, error)
	ListImportRows(ctx context.Context, arg ListImportRowsParams) ([]ImportImportRow, error)
	ListInboxCandidates(ctx context.Context) ([]ApprovalRequest, error)
	ListInboxCandidatesEnriched(ctx context.Context) ([]ListInboxCandidatesEnrichedRow, error)
	// Assets flagged under_maintenance (e.g. by assignment check-in) with no active
	// maintenance record — the "Perlu Tindak Lanjut" queue.
	ListMaintAttentionAssets(ctx context.Context, arg ListMaintAttentionAssetsParams) ([]ListMaintAttentionAssetsRow, error)
	ListMaintRecordsByAssetEnriched(ctx context.Context, arg ListMaintRecordsByAssetEnrichedParams) ([]ListMaintRecordsByAssetEnrichedRow, error)
	ListMaintRecordsEnriched(ctx context.Context, arg ListMaintRecordsEnrichedParams) ([]ListMaintRecordsEnrichedRow, error)
	ListMaintSchedulesEnriched(ctx context.Context, arg ListMaintSchedulesEnrichedParams) ([]ListMaintSchedulesEnrichedRow, error)
	// (brand_id, name) pairs for the models importer's composite dupNama check
	// (uq_models_brand_name).
	ListModelsLookup(ctx context.Context) ([]ListModelsLookupRow, error)
	// unread_only and read_only are mutually exclusive flags carrying the tri-state
	// "read" filter: both false means no filter (the whole feed).
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]NotificationNotification, error)
	// Flat id/name lookup for the office importer's "tipe" column. office_types
	// has no code column (only name), so the importer matches by name only.
	ListOfficeTypesLookup(ctx context.Context) ([]ListOfficeTypesLookupRow, error)
	// Offices (hierarchy) with data-scoping. all_scope bypasses the office filter
	// (global scope); otherwise only offices whose id is in office_ids are returned.
	ListOffices(ctx context.Context, arg ListOfficesParams) ([]MasterdataOffice, error)
	// Geo-enriched, scoped office list for the Peta Lokasi screen: resolves
	// office-type/province/city names + a per-office (non-deleted) asset count.
	ListOfficesMap(ctx context.Context, arg ListOfficesMapParams) ([]ListOfficesMapRow, error)
	// Full scoped office set (no pagination) for building the office hierarchy tree
	// client-side. Mirrors ListOffices' scope filter but without LIMIT/OFFSET/search.
	ListOfficesTree(ctx context.Context, arg ListOfficesTreeParams) ([]MasterdataOffice, error)
	ListOpnameItemsEnriched(ctx context.Context, arg ListOpnameItemsEnrichedParams) ([]ListOpnameItemsEnrichedRow, error)
	ListOpnameSessions(ctx context.Context, arg ListOpnameSessionsParams) ([]ListOpnameSessionsRow, error)
	// id/name lookup for the employee importer's optional "jabatan" column
	// (matched by name, case-insensitive). positions has no code column.
	ListPositionsLookup(ctx context.Context) ([]ListPositionsLookupRow, error)
	// Flat id/name/code lookup for the cities importer's "provinsi" column
	// (matched by name OR code, case-insensitive).
	ListProvincesLookup(ctx context.Context) ([]ListProvincesLookupRow, error)
	ListRequestApprovals(ctx context.Context, requestID uuid.UUID) ([]ApprovalRequestApproval, error)
	ListRequestApprovalsEnriched(ctx context.Context, requestID uuid.UUID) ([]ListRequestApprovalsEnrichedRow, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ApprovalRequest, error)
	ListRequestsEnriched(ctx context.Context, arg ListRequestsEnrichedParams) ([]ListRequestsEnrichedRow, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRoles(ctx context.Context) ([]IdentityRole, error)
	// Rooms (within a floor). Scope is derived from the room's floor -> office.
	ListRoomsByFloor(ctx context.Context, arg ListRoomsByFloorParams) ([]MasterdataRoom, error)
	// Flat room lookup (id, name, code, office_id) for the asset importer, scoped
	// to the caller's offices via the room's floor -> office chain. all_scope
	// bypasses the office filter; otherwise only rooms whose office is in office_ids
	// are returned.
	ListRoomsLookup(ctx context.Context, arg ListRoomsLookupParams) ([]ListRoomsLookupRow, error)
	// Unscoped, unlimited sweep for the notification due-reminder job. Distinct from
	// DashboardMaintenanceDueList, which is scope-filtered and hardcodes LIMIT 3 for
	// the dashboard card, so it cannot drive a sweep.
	ListSchedulesDueBetween(ctx context.Context, dueBefore pgtype.Date) ([]ListSchedulesDueBetweenRow, error)
	ListThresholds(ctx context.Context) ([]ApprovalApprovalThreshold, error)
	// Per-asset history, scoped by from- or to-office. Same enrichment as
	// GetTransferEnriched/ListTransfersEnriched.
	ListTransfersByAssetEnriched(ctx context.Context, arg ListTransfersByAssetEnrichedParams) ([]ListTransfersByAssetEnrichedRow, error)
	ListTransfersEnriched(ctx context.Context, arg ListTransfersEnrichedParams) ([]ListTransfersEnrichedRow, error)
	// Existing (non-deleted) unit names for the units importer's dupNama check
	// (uq_units_name).
	ListUnitNames(ctx context.Context) ([]string, error)
	// User management queries (Superadmin). All respect soft delete.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUser, error)
	// The inverse of the request-time permission check: given a permission key, who
	// holds it? Needed to fan notifications out to concrete users, because every
	// other authorization path here answers only "may THIS caller act?".
	// Callers must still apply scope and SoD by running the existing eligibility
	// predicate over each candidate -- deliberately not reimplemented in SQL, or the
	// rules would drift from approval.eligibleToDecide.
	ListUsersWithPermission(ctx context.Context, permissionKey string) ([]ListUsersWithPermissionRow, error)
	ListValidImportRows(ctx context.Context, jobID uuid.UUID) ([]ImportImportRow, error)
	// Vendor master data (masterdata.vendors). Vendors are managed via the generic
	// reference engine; this file holds only bespoke queries needed by other
	// modules.
	// Flat vendor lookup (id, name) for the asset importer. Vendors are not
	// office-scoped, so the full non-deleted set is returned.
	ListVendorsLookup(ctx context.Context) ([]ListVendorsLookupRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	// user_id is part of the predicate, not just the lookup: marking someone else's
	// notification read must affect zero rows (the handler turns that into a 404).
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (NotificationNotification, error)
	// Only ever called after XADD succeeds: an unpublished row is retried next tick
	// rather than lost.
	MarkOutboxPublished(ctx context.Context, id uuid.UUID) error
	MarkRowFailed(ctx context.Context, arg MarkRowFailedParams) error
	MarkRowResult(ctx context.Context, arg MarkRowResultParams) error
	// Approval / maker-checker queries (approval schema).
	// See docs/DATABASE.md §4.5 and PRD §3.6 for schema context.
	MatchThresholdSteps(ctx context.Context, arg MatchThresholdStepsParams) ([]ApprovalApprovalThreshold, error)
	// Retention purge. Soft delete keeps the convention; because every index is
	// partial on deleted_at IS NULL, purged rows leave the indexes entirely, so the
	// feed and unread count stay fast however large the table grows.
	PurgeNotifications(ctx context.Context, cutoff pgtype.Timestamptz) error
	PurgeOutbox(ctx context.Context, cutoff pgtype.Timestamptz) error
	RecoverStuckJobs(ctx context.Context) (int64, error)
	// book value per category (top 8)
	ReportAssetChart(ctx context.Context, arg ReportAssetChartParams) ([]ReportAssetChartRow, error)
	// ══════════════════════════════════════════════════════════════════════════
	// Report builder — assets / depreciation / utilization / maintenance.
	// Every query shares the standard filter block on the assets alias `a`:
	//   scope (all_scope OR office_id = ANY(office_ids))
	//   + optional narg(office_filter) drill-down
	//   + optional narg(category_id).
	// Money aggregates: COALESCE(SUM(x), 0)::text — never float.
	// Valuation rule (assets report): excluded_from_valuation is dropped from money
	// sums (Totals/KPIs/chart) but the rows still list every asset.
	// ══════════════════════════════════════════════════════════════════════════
	ReportAssetRows(ctx context.Context, arg ReportAssetRowsParams) ([]ReportAssetRowsRow, error)
	ReportAssetTotals(ctx context.Context, arg ReportAssetTotalsParams) (ReportAssetTotalsRow, error)
	ReportDepreciationKpis(ctx context.Context, arg ReportDepreciationKpisParams) (ReportDepreciationKpisRow, error)
	// sum of each asset's last closing_value <= date_to
	ReportDepreciationRemaining(ctx context.Context, arg ReportDepreciationRemainingParams) (string, error)
	ReportDepreciationRows(ctx context.Context, arg ReportDepreciationRowsParams) ([]ReportDepreciationRowsRow, error)
	// net gain/loss per disposal method
	ReportDisposalChart(ctx context.Context, arg ReportDisposalChartParams) ([]ReportDisposalChartRow, error)
	ReportDisposalKpis(ctx context.Context, arg ReportDisposalKpisParams) (ReportDisposalKpisRow, error)
	ReportDisposalRows(ctx context.Context, arg ReportDisposalRowsParams) ([]ReportDisposalRowsRow, error)
	// cost per category (top 8)
	ReportMaintenanceChart(ctx context.Context, arg ReportMaintenanceChartParams) ([]ReportMaintenanceChartRow, error)
	ReportMaintenanceKpis(ctx context.Context, arg ReportMaintenanceKpisParams) (ReportMaintenanceKpisRow, error)
	ReportMaintenanceRows(ctx context.Context, arg ReportMaintenanceRowsParams) ([]ReportMaintenanceRowsRow, error)
	ReportOpnameSessions(ctx context.Context, arg ReportOpnameSessionsParams) ([]ReportOpnameSessionsRow, error)
	// transfer count per destination office (top 8)
	ReportTransferChart(ctx context.Context, arg ReportTransferChartParams) ([]ReportTransferChartRow, error)
	ReportTransferKpis(ctx context.Context, arg ReportTransferKpisParams) (ReportTransferKpisRow, error)
	// ══════════════════════════════════════════════════════════════════════════
	// Report builder — transfers / disposals (+ GL recap) / opname (Task 6).
	// transfers scope: from OR to office in scope (an inbound mutasi is visible to
	// the destination office). disposals/opname scope on the owning asset/session
	// office. Money aggregates: COALESCE(SUM(x), 0)::text — never float.
	// ══════════════════════════════════════════════════════════════════════════
	ReportTransferRows(ctx context.Context, arg ReportTransferRowsParams) ([]ReportTransferRowsRow, error)
	ReportUtilizationKpis(ctx context.Context, arg ReportUtilizationKpisParams) (int64, error)
	ReportUtilizationRows(ctx context.Context, arg ReportUtilizationRowsParams) ([]ReportUtilizationRowsRow, error)
	// Unfiltered KPI tiles (period + basis + scope only — table filters must never
	// shrink the tiles). Same FROM/WHERE as ScheduleTotals MINUS the search/
	// category/office filters.
	ScheduleKpi(ctx context.Context, arg ScheduleKpiParams) (ScheduleKpiRow, error)
	// One asset-based, paginated schedule page. A row is included if it has an
	// entry for this period+basis (entry row) OR the asset is a parameterizable
	// "union" row (fully depreciated, no entry this period). The parameterizable
	// predicate mirrors ResolveCommercial/ResolveFiscal's Skip checks in SQL.
	//
	// SYNC WARNING: this WHERE clause is a hand-maintained re-derivation of
	// internal/depreciation/engine.go's Skip logic — disposed/not_capitalized/
	// no_cost/no_purchase_date map 1:1 to a.status/a.capitalized/a.purchase_cost/
	// a.purchase_date above, and missing_params/non_susut map to the
	// is_commercial branch's method+life / fiscal_group checks. There is no
	// shared source of truth between Go and SQL, so any new Skip reason added to
	// ResolveCommercial/ResolveFiscal (or a new shared.fiscal_asset_group enum
	// value without a FiscalRules entry) must be mirrored here explicitly, or a
	// disposed/skip asset can silently reappear as a "fully depreciated" row (or
	// vice versa). The identical predicate is duplicated in ScheduleTotals and
	// ScheduleKpi below — keep all three in lockstep.
	ScheduleRows(ctx context.Context, arg ScheduleRowsParams) ([]ScheduleRowsRow, error)
	// Filtered tfoot totals + row count (same FROM/WHERE as ScheduleRows, incl.
	// the search/category/office filters, no pagination).
	ScheduleTotals(ctx context.Context, arg ScheduleTotalsParams) (ScheduleTotalsRow, error)
	// Global search (command palette). Each query returns the top matches for one
	// entity plus the full match count via a window function. Callers gate by
	// permission + data scope; queries only enforce the office scope filter.
	SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]SearchAssetsRow, error)
	SearchEmployees(ctx context.Context, arg SearchEmployeesParams) ([]SearchEmployeesRow, error)
	SearchOffices(ctx context.Context, arg SearchOfficesParams) ([]SearchOfficesRow, error)
	SearchRequests(ctx context.Context, arg SearchRequestsParams) ([]SearchRequestsRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SessionKpis(ctx context.Context, sessionID uuid.UUID) (SessionKpisRow, error)
	SetAssetDocumentObjectKey(ctx context.Context, arg SetAssetDocumentObjectKeyParams) (AssetAssetDocument, error)
	// Relocate an asset to a new office/room (used by the transfer receive step).
	SetAssetOffice(ctx context.Context, arg SetAssetOfficeParams) (AssetAsset, error)
	SetAssetStatus(ctx context.Context, arg SetAssetStatusParams) (AssetAsset, error)
	SetAssetValuationExclusion(ctx context.Context, arg SetAssetValuationExclusionParams) (AssetAsset, error)
	SetDisposalBastNo(ctx context.Context, arg SetDisposalBastNoParams) (DisposalDisposal, error)
	SetItemFollowup(ctx context.Context, arg SetItemFollowupParams) (StockopnameStockOpnameItem, error)
	SetItemFollowupRecord(ctx context.Context, arg SetItemFollowupRecordParams) (StockopnameStockOpnameItem, error)
	SetJobErrorReportKey(ctx context.Context, arg SetJobErrorReportKeyParams) error
	SetJobRequest(ctx context.Context, arg SetJobRequestParams) (ImportImportJob, error)
	SetJobResult(ctx context.Context, arg SetJobResultParams) (ImportImportJob, error)
	SetJobValidated(ctx context.Context, arg SetJobValidatedParams) (ImportImportJob, error)
	SetOpnameItemResult(ctx context.Context, arg SetOpnameItemResultParams) (StockopnameStockOpnameItem, error)
	SetPeriodClosed(ctx context.Context, arg SetPeriodClosedParams) (DepreciationDepreciationPeriod, error)
	SetRequestDecision(ctx context.Context, arg SetRequestDecisionParams) (ApprovalRequest, error)
	SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) (StockopnameStockOpnameSession, error)
	SetTransferReceived(ctx context.Context, arg SetTransferReceivedParams) (TransferAssetTransfer, error)
	// Receiving side declines the shipment: terminal 'returned', asset never moved.
	SetTransferReturned(ctx context.Context, arg SetTransferReturnedParams) (TransferAssetTransfer, error)
	SetTransferShipped(ctx context.Context, arg SetTransferShippedParams) (TransferAssetTransfer, error)
	SnapshotSessionItems(ctx context.Context, arg SnapshotSessionItemsParams) error
	SoftDeleteAssetDocument(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteAttachment(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteCategory(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteDataScopePoliciesByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) (int64, error)
	SoftDeleteFieldPermissionsByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	SoftDeleteFloor(ctx context.Context, arg SoftDeleteFloorParams) (int64, error)
	SoftDeleteMaintSchedule(ctx context.Context, id uuid.UUID) (int64, error)
	// Auto-resolve: a notification whose turn has passed is soft-deleted, not just
	// marked read -- it cannot be acted on, so it should not sit in the feed.
	// Clears exactly one step. Every recipient of a step shares the same dedup_key
	// (only user_id differs), so an exact match already sweeps all of them.
	// Prefer this over the prefix form whenever a single step is meant: the prefix
	// 'request:<id>:step:1' also matches step:10, step:11, ...
	SoftDeleteNotificationsByDedupKey(ctx context.Context, dedupKey *string) error
	// Prefix form, for sweeping every step of a request at once. Callers must pass
	// a prefix that cannot straddle a boundary -- 'request:<id>:step:' with the
	// trailing colon, never 'request:<id>:step:<n>'. The keys carry no LIKE
	// metacharacter (no '%' or '_'), so no escaping is needed.
	SoftDeleteNotificationsByDedupPrefix(ctx context.Context, prefix *string) error
	SoftDeleteOffice(ctx context.Context, arg SoftDeleteOfficeParams) (int64, error)
	SoftDeleteRole(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteRolePermissionsByRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (int64, error)
	SoftDeleteThreshold(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	SumAssetAmounts(ctx context.Context, arg SumAssetAmountsParams) (string, error)
	TouchMaintScheduleDone(ctx context.Context, arg TouchMaintScheduleDoneParams) (MaintenanceMaintenanceSchedule, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (AssetAsset, error)
	UpdateAssetDepreciationSummary(ctx context.Context, arg UpdateAssetDepreciationSummaryParams) error
	UpdateAssetDocument(ctx context.Context, arg UpdateAssetDocumentParams) (AssetAssetDocument, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MasterdataCategory, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (MasterdataEmployee, error)
	UpdateEmployeePhone(ctx context.Context, arg UpdateEmployeePhoneParams) error
	UpdateFloor(ctx context.Context, arg UpdateFloorParams) (MasterdataFloor, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (ImportImportJob, error)
	UpdateMaintRecord(ctx context.Context, arg UpdateMaintRecordParams) (MaintenanceMaintenanceRecord, error)
	UpdateMaintSchedule(ctx context.Context, arg UpdateMaintScheduleParams) (MaintenanceMaintenanceSchedule, error)
	UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (MasterdataOffice, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (IdentityRole, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (MasterdataRoom, error)
	UpdateThreshold(ctx context.Context, arg UpdateThresholdParams) (ApprovalApprovalThreshold, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (IdentityUser, error)
	UpdateUserAvatarKey(ctx context.Context, arg UpdateUserAvatarKeyParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (IdentityUser, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (IdentityUser, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// The DO UPDATE's WHERE guard makes a closed period unmatchable (0 rows →
	// pgx.ErrNoRows): even if a ComputePeriod raced past its status pre-check, it
	// can never flip a closed period back to 'computed'. The service maps that
	// ErrNoRows to ErrPeriodClosed and rolls back the regenerated entries.
	UpsertPeriodComputed(ctx context.Context, arg UpsertPeriodComputedParams) (DepreciationDepreciationPeriod, error)
}

var _ Querier = (*Queries)(nil)
