// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference_import.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO masterdata.brands (name) VALUES ($1) RETURNING id, name, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (MasterdataBrand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i MasterdataBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO masterdata.cities (province_id, name, code) VALUES ($1, $2, $3)
RETURNING id, province_id, name, code, created_at, updated_at, deleted_at
`

type CreateCityParams struct {
	ProvinceID uuid.UUID `json:"province_id"`
	Name       string    `json:"name"`
	Code       *string   `json:"code"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (MasterdataCity, error) {
	row := q.db.QueryRow(ctx, createCity, arg.ProvinceID, arg.Name, arg.Code)
	var i MasterdataCity
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProvince = `-- name: CreateProvince :one

INSERT INTO masterdata.provinces (name, code) VALUES ($1, $2)
RETURNING id, name, code, created_at, updated_at, deleted_at
`

type CreateProvinceParams struct {
	Name string  `json:"name"`
	Code *string `json:"code"`
}

// Dedicated queries for the reference-target bulk importer (provinces, cities).
// These exist alongside the generic reference engine (internal/masterdata/reference/engine.go)
// because the engine operates on a *pgxpool.Pool directly and cannot join the
// import worker's sqlc transaction (target.Execute receives a tx-bound
// *sqlc.Queries). See internal/masterdata/reference/importer.go.
func (q *Queries) CreateProvince(ctx context.Context, arg CreateProvinceParams) (MasterdataProvince, error) {
	row := q.db.QueryRow(ctx, createProvince, arg.Name, arg.Code)
	var i MasterdataProvince
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO masterdata.units (name, symbol) VALUES ($1, $2) RETURNING id, name, symbol, is_active, created_at, updated_at, deleted_at
`

type CreateUnitParams struct {
	Name   string  `json:"name"`
	Symbol *string `json:"symbol"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (MasterdataUnit, error) {
	row := q.db.QueryRow(ctx, createUnit, arg.Name, arg.Symbol)
	var i MasterdataUnit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBrandByName = `-- name: GetBrandByName :one
SELECT id, name, is_active, created_at, updated_at, deleted_at FROM masterdata.brands WHERE lower(name) = lower($1) AND deleted_at IS NULL LIMIT 1
`

// Side-effect-free existence check for the brands importer's Execute
// anti-poisoning pre-check (uq_brands_name; matched case-insensitively).
func (q *Queries) GetBrandByName(ctx context.Context, lower string) (MasterdataBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByName, lower)
	var i MasterdataBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCityByCode = `-- name: GetCityByCode :one
SELECT id, province_id, name, code, created_at, updated_at, deleted_at FROM masterdata.cities WHERE code = $1 AND deleted_at IS NULL LIMIT 1
`

// Fresh, side-effect-free existence check used by the reference importer's
// Execute anti-poisoning pre-check for cities (cities.code IS uniquely
// constrained — uq_cities_code — so this pre-check is required, mirroring
// GetProvinceByCode).
func (q *Queries) GetCityByCode(ctx context.Context, code *string) (MasterdataCity, error) {
	row := q.db.QueryRow(ctx, getCityByCode, code)
	var i MasterdataCity
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProvinceByCode = `-- name: GetProvinceByCode :one
SELECT id, name, code, created_at, updated_at, deleted_at FROM masterdata.provinces WHERE code = $1 AND deleted_at IS NULL LIMIT 1
`

// Fresh, side-effect-free existence check used by the reference importer's
// Execute anti-poisoning pre-check for provinces (mirrors GetEmployeeByCode /
// GetOfficeByCode).
func (q *Queries) GetProvinceByCode(ctx context.Context, code *string) (MasterdataProvince, error) {
	row := q.db.QueryRow(ctx, getProvinceByCode, code)
	var i MasterdataProvince
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUnitByName = `-- name: GetUnitByName :one
SELECT id, name, symbol, is_active, created_at, updated_at, deleted_at FROM masterdata.units WHERE lower(name) = lower($1) AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUnitByName(ctx context.Context, lower string) (MasterdataUnit, error) {
	row := q.db.QueryRow(ctx, getUnitByName, lower)
	var i MasterdataUnit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBrandsLookup = `-- name: ListBrandsLookup :many
SELECT id, name FROM masterdata.brands WHERE deleted_at IS NULL
`

type ListBrandsLookupRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// id/name lookup: brand-name dedup (brands importer) AND "merek" resolution
// (models importer). brands.name IS uniquely constrained (uq_brands_name).
func (q *Queries) ListBrandsLookup(ctx context.Context) ([]ListBrandsLookupRow, error) {
	rows, err := q.db.Query(ctx, listBrandsLookup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrandsLookupRow{}
	for rows.Next() {
		var i ListBrandsLookupRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCityCodes = `-- name: ListCityCodes :many
SELECT code FROM masterdata.cities WHERE code IS NOT NULL AND deleted_at IS NULL
`

// Existing (non-deleted) city codes for the cities importer's validate-time
// dupKode check (mirrors ListProvincesLookup's existingCodes use for
// provinces) — cities.code IS uniquely constrained (uq_cities_code), so a
// match here is authoritative, not just an in-file check.
func (q *Queries) ListCityCodes(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, listCityCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var code *string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartmentsLookup = `-- name: ListDepartmentsLookup :many
SELECT id, name, code FROM masterdata.departments WHERE deleted_at IS NULL
`

type ListDepartmentsLookupRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Code *string   `json:"code"`
}

// id/name/code lookup for the employee importer's optional "departemen" column
// (matched by name OR code, case-insensitive).
func (q *Queries) ListDepartmentsLookup(ctx context.Context) ([]ListDepartmentsLookupRow, error) {
	rows, err := q.db.Query(ctx, listDepartmentsLookup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsLookupRow{}
	for rows.Next() {
		var i ListDepartmentsLookupRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsLookup = `-- name: ListPositionsLookup :many
SELECT id, name FROM masterdata.positions WHERE deleted_at IS NULL
`

type ListPositionsLookupRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// id/name lookup for the employee importer's optional "jabatan" column
// (matched by name, case-insensitive). positions has no code column.
func (q *Queries) ListPositionsLookup(ctx context.Context) ([]ListPositionsLookupRow, error) {
	rows, err := q.db.Query(ctx, listPositionsLookup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsLookupRow{}
	for rows.Next() {
		var i ListPositionsLookupRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvincesLookup = `-- name: ListProvincesLookup :many
SELECT id, name, code FROM masterdata.provinces WHERE deleted_at IS NULL
`

type ListProvincesLookupRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Code *string   `json:"code"`
}

// Flat id/name/code lookup for the cities importer's "provinsi" column
// (matched by name OR code, case-insensitive).
func (q *Queries) ListProvincesLookup(ctx context.Context) ([]ListProvincesLookupRow, error) {
	rows, err := q.db.Query(ctx, listProvincesLookup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProvincesLookupRow{}
	for rows.Next() {
		var i ListProvincesLookupRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitNames = `-- name: ListUnitNames :many
SELECT name FROM masterdata.units WHERE deleted_at IS NULL
`

// Existing (non-deleted) unit names for the units importer's dupNama check
// (uq_units_name).
func (q *Queries) ListUnitNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnitNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
