// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countRoomsByFloor = `-- name: CountRoomsByFloor :one
SELECT count(*) FROM masterdata.rooms
WHERE deleted_at IS NULL AND floor_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%' OR coalesce(code, '') ILIKE '%' || $2 || '%')
`

type CountRoomsByFloorParams struct {
	FloorID uuid.UUID `json:"floor_id"`
	Search  string    `json:"search"`
}

func (q *Queries) CountRoomsByFloor(ctx context.Context, arg CountRoomsByFloorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomsByFloor, arg.FloorID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO masterdata.rooms (floor_id, name, code)
VALUES ($1, $2, $3)
RETURNING id, floor_id, name, code, created_at, updated_at, deleted_at
`

type CreateRoomParams struct {
	FloorID uuid.UUID `json:"floor_id"`
	Name    string    `json:"name"`
	Code    *string   `json:"code"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (MasterdataRoom, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.FloorID, arg.Name, arg.Code)
	var i MasterdataRoom
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT r.id, r.floor_id, r.name, r.code, r.created_at, r.updated_at, r.deleted_at FROM masterdata.rooms r
JOIN masterdata.floors f ON f.id = r.floor_id
WHERE r.id = $1 AND r.deleted_at IS NULL
  AND ($2::bool OR f.office_id = ANY($3::uuid[]))
`

type GetRoomParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) GetRoom(ctx context.Context, arg GetRoomParams) (MasterdataRoom, error) {
	row := q.db.QueryRow(ctx, getRoom, arg.ID, arg.AllScope, arg.OfficeIds)
	var i MasterdataRoom
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRoomsByFloor = `-- name: ListRoomsByFloor :many

SELECT id, floor_id, name, code, created_at, updated_at, deleted_at FROM masterdata.rooms
WHERE deleted_at IS NULL AND floor_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%' OR coalesce(code, '') ILIKE '%' || $2 || '%')
ORDER BY name
LIMIT $4 OFFSET $3
`

type ListRoomsByFloorParams struct {
	FloorID uuid.UUID `json:"floor_id"`
	Search  string    `json:"search"`
	Off     int32     `json:"off"`
	Lim     int32     `json:"lim"`
}

// Rooms (within a floor). Scope is derived from the room's floor -> office.
func (q *Queries) ListRoomsByFloor(ctx context.Context, arg ListRoomsByFloorParams) ([]MasterdataRoom, error) {
	rows, err := q.db.Query(ctx, listRoomsByFloor,
		arg.FloorID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterdataRoom{}
	for rows.Next() {
		var i MasterdataRoom
		if err := rows.Scan(
			&i.ID,
			&i.FloorID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsLookup = `-- name: ListRoomsLookup :many
SELECT r.id, r.name, r.code, f.office_id
FROM masterdata.rooms r
JOIN masterdata.floors f ON f.id = r.floor_id AND f.deleted_at IS NULL
WHERE r.deleted_at IS NULL
  AND ($1::bool OR f.office_id = ANY($2::uuid[]))
ORDER BY r.name
`

type ListRoomsLookupParams struct {
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

type ListRoomsLookupRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Code     *string   `json:"code"`
	OfficeID uuid.UUID `json:"office_id"`
}

// Flat room lookup (id, name, code, office_id) for the asset importer, scoped
// to the caller's offices via the room's floor -> office chain. all_scope
// bypasses the office filter; otherwise only rooms whose office is in office_ids
// are returned.
func (q *Queries) ListRoomsLookup(ctx context.Context, arg ListRoomsLookupParams) ([]ListRoomsLookupRow, error) {
	rows, err := q.db.Query(ctx, listRoomsLookup, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsLookupRow{}
	for rows.Next() {
		var i ListRoomsLookupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRoom = `-- name: SoftDeleteRoom :execrows
UPDATE masterdata.rooms SET deleted_at = now()
WHERE rooms.id = $1 AND rooms.deleted_at IS NULL
  AND (
    $2::bool
    OR (SELECT f.office_id FROM masterdata.floors f WHERE f.id = rooms.floor_id) = ANY($3::uuid[])
  )
`

type SoftDeleteRoomParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRoom, arg.ID, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE masterdata.rooms
SET floor_id = $1, name = $2, code = $3
WHERE rooms.id = $4 AND rooms.deleted_at IS NULL
  AND (
    $5::bool
    OR (SELECT f.office_id FROM masterdata.floors f WHERE f.id = rooms.floor_id) = ANY($6::uuid[])
  )
RETURNING id, floor_id, name, code, created_at, updated_at, deleted_at
`

type UpdateRoomParams struct {
	FloorID   uuid.UUID   `json:"floor_id"`
	Name      string      `json:"name"`
	Code      *string     `json:"code"`
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (MasterdataRoom, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.FloorID,
		arg.Name,
		arg.Code,
		arg.ID,
		arg.AllScope,
		arg.OfficeIds,
	)
	var i MasterdataRoom
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
