// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stockopname.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOpnameSessions = `-- name: CountOpnameSessions :one
SELECT count(*)
FROM stockopname.stock_opname_sessions s
WHERE s.deleted_at IS NULL
  AND ($1::boolean OR s.office_id = ANY($2::uuid[]))
  AND ($3::shared.opname_session_status IS NULL OR s.status = $3)
`

type CountOpnameSessionsParams struct {
	AllScope  bool                       `json:"all_scope"`
	OfficeIds []uuid.UUID                `json:"office_ids"`
	Status    *SharedOpnameSessionStatus `json:"status"`
}

func (q *Queries) CountOpnameSessions(ctx context.Context, arg CountOpnameSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpnameSessions, arg.AllScope, arg.OfficeIds, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOpnameSession = `-- name: CreateOpnameSession :one
INSERT INTO stockopname.stock_opname_sessions (office_id, name, period, started_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, office_id, name, period, status, started_by_id, started_at, closed_by_id, closed_at, created_at, updated_at, deleted_at
`

type CreateOpnameSessionParams struct {
	OfficeID    uuid.UUID   `json:"office_id"`
	Name        *string     `json:"name"`
	Period      pgtype.Date `json:"period"`
	StartedByID uuid.UUID   `json:"started_by_id"`
}

func (q *Queries) CreateOpnameSession(ctx context.Context, arg CreateOpnameSessionParams) (StockopnameStockOpnameSession, error) {
	row := q.db.QueryRow(ctx, createOpnameSession,
		arg.OfficeID,
		arg.Name,
		arg.Period,
		arg.StartedByID,
	)
	var i StockopnameStockOpnameSession
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Period,
		&i.Status,
		&i.StartedByID,
		&i.StartedAt,
		&i.ClosedByID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOpnameItem = `-- name: GetOpnameItem :one
SELECT id, session_id, asset_id, expected, result, counted_by_id, counted_at, note, created_at, updated_at, deleted_at, followup_request_id, followup_record_id FROM stockopname.stock_opname_items
WHERE id = $1 AND session_id = $2 AND deleted_at IS NULL
`

type GetOpnameItemParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) GetOpnameItem(ctx context.Context, arg GetOpnameItemParams) (StockopnameStockOpnameItem, error) {
	row := q.db.QueryRow(ctx, getOpnameItem, arg.ID, arg.SessionID)
	var i StockopnameStockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AssetID,
		&i.Expected,
		&i.Result,
		&i.CountedByID,
		&i.CountedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FollowupRequestID,
		&i.FollowupRecordID,
	)
	return i, err
}

const getOpnameItemByTag = `-- name: GetOpnameItemByTag :one
SELECT it.id, it.session_id, it.asset_id, it.expected, it.result, it.counted_by_id, it.counted_at, it.note, it.created_at, it.updated_at, it.deleted_at, it.followup_request_id, it.followup_record_id FROM stockopname.stock_opname_items it
JOIN asset.assets a ON a.id = it.asset_id
WHERE it.session_id = $1 AND it.deleted_at IS NULL
  AND a.asset_tag = $2
`

type GetOpnameItemByTagParams struct {
	SessionID uuid.UUID `json:"session_id"`
	AssetTag  string    `json:"asset_tag"`
}

func (q *Queries) GetOpnameItemByTag(ctx context.Context, arg GetOpnameItemByTagParams) (StockopnameStockOpnameItem, error) {
	row := q.db.QueryRow(ctx, getOpnameItemByTag, arg.SessionID, arg.AssetTag)
	var i StockopnameStockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AssetID,
		&i.Expected,
		&i.Result,
		&i.CountedByID,
		&i.CountedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FollowupRequestID,
		&i.FollowupRecordID,
	)
	return i, err
}

const getOpnameSession = `-- name: GetOpnameSession :one
SELECT s.id, s.office_id, s.name, s.period, s.status, s.started_by_id, s.started_at, s.closed_by_id, s.closed_at, s.created_at, s.updated_at, s.deleted_at, o.name AS office_name,
       su.name AS started_by_name, cu.name AS closed_by_name
FROM stockopname.stock_opname_sessions s
LEFT JOIN masterdata.offices o ON o.id = s.office_id AND o.deleted_at IS NULL
LEFT JOIN identity.users su ON su.id = s.started_by_id AND su.deleted_at IS NULL
LEFT JOIN identity.users cu ON cu.id = s.closed_by_id AND cu.deleted_at IS NULL
WHERE s.id = $1 AND s.deleted_at IS NULL
  AND ($2::boolean OR s.office_id = ANY($3::uuid[]))
`

type GetOpnameSessionParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

type GetOpnameSessionRow struct {
	StockopnameStockOpnameSession StockopnameStockOpnameSession `json:"stockopname_stock_opname_session"`
	OfficeName                    *string                       `json:"office_name"`
	StartedByName                 *string                       `json:"started_by_name"`
	ClosedByName                  *string                       `json:"closed_by_name"`
}

func (q *Queries) GetOpnameSession(ctx context.Context, arg GetOpnameSessionParams) (GetOpnameSessionRow, error) {
	row := q.db.QueryRow(ctx, getOpnameSession, arg.ID, arg.AllScope, arg.OfficeIds)
	var i GetOpnameSessionRow
	err := row.Scan(
		&i.StockopnameStockOpnameSession.ID,
		&i.StockopnameStockOpnameSession.OfficeID,
		&i.StockopnameStockOpnameSession.Name,
		&i.StockopnameStockOpnameSession.Period,
		&i.StockopnameStockOpnameSession.Status,
		&i.StockopnameStockOpnameSession.StartedByID,
		&i.StockopnameStockOpnameSession.StartedAt,
		&i.StockopnameStockOpnameSession.ClosedByID,
		&i.StockopnameStockOpnameSession.ClosedAt,
		&i.StockopnameStockOpnameSession.CreatedAt,
		&i.StockopnameStockOpnameSession.UpdatedAt,
		&i.StockopnameStockOpnameSession.DeletedAt,
		&i.OfficeName,
		&i.StartedByName,
		&i.ClosedByName,
	)
	return i, err
}

const insertUnexpectedItem = `-- name: InsertUnexpectedItem :one

INSERT INTO stockopname.stock_opname_items (session_id, asset_id, expected, result)
VALUES ($1, $2, false, 'pending')
ON CONFLICT (session_id, asset_id) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, session_id, asset_id, expected, result, counted_by_id, counted_at, note, created_at, updated_at, deleted_at, followup_request_id, followup_record_id
`

type InsertUnexpectedItemParams struct {
	SessionID uuid.UUID `json:"session_id"`
	AssetID   uuid.UUID `json:"asset_id"`
}

// (scan reuses assets.sql GetAssetByTag; scope enforced in the service)
// NOTE: :one + ON CONFLICT DO NOTHING → a conflict returns pgx.ErrNoRows (no row inserted); the caller treats that as "already present".
func (q *Queries) InsertUnexpectedItem(ctx context.Context, arg InsertUnexpectedItemParams) (StockopnameStockOpnameItem, error) {
	row := q.db.QueryRow(ctx, insertUnexpectedItem, arg.SessionID, arg.AssetID)
	var i StockopnameStockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AssetID,
		&i.Expected,
		&i.Result,
		&i.CountedByID,
		&i.CountedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FollowupRequestID,
		&i.FollowupRecordID,
	)
	return i, err
}

const listOpnameItemsEnriched = `-- name: ListOpnameItemsEnriched :many
SELECT it.id, it.session_id, it.asset_id, it.expected, it.result, it.counted_by_id, it.counted_at, it.note, it.created_at, it.updated_at, it.deleted_at, it.followup_request_id, it.followup_record_id, a.name AS asset_name, a.asset_tag AS asset_tag,
       o.name AS office_name, rm.name AS room_name, fl.name AS floor_name,
       cu.name AS counted_by_name
FROM stockopname.stock_opname_items it
LEFT JOIN asset.assets a ON a.id = it.asset_id AND a.deleted_at IS NULL
LEFT JOIN masterdata.offices o ON o.id = a.office_id AND o.deleted_at IS NULL
LEFT JOIN masterdata.rooms rm ON rm.id = a.room_id AND rm.deleted_at IS NULL
LEFT JOIN masterdata.floors fl ON fl.id = rm.floor_id AND fl.deleted_at IS NULL
LEFT JOIN identity.users cu ON cu.id = it.counted_by_id AND cu.deleted_at IS NULL
WHERE it.session_id = $1 AND it.deleted_at IS NULL
  AND ($2::shared.opname_item_result IS NULL OR it.result = $2)
ORDER BY a.name
`

type ListOpnameItemsEnrichedParams struct {
	SessionID uuid.UUID               `json:"session_id"`
	Result    *SharedOpnameItemResult `json:"result"`
}

type ListOpnameItemsEnrichedRow struct {
	StockopnameStockOpnameItem StockopnameStockOpnameItem `json:"stockopname_stock_opname_item"`
	AssetName                  *string                    `json:"asset_name"`
	AssetTag                   *string                    `json:"asset_tag"`
	OfficeName                 *string                    `json:"office_name"`
	RoomName                   *string                    `json:"room_name"`
	FloorName                  *string                    `json:"floor_name"`
	CountedByName              *string                    `json:"counted_by_name"`
}

func (q *Queries) ListOpnameItemsEnriched(ctx context.Context, arg ListOpnameItemsEnrichedParams) ([]ListOpnameItemsEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listOpnameItemsEnriched, arg.SessionID, arg.Result)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpnameItemsEnrichedRow{}
	for rows.Next() {
		var i ListOpnameItemsEnrichedRow
		if err := rows.Scan(
			&i.StockopnameStockOpnameItem.ID,
			&i.StockopnameStockOpnameItem.SessionID,
			&i.StockopnameStockOpnameItem.AssetID,
			&i.StockopnameStockOpnameItem.Expected,
			&i.StockopnameStockOpnameItem.Result,
			&i.StockopnameStockOpnameItem.CountedByID,
			&i.StockopnameStockOpnameItem.CountedAt,
			&i.StockopnameStockOpnameItem.Note,
			&i.StockopnameStockOpnameItem.CreatedAt,
			&i.StockopnameStockOpnameItem.UpdatedAt,
			&i.StockopnameStockOpnameItem.DeletedAt,
			&i.StockopnameStockOpnameItem.FollowupRequestID,
			&i.StockopnameStockOpnameItem.FollowupRecordID,
			&i.AssetName,
			&i.AssetTag,
			&i.OfficeName,
			&i.RoomName,
			&i.FloorName,
			&i.CountedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpnameSessions = `-- name: ListOpnameSessions :many
SELECT s.id, s.office_id, s.name, s.period, s.status, s.started_by_id, s.started_at, s.closed_by_id, s.closed_at, s.created_at, s.updated_at, s.deleted_at, o.name AS office_name
FROM stockopname.stock_opname_sessions s
LEFT JOIN masterdata.offices o ON o.id = s.office_id AND o.deleted_at IS NULL
WHERE s.deleted_at IS NULL
  AND ($1::boolean OR s.office_id = ANY($2::uuid[]))
  AND ($3::shared.opname_session_status IS NULL OR s.status = $3)
ORDER BY s.created_at DESC
LIMIT $5 OFFSET $4
`

type ListOpnameSessionsParams struct {
	AllScope  bool                       `json:"all_scope"`
	OfficeIds []uuid.UUID                `json:"office_ids"`
	Status    *SharedOpnameSessionStatus `json:"status"`
	Off       int32                      `json:"off"`
	Lim       int32                      `json:"lim"`
}

type ListOpnameSessionsRow struct {
	StockopnameStockOpnameSession StockopnameStockOpnameSession `json:"stockopname_stock_opname_session"`
	OfficeName                    *string                       `json:"office_name"`
}

func (q *Queries) ListOpnameSessions(ctx context.Context, arg ListOpnameSessionsParams) ([]ListOpnameSessionsRow, error) {
	rows, err := q.db.Query(ctx, listOpnameSessions,
		arg.AllScope,
		arg.OfficeIds,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpnameSessionsRow{}
	for rows.Next() {
		var i ListOpnameSessionsRow
		if err := rows.Scan(
			&i.StockopnameStockOpnameSession.ID,
			&i.StockopnameStockOpnameSession.OfficeID,
			&i.StockopnameStockOpnameSession.Name,
			&i.StockopnameStockOpnameSession.Period,
			&i.StockopnameStockOpnameSession.Status,
			&i.StockopnameStockOpnameSession.StartedByID,
			&i.StockopnameStockOpnameSession.StartedAt,
			&i.StockopnameStockOpnameSession.ClosedByID,
			&i.StockopnameStockOpnameSession.ClosedAt,
			&i.StockopnameStockOpnameSession.CreatedAt,
			&i.StockopnameStockOpnameSession.UpdatedAt,
			&i.StockopnameStockOpnameSession.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionKpis = `-- name: SessionKpis :one
SELECT
  count(*)::bigint AS total,
  count(*) FILTER (WHERE result = 'found')::bigint AS found,
  count(*) FILTER (WHERE result = 'pending')::bigint AS pending,
  count(*) FILTER (WHERE result IN ('not_found','damaged','misplaced'))::bigint AS variance
FROM stockopname.stock_opname_items
WHERE session_id = $1 AND deleted_at IS NULL
`

type SessionKpisRow struct {
	Total    int64 `json:"total"`
	Found    int64 `json:"found"`
	Pending  int64 `json:"pending"`
	Variance int64 `json:"variance"`
}

func (q *Queries) SessionKpis(ctx context.Context, sessionID uuid.UUID) (SessionKpisRow, error) {
	row := q.db.QueryRow(ctx, sessionKpis, sessionID)
	var i SessionKpisRow
	err := row.Scan(
		&i.Total,
		&i.Found,
		&i.Pending,
		&i.Variance,
	)
	return i, err
}

const setItemFollowup = `-- name: SetItemFollowup :one
UPDATE stockopname.stock_opname_items
SET followup_request_id = $1
WHERE id = $2 AND session_id = $3 AND deleted_at IS NULL
RETURNING id, session_id, asset_id, expected, result, counted_by_id, counted_at, note, created_at, updated_at, deleted_at, followup_request_id, followup_record_id
`

type SetItemFollowupParams struct {
	FollowupRequestID *uuid.UUID `json:"followup_request_id"`
	ID                uuid.UUID  `json:"id"`
	SessionID         uuid.UUID  `json:"session_id"`
}

func (q *Queries) SetItemFollowup(ctx context.Context, arg SetItemFollowupParams) (StockopnameStockOpnameItem, error) {
	row := q.db.QueryRow(ctx, setItemFollowup, arg.FollowupRequestID, arg.ID, arg.SessionID)
	var i StockopnameStockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AssetID,
		&i.Expected,
		&i.Result,
		&i.CountedByID,
		&i.CountedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FollowupRequestID,
		&i.FollowupRecordID,
	)
	return i, err
}

const setItemFollowupRecord = `-- name: SetItemFollowupRecord :one
UPDATE stockopname.stock_opname_items
SET followup_record_id = $1
WHERE id = $2 AND session_id = $3 AND deleted_at IS NULL
RETURNING id, session_id, asset_id, expected, result, counted_by_id, counted_at, note, created_at, updated_at, deleted_at, followup_request_id, followup_record_id
`

type SetItemFollowupRecordParams struct {
	FollowupRecordID *uuid.UUID `json:"followup_record_id"`
	ID               uuid.UUID  `json:"id"`
	SessionID        uuid.UUID  `json:"session_id"`
}

func (q *Queries) SetItemFollowupRecord(ctx context.Context, arg SetItemFollowupRecordParams) (StockopnameStockOpnameItem, error) {
	row := q.db.QueryRow(ctx, setItemFollowupRecord, arg.FollowupRecordID, arg.ID, arg.SessionID)
	var i StockopnameStockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AssetID,
		&i.Expected,
		&i.Result,
		&i.CountedByID,
		&i.CountedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FollowupRequestID,
		&i.FollowupRecordID,
	)
	return i, err
}

const setOpnameItemResult = `-- name: SetOpnameItemResult :one
UPDATE stockopname.stock_opname_items
SET result = $1, note = $2,
    counted_by_id = $3, counted_at = now()
WHERE id = $4 AND session_id = $5 AND deleted_at IS NULL
RETURNING id, session_id, asset_id, expected, result, counted_by_id, counted_at, note, created_at, updated_at, deleted_at, followup_request_id, followup_record_id
`

type SetOpnameItemResultParams struct {
	Result      SharedOpnameItemResult `json:"result"`
	Note        *string                `json:"note"`
	CountedByID *uuid.UUID             `json:"counted_by_id"`
	ID          uuid.UUID              `json:"id"`
	SessionID   uuid.UUID              `json:"session_id"`
}

func (q *Queries) SetOpnameItemResult(ctx context.Context, arg SetOpnameItemResultParams) (StockopnameStockOpnameItem, error) {
	row := q.db.QueryRow(ctx, setOpnameItemResult,
		arg.Result,
		arg.Note,
		arg.CountedByID,
		arg.ID,
		arg.SessionID,
	)
	var i StockopnameStockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AssetID,
		&i.Expected,
		&i.Result,
		&i.CountedByID,
		&i.CountedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FollowupRequestID,
		&i.FollowupRecordID,
	)
	return i, err
}

const setSessionStatus = `-- name: SetSessionStatus :one
UPDATE stockopname.stock_opname_sessions
SET status = $1,
    closed_by_id = $2,
    closed_at = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, office_id, name, period, status, started_by_id, started_at, closed_by_id, closed_at, created_at, updated_at, deleted_at
`

type SetSessionStatusParams struct {
	Status     SharedOpnameSessionStatus `json:"status"`
	ClosedByID *uuid.UUID                `json:"closed_by_id"`
	ClosedAt   pgtype.Timestamptz        `json:"closed_at"`
	ID         uuid.UUID                 `json:"id"`
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) (StockopnameStockOpnameSession, error) {
	row := q.db.QueryRow(ctx, setSessionStatus,
		arg.Status,
		arg.ClosedByID,
		arg.ClosedAt,
		arg.ID,
	)
	var i StockopnameStockOpnameSession
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Period,
		&i.Status,
		&i.StartedByID,
		&i.StartedAt,
		&i.ClosedByID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const snapshotSessionItems = `-- name: SnapshotSessionItems :exec
INSERT INTO stockopname.stock_opname_items (session_id, asset_id, expected, result)
SELECT $1, a.id, true, 'pending'
FROM asset.assets a
WHERE a.office_id = $2
  AND a.status <> 'disposed'
  AND a.deleted_at IS NULL
`

type SnapshotSessionItemsParams struct {
	SessionID uuid.UUID `json:"session_id"`
	OfficeID  uuid.UUID `json:"office_id"`
}

func (q *Queries) SnapshotSessionItems(ctx context.Context, arg SnapshotSessionItemsParams) error {
	_, err := q.db.Exec(ctx, snapshotSessionItems, arg.SessionID, arg.OfficeID)
	return err
}
