// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingTransferRequestsForAsset = `-- name: CountPendingTransferRequestsForAsset :one
SELECT count(*) FROM approval.requests
WHERE type = 'asset_transfer' AND target_id = $1
  AND status = 'pending' AND deleted_at IS NULL
`

// Guard: an asset may have at most one pending asset_transfer approval request.
func (q *Queries) CountPendingTransferRequestsForAsset(ctx context.Context, assetID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingTransferRequestsForAsset, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransfers = `-- name: CountTransfers :one
SELECT count(*) FROM transfer.asset_transfers
WHERE deleted_at IS NULL
  AND ($1::boolean
       OR from_office_id = ANY($2::uuid[])
       OR to_office_id   = ANY($2::uuid[]))
  AND ($3::shared.transfer_status IS NULL OR status = $3)
`

type CountTransfersParams struct {
	AllScope  bool                  `json:"all_scope"`
	OfficeIds []uuid.UUID           `json:"office_ids"`
	Status    *SharedTransferStatus `json:"status"`
}

func (q *Queries) CountTransfers(ctx context.Context, arg CountTransfersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransfers, arg.AllScope, arg.OfficeIds, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer.asset_transfers (
  asset_id, from_office_id, to_office_id, to_room_id, status,
  reason, requested_by_id, approved_by_id, request_id, condition_sent, transfer_date
) VALUES (
  $1, $2, $3, $4,
  'approved', $5, $6, $7, $8,
  $9, $10
)
RETURNING id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note
`

type CreateTransferParams struct {
	AssetID       uuid.UUID                `json:"asset_id"`
	FromOfficeID  uuid.UUID                `json:"from_office_id"`
	ToOfficeID    uuid.UUID                `json:"to_office_id"`
	ToRoomID      *uuid.UUID               `json:"to_room_id"`
	Reason        *string                  `json:"reason"`
	RequestedByID uuid.UUID                `json:"requested_by_id"`
	ApprovedByID  *uuid.UUID               `json:"approved_by_id"`
	RequestID     *uuid.UUID               `json:"request_id"`
	ConditionSent *SharedTransferCondition `json:"condition_sent"`
	TransferDate  pgtype.Date              `json:"transfer_date"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (TransferAssetTransfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.AssetID,
		arg.FromOfficeID,
		arg.ToOfficeID,
		arg.ToRoomID,
		arg.Reason,
		arg.RequestedByID,
		arg.ApprovedByID,
		arg.RequestID,
		arg.ConditionSent,
		arg.TransferDate,
	)
	var i TransferAssetTransfer
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromOfficeID,
		&i.ToOfficeID,
		&i.ToRoomID,
		&i.Status,
		&i.Reason,
		&i.RequestedByID,
		&i.ApprovedByID,
		&i.ShippedDate,
		&i.ReceivedDate,
		&i.ReceivedByID,
		&i.BastNo,
		&i.RequestID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConditionSent,
		&i.TransferDate,
		&i.ReturnNote,
	)
	return i, err
}

const getOpenTransferForAsset = `-- name: GetOpenTransferForAsset :one
SELECT id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note FROM transfer.asset_transfers
WHERE asset_id = $1 AND deleted_at IS NULL
  AND status IN ('approved', 'in_transit')
LIMIT 1
`

// Guard: an asset may have at most one non-terminal transfer row.
func (q *Queries) GetOpenTransferForAsset(ctx context.Context, assetID uuid.UUID) (TransferAssetTransfer, error) {
	row := q.db.QueryRow(ctx, getOpenTransferForAsset, assetID)
	var i TransferAssetTransfer
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromOfficeID,
		&i.ToOfficeID,
		&i.ToRoomID,
		&i.Status,
		&i.Reason,
		&i.RequestedByID,
		&i.ApprovedByID,
		&i.ShippedDate,
		&i.ReceivedDate,
		&i.ReceivedByID,
		&i.BastNo,
		&i.RequestID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConditionSent,
		&i.TransferDate,
		&i.ReturnNote,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note FROM transfer.asset_transfers
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::boolean
       OR from_office_id = ANY($3::uuid[])
       OR to_office_id   = ANY($3::uuid[]))
`

type GetTransferParams struct {
	ID        uuid.UUID   `json:"id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

// Scoped: caller must have the from- or to-office in scope.
func (q *Queries) GetTransfer(ctx context.Context, arg GetTransferParams) (TransferAssetTransfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, arg.ID, arg.AllScope, arg.OfficeIds)
	var i TransferAssetTransfer
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromOfficeID,
		&i.ToOfficeID,
		&i.ToRoomID,
		&i.Status,
		&i.Reason,
		&i.RequestedByID,
		&i.ApprovedByID,
		&i.ShippedDate,
		&i.ReceivedDate,
		&i.ReceivedByID,
		&i.BastNo,
		&i.RequestID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConditionSent,
		&i.TransferDate,
		&i.ReturnNote,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note FROM transfer.asset_transfers
WHERE deleted_at IS NULL
  AND ($1::boolean
       OR from_office_id = ANY($2::uuid[])
       OR to_office_id   = ANY($2::uuid[]))
  AND ($3::shared.transfer_status IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTransfersParams struct {
	AllScope  bool                  `json:"all_scope"`
	OfficeIds []uuid.UUID           `json:"office_ids"`
	Status    *SharedTransferStatus `json:"status"`
	Off       int32                 `json:"off"`
	Lim       int32                 `json:"lim"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]TransferAssetTransfer, error) {
	rows, err := q.db.Query(ctx, listTransfers,
		arg.AllScope,
		arg.OfficeIds,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferAssetTransfer{}
	for rows.Next() {
		var i TransferAssetTransfer
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.FromOfficeID,
			&i.ToOfficeID,
			&i.ToRoomID,
			&i.Status,
			&i.Reason,
			&i.RequestedByID,
			&i.ApprovedByID,
			&i.ShippedDate,
			&i.ReceivedDate,
			&i.ReceivedByID,
			&i.BastNo,
			&i.RequestID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ConditionSent,
			&i.TransferDate,
			&i.ReturnNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByAsset = `-- name: ListTransfersByAsset :many
SELECT id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note FROM transfer.asset_transfers
WHERE asset_id = $1 AND deleted_at IS NULL
  AND ($2::boolean
       OR from_office_id = ANY($3::uuid[])
       OR to_office_id   = ANY($3::uuid[]))
ORDER BY created_at DESC
`

type ListTransfersByAssetParams struct {
	AssetID   uuid.UUID   `json:"asset_id"`
	AllScope  bool        `json:"all_scope"`
	OfficeIds []uuid.UUID `json:"office_ids"`
}

// Per-asset history, scoped by from- or to-office.
func (q *Queries) ListTransfersByAsset(ctx context.Context, arg ListTransfersByAssetParams) ([]TransferAssetTransfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByAsset, arg.AssetID, arg.AllScope, arg.OfficeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferAssetTransfer{}
	for rows.Next() {
		var i TransferAssetTransfer
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.FromOfficeID,
			&i.ToOfficeID,
			&i.ToRoomID,
			&i.Status,
			&i.Reason,
			&i.RequestedByID,
			&i.ApprovedByID,
			&i.ShippedDate,
			&i.ReceivedDate,
			&i.ReceivedByID,
			&i.BastNo,
			&i.RequestID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ConditionSent,
			&i.TransferDate,
			&i.ReturnNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransferReceived = `-- name: SetTransferReceived :one
UPDATE transfer.asset_transfers
SET status = 'received',
    received_date = $1,
    received_by_id = $2,
    bast_no = $3,
    to_room_id = COALESCE($4, to_room_id)
WHERE id = $5 AND status = 'in_transit' AND deleted_at IS NULL
RETURNING id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note
`

type SetTransferReceivedParams struct {
	ReceivedDate pgtype.Date `json:"received_date"`
	ReceivedByID *uuid.UUID  `json:"received_by_id"`
	BastNo       *string     `json:"bast_no"`
	ToRoomID     *uuid.UUID  `json:"to_room_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) SetTransferReceived(ctx context.Context, arg SetTransferReceivedParams) (TransferAssetTransfer, error) {
	row := q.db.QueryRow(ctx, setTransferReceived,
		arg.ReceivedDate,
		arg.ReceivedByID,
		arg.BastNo,
		arg.ToRoomID,
		arg.ID,
	)
	var i TransferAssetTransfer
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromOfficeID,
		&i.ToOfficeID,
		&i.ToRoomID,
		&i.Status,
		&i.Reason,
		&i.RequestedByID,
		&i.ApprovedByID,
		&i.ShippedDate,
		&i.ReceivedDate,
		&i.ReceivedByID,
		&i.BastNo,
		&i.RequestID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConditionSent,
		&i.TransferDate,
		&i.ReturnNote,
	)
	return i, err
}

const setTransferReturned = `-- name: SetTransferReturned :one
UPDATE transfer.asset_transfers
SET status = 'returned',
    return_note = $1,
    received_by_id = $2
WHERE id = $3 AND status = 'in_transit' AND deleted_at IS NULL
RETURNING id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note
`

type SetTransferReturnedParams struct {
	ReturnNote *string    `json:"return_note"`
	ActorID    *uuid.UUID `json:"actor_id"`
	ID         uuid.UUID  `json:"id"`
}

// Receiving side declines the shipment: terminal 'returned', asset never moved.
func (q *Queries) SetTransferReturned(ctx context.Context, arg SetTransferReturnedParams) (TransferAssetTransfer, error) {
	row := q.db.QueryRow(ctx, setTransferReturned, arg.ReturnNote, arg.ActorID, arg.ID)
	var i TransferAssetTransfer
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromOfficeID,
		&i.ToOfficeID,
		&i.ToRoomID,
		&i.Status,
		&i.Reason,
		&i.RequestedByID,
		&i.ApprovedByID,
		&i.ShippedDate,
		&i.ReceivedDate,
		&i.ReceivedByID,
		&i.BastNo,
		&i.RequestID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConditionSent,
		&i.TransferDate,
		&i.ReturnNote,
	)
	return i, err
}

const setTransferShipped = `-- name: SetTransferShipped :one
UPDATE transfer.asset_transfers
SET status = 'in_transit', shipped_date = $1
WHERE id = $2 AND status = 'approved' AND deleted_at IS NULL
RETURNING id, asset_id, from_office_id, to_office_id, to_room_id, status, reason, requested_by_id, approved_by_id, shipped_date, received_date, received_by_id, bast_no, request_id, notes, created_at, updated_at, deleted_at, condition_sent, transfer_date, return_note
`

type SetTransferShippedParams struct {
	ShippedDate pgtype.Date `json:"shipped_date"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) SetTransferShipped(ctx context.Context, arg SetTransferShippedParams) (TransferAssetTransfer, error) {
	row := q.db.QueryRow(ctx, setTransferShipped, arg.ShippedDate, arg.ID)
	var i TransferAssetTransfer
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromOfficeID,
		&i.ToOfficeID,
		&i.ToRoomID,
		&i.Status,
		&i.Reason,
		&i.RequestedByID,
		&i.ApprovedByID,
		&i.ShippedDate,
		&i.ReceivedDate,
		&i.ReceivedByID,
		&i.BastNo,
		&i.RequestID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConditionSent,
		&i.TransferDate,
		&i.ReturnNote,
	)
	return i, err
}
