// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM identity.users
WHERE deleted_at IS NULL
  AND (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
  )
  AND ($2::uuid IS NULL OR role_id = $2)
  AND ($3::uuid IS NULL OR office_id = $3)
  AND ($4::shared.user_status IS NULL OR status = $4)
`

type CountUsersParams struct {
	Search   string            `json:"search"`
	RoleID   *uuid.UUID        `json:"role_id"`
	OfficeID *uuid.UUID        `json:"office_id"`
	Status   *SharedUserStatus `json:"status"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.Search,
		arg.RoleID,
		arg.OfficeID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsers = `-- name: ListUsers :many

SELECT id, employee_id, office_id, name, email, password_hash, google_id, avatar_key, role_id, status, created_at, updated_at, deleted_at, password_changed_at FROM identity.users
WHERE deleted_at IS NULL
  AND (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
  )
  AND ($2::uuid IS NULL OR role_id = $2)
  AND ($3::uuid IS NULL OR office_id = $3)
  AND ($4::shared.user_status IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListUsersParams struct {
	Search   string            `json:"search"`
	RoleID   *uuid.UUID        `json:"role_id"`
	OfficeID *uuid.UUID        `json:"office_id"`
	Status   *SharedUserStatus `json:"status"`
	Off      int32             `json:"off"`
	Lim      int32             `json:"lim"`
}

// User management queries (Superadmin). All respect soft delete.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.RoleID,
		arg.OfficeID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUser{}
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.OfficeID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.GoogleID,
			&i.AvatarKey,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PasswordChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE identity.users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE identity.users
SET name = $2,
    role_id = $3,
    office_id = $4,
    employee_id = $5,
    status = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, employee_id, office_id, name, email, password_hash, google_id, avatar_key, role_id, status, created_at, updated_at, deleted_at, password_changed_at
`

type UpdateUserParams struct {
	ID         uuid.UUID        `json:"id"`
	Name       string           `json:"name"`
	RoleID     uuid.UUID        `json:"role_id"`
	OfficeID   *uuid.UUID       `json:"office_id"`
	EmployeeID *uuid.UUID       `json:"employee_id"`
	Status     SharedUserStatus `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.RoleID,
		arg.OfficeID,
		arg.EmployeeID,
		arg.Status,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.OfficeID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarKey,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}
